import { Header, Footer, JsonLd } from '../components';
import { site, staffingOffer, leadQuestions, staffingFitNote } from '../data';

export const metadata = { title: `Contact ${site.brand}`, description: 'Request a Philippines staffing role plan. Share the tasks, tools, schedule, and review needs.' };

export default function Contact() {
  const siteUrl = `https://${String(site.domain).toLowerCase()}`;
  const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'ContactPage', name: `Contact ${site.brand}`, url: `${siteUrl}/contact` }, { '@type': 'Organization', name: site.brand, url: siteUrl }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Contact', item: `${siteUrl}/contact` }] }] };
  return <><Header /><main className="section"><JsonLd data={schema} /><div className="container two"><div><p className="eyebrow">Philippines staffing intake</p><h1>Map the role before you meet candidates.</h1><p className="lead">Tell us what should move off your team's plate. We will shape a practical brief for Filipino talent around the tasks, tools, schedule, access, and review needs.</p><div className="card"><h2>What the plan covers</h2><ul className="list">{staffingOffer.included.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="card"><h2>Useful details to bring</h2><ul className="list">{leadQuestions.map((q) => <li key={q}>{q}</li>)}</ul></div><p className="callout"><b>Philippines only:</b> {staffingFitNote}</p><p className="disclosure">OffshoreAdvantages.com is an independent informational site. Qualified inquiries may be shared with a Philippines staffing provider that can follow up about Filipino talent.</p></div><form className="card contact-form" action="/thank-you"><label>Name<br /><input required name="name" style={{ width: '100%', padding: 12, margin: '6px 0 14px' }} /></label><label>Email<br /><input required name="email" type="email" style={{ width: '100%', padding: 12, margin: '6px 0 14px' }} /></label><label>Company or website<br /><input name="company" style={{ width: '100%', padding: 12, margin: '6px 0 14px' }} /></label><label>What should the Filipino team member own?<br /><textarea name="tasks" rows={6} style={{ width: '100%', padding: 12, margin: '6px 0 14px' }} /></label><label>What needs the most planning?<br /><select name="concern" style={{ width: '100%', padding: 12, margin: '6px 0 14px' }}><option>Role scope and task fit</option><option>Quality review and reporting</option><option>Coverage and schedule</option><option>Tool access and data safety</option><option>Growing beyond one Philippines-based role</option></select></label><button className="btn" type="submit">Send my Philippines role brief</button></form></div></main><Footer /></>;
}
