export type August20Post = { slug:string; title:string; excerpt:string; published:'2026-08-20'; image:string; sections: readonly { title:string; body:string }[] };

const image = (slug:string) => `/aug20-heroes/${slug}.svg`;
const sources = [
  ['philippines-offshore-capacity-planning','Philippines Offshore Capacity Planning: Match Work to Real Demand','Plan a Philippines-based support lane by queue shape, decision latency, and review capacity, rather than by a vague headcount target.','Capacity planning starts with the work that actually arrives. Separate routine requests from approvals, investigation, rework, and waiting time. A Philippines-based operator can process a defined queue, but a schedule cannot remove a missing decision owner. Map the source channel, expected volume, service window, average handling pattern, and exception rate before discussing coverage.\n\nUse a short observation period and keep the raw counts. Do not turn a small sample into a promised forecast. The useful question is whether the queue has enough repeatability for a documented role, and whether a manager can review the work without becoming the hidden processor of every case.'],
  ['offshore-operations-knowledge-transfer','Offshore Operations Knowledge Transfer: Move Judgment Without Losing Context','A practical handoff method for transferring repeatable offshore operations work while keeping business judgment with the client owner.','Knowledge transfer fails when it is treated as a meeting instead of an evidence trail. For a Philippines-based operations lane, capture the input, intended outcome, sequence, examples, exception signals, and named decision owner. Record why a prior case was handled a certain way, but label policy as policy and preference as preference. That distinction prevents a useful example from becoming an accidental rule.\n\nStart with real, redacted work samples. Ask the operator to explain the next action, the evidence supporting it, and the point where they would stop. A reviewer should be able to see what was understood without rewarding confident guessing.'],
  ['philippines-offshore-inbox-triage','Philippines Offshore Inbox Triage: Turn Messages Into Owned Work','Design an offshore inbox workflow that classifies requests, preserves context, and escalates decisions instead of merely clearing messages.','Inbox triage is an operations problem because a message is not the same thing as a task. A Philippines-based admin operator should record the requester, desired outcome, deadline, source, missing evidence, and approved next action. Labels should describe state: ready, waiting, returned, escalated, or complete, rather than personality or urgency alone.\n\nKeep sensitive attachments in their controlled system and link the record from the queue. A private chat can help clarify a question, but it should not become the only place where the decision lives. The next shift needs a recoverable record, not a search through someone’s memory.'],
  ['offshore-customer-support-coaching-loop','Offshore Customer Support Coaching: Build a Fair Review Loop','Create a Philippines-based customer support coaching cycle that improves observable work without turning a score into an unsupported performance claim.','Coaching is strongest when the reviewer can point to an observable action: the verification step was skipped, the promise was not recorded, or the escalation reason was incomplete. A Philippines-based support agent needs examples tied to the actual queue, not abstract encouragement. Separate policy errors, knowledge gaps, tool defects, and judgment calls before deciding what to coach.\n\nUse a small sample that includes ordinary contacts and difficult cases. Preserve disagreement when the rule is unclear; forcing reviewers to agree can hide a missing definition. The client policy owner resolves interpretation, while the operator receives a clear behavior to repeat, stop, or escalate.'],
  ['offshore-operations-cutover-checklist','Offshore Operations Cutover Checklist: Prove the Handoff Before Launch','A launch checklist for moving a defined operations workflow to Philippines-based talent with visible ownership, access, and exception controls.','A cutover is ready when the workflow can survive a normal case, an absent approver, a source delay, and a handoff between shifts. Write the checks as observable evidence: a named account works, the current SOP is accessible, the reviewer can find the queue, and the escalation contact answers. Do not accept “trained” as proof that the operator can complete the task.\n\nRun a controlled sample with redacted records and mark each failure by cause. A missing permission, unclear acceptance test, and unavailable decision owner require different fixes. Keep launch approval with the accountable client owner; the offshore operator can demonstrate the routine and surface uncertainty.'],
  ['philippines-offshore-reporting-reconciliation','Philippines Offshore Reporting Reconciliation: Make Numbers Traceable','A source-to-report method for Philippines-based reporting support when extracts arrive late, definitions differ, or corrections change the result.','Reporting support should make a number easier to inspect, not merely easier to publish. Define the metric, population, cutoff, timezone, identifiers, exclusions, and owner before the Filipino reporting specialist calculates anything. Preserve the source extract and record transformations so a reviewer can distinguish a data problem from a formula problem.\n\nLate records need an explicit treatment. Compare original and revised values, quantify the affected slice, and state what remains undecided. The specialist can locate duplicates, missing fields, and variance; the metric owner decides definitions, restatements, and business use.'],
  ['offshore-vendor-follow-up-controls','Offshore Vendor Follow-Up Controls: Escalate Evidence, Not Frustration','Keep Philippines-based vendor coordination useful by tying reminders and escalations to acceptance conditions, dependencies, and named owners.','Vendor follow-up becomes noisy when every late reply is treated as the same failure. Start with the agreed acceptance condition, original due date, dependency, and evidence still missing. A Philippines-based coordinator can request a status, attach the source record, and prepare an escalation packet; they should not invent a new requirement or promise a remedy.\n\nUse escalation levels with triggers such as missed acknowledgement, missing evidence, failed acceptance test, or repeated date movement. Record the response and test whether it actually clears the dependency. “Sent” is an activity; acceptance evidence is what permits the next step.'],
  ['philippines-offshore-access-review','Philippines Offshore Access Review: Keep Permissions Aligned to the Role','A recurring access-review routine for Philippines-based support and administration roles that keeps permissions narrow, named, and recoverable.','Access should follow the task, not the person’s convenience. Map every workflow step to the system action required, then remove permissions that do not support an approved step. For a Philippines-based role, use named accounts, strong authentication, a documented owner, and a review date. Shared credentials make both investigation and offboarding harder.\n\nReview changes as well as current access. A clean list can hide an old administrator grant, an active session, an unused token, or a group membership that survived a transfer. The operator can assemble evidence and flag drift; the client security or system owner approves access and handles sensitive exceptions.'],
  ['offshore-admin-calendar-guardrails','Offshore Admin Calendar Guardrails: Coordinate Without Accepting Risk','Give Philippines-based calendar support clear authority to gather options and communicate approved decisions without silently changing priorities or commitments.','Calendar coordination needs more than availability. Capture the purpose, required attendees, timezone, preparation, deadline, priority, and unresolved trade-off. A Philippines-based assistant can identify feasible options, preserve the request, and send an approved selection. They should not decide which customer, legal, financial, safety, or executive commitment can be displaced.\n\nCheck the finished event from the recipient’s view. Verify the time, attendee list, link, notices, and preparation details. Sample a moved meeting and an unavailable approver so the workflow proves how it records the reason rather than presenting a new time as if it were self-authorized.'],
  ['offshore-customer-support-reopen-analysis','Offshore Customer Support Reopen Analysis: Find the Missing Control','Use reopened customer cases to improve a Philippines-based support workflow without blaming the last agent or hiding policy ambiguity.','A reopened case is a sequence, not a score. Identify what the first agent verified, what they promised, what evidence was missing, why the customer returned, and what the next shift had to rediscover. Compare incomplete response, new information, failed promised action, unclear rule, and system defect as separate causes.\n\nSample normal and high-consequence contacts across shifts. Then change the smallest control that would have prevented the return: a verification field, a handoff requirement, an example, or an escalation owner. Support staff can preserve context and route the decision; they should not alter policy to make the reopen rate look better.'],
  ['philippines-offshore-exception-aging','Philippines Offshore Exception Aging: Give Waiting Work a Decision Clock','Create an exception-aging routine for Philippines-based operations teams that makes waiting visible and routes blocked decisions to the right owner.','An exception needs a clock with meaning. Record when it opened, what is waiting, what work may continue, what pauses the clock, and which event closes it. Aging alone is not priority. Group items by cause: missing approval, incomplete intake, conflicting source, system defect, or customer dependency. Each cause needs a different correction.\n\nEscalate with verified facts, missing answer, impact of delay, safe interim action, and a precise request. The operator can maintain the ledger and protect the record. The accountable owner accepts residual risk, sets priority, and approves closure. An item must not be closed simply because it is awkward to report.'],
  ['offshore-operations-change-brief','Offshore Operations Change Brief: Release a New Rule Safely','A compact change-control method for updating Philippines-based operations workflows without leaving old instructions active or confusing the review record.','A process change is a release to people, tools, and decisions. State the effective time, affected queue, reason, owner, examples, and old instruction being retired. A Philippines-based operator should know which version governs a case that arrives near the boundary. Keep the change note with the source record so later review does not confuse a training delay with policy disagreement.\n\nSample the first cases after release, including one where the safe action is to pause. Track questions, exceptions, and mismatches between the written rule and the tool. The operator can acknowledge and apply the approved change; the client owner decides policy, risk acceptance, and any customer-facing consequence.']
] as const;

const expansions = [
  'Build a small evidence table with source, owner, timestamp, expected state, observed state, and next action. Review it at the same checkpoint each cycle, then change one control at a time so the result can be understood. If a measure moves, state whether the population or the process changed. Keep exceptions visible until an authorized owner closes them. This is especially important in a Philippines-based workflow spanning time zones, where a quiet queue can mean completed work, waiting approval, or an unrecorded handoff. The role is successful when another person can continue from the record without asking the original operator to reconstruct the case.',
  'Use a worked example and a difficult example. The worked example shows the normal path; the difficult example shows where the role stops and asks for a decision. Include the source, the action taken, the evidence retained, and the person who accepted the result. Avoid turning a single example into an invented guarantee about speed, quality, or savings. Managers should review the method and the boundary together. Filipino talent can execute approved recurring steps and raise a well-formed exception, while the client retains business judgment, policy ownership, and responsibility for commitments made to customers, vendors, or regulators.',
  'Design the handoff so it survives a shift change. The minimum record should state current status, verified facts, action already taken, open risk, next allowed action, and owner. Do not place the only explanation in a personal message. If the work contains personal information, link to the controlled record and avoid copying unnecessary details into the queue. Test the handoff when the approver is unavailable and when the source system is delayed. A useful workflow acknowledges the request, protects context, and makes waiting explicit rather than encouraging the operator to improvise an answer that the role is not authorized to give.',
  'Review the outcome from the customer or recipient’s point of view. Ask whether the next person can tell what happened, what was promised, what remains uncertain, and who can decide. Then inspect the internal control: named account, source link, approval state, exception reason, and review date. Treat a failed check as information about the workflow, not automatic evidence of individual failure. In a Philippines-based support or administration lane, fair review means separating unclear instructions, unavailable systems, unusual demand, and operator error. Each category points to a different correction and should not be collapsed into a single activity score.',
  'Keep the public guidance bounded. Do not promise a particular result, imply that geography alone solves security or coverage, or suggest that an offshore operator can replace a client decision-maker. State what the workflow can prove and what it cannot. If a legal, financial, privacy, employment, safety, or customer-remedy question appears, route it to the appropriate owner. A well-designed Philippines staffing workflow is useful because it makes recurring work inspectable and exceptions legible. Its value comes from scope, evidence, and accountable review, not from an unsupported claim about certainty.'
] as const;

const routeContexts = [
  'For capacity planning, begin with a queue map rather than a staffing label. Separate arrivals by channel, handling pattern, approval wait, rework, and interruption. A manager can then compare the work that is actually ready with the work that is merely visible. Note the busiest periods, but do not confuse a spike with a permanent requirement. Review a sample with the person who owns the service promise. If the sample reveals missing inputs, fix intake before adding coverage. The operator needs a written stop rule for cases that lack evidence, exceed the role, or need a decision outside the queue.',
  'Knowledge transfer should leave behind a usable decision trail. Choose representative cases, redact sensitive details, and ask the new operator to describe the trigger, normal action, exception signal, and escalation owner. Capture disagreements instead of smoothing them away. They often reveal a policy that was never written down. A client reviewer should approve the final procedure and identify the examples that remain current. The offshore role can learn and apply the approved routine, but it should not turn a memorable case into a new rule without that approval.',
  'Inbox triage improves when the first record answers a few practical questions: what outcome is requested, who is affected, what evidence arrived, what is missing, and what action is allowed now. An acknowledgement can protect the sender from silence while the operator gathers the missing item. Keep the original message linked to the task, and avoid moving sensitive attachments into an informal mailbox. A clean queue distinguishes ready work from waiting work. That distinction matters when another Philippines-based operator takes over after a shift change.',
  'A support coaching loop should examine work that a reviewer can see. Start with a small, mixed sample and mark the exact point where the case left the approved path. Was verification missing, was the record incomplete, did the tool fail, or was the policy unclear? Each answer calls for a different response. Give the agent one behavior to repeat or stop, plus a safe escalation path. Keep customer outcomes and policy decisions with the client owner. Coaching should make the work easier to review, not turn a score into a verdict about a person.',
  'A cutover checklist must test the workflow under ordinary pressure. Confirm that the operator can find the current procedure, open the named account, locate the queue, record evidence, and reach the reviewer. Then test a missing approver, a stale source, and a case that must pause. Mark the cause of every failure. Access defects, unclear acceptance criteria, and unavailable decision owners cannot be fixed by repeating training. The client owner accepts launch risk and approves the boundary. The offshore team demonstrates the routine and records what still blocks safe execution.',
  'Reporting reconciliation starts before the spreadsheet opens. Define the population, source, cutoff, timezone, identifiers, exclusions, and treatment of late rows. Preserve the source extract and show proposed corrections beside the original value. This lets a reviewer tell a calculation error from a definition disagreement. A Philippines-based reporting operator can run the agreed checks and prepare a variance explanation. The metric owner decides whether to restate a result or change the definition. A useful report makes uncertainty visible rather than hiding it behind a polished total.',
  'Vendor follow-up works when each message points to an acceptance condition. Record the original request, due date, dependency, evidence received, and exact item still missing. A coordinator may ask for status, attach the source record, and prepare a concise escalation. They should not invent a substitute requirement or promise that the client has accepted a remedy. Treat acknowledgement, evidence, test result, and final acceptance as different states. That small distinction keeps activity from being mistaken for progress and gives the next owner a clear reason for the escalation.',
  'An access review should be tied to the actual workflow. List each task, the system action it needs, the account that performs it, and the owner who approves the permission. Check group membership, old grants, tokens, sessions, and access that survived a role change. Use named accounts and keep sensitive details out of ordinary queue notes. The operator can assemble evidence and identify drift. The client security or system owner decides whether access changes, whether an exception is accepted, and how an urgent mismatch is handled.',
  'Calendar administration needs a request record that explains more than an open time slot. Capture purpose, attendees, timezone, preparation, deadline, priority, and any fixed commitment. Present feasible options with the trade-off each one carries. The assistant may coordinate an approved choice, but should not silently displace a customer, legal, financial, safety, or executive commitment. After scheduling, inspect the event as a recipient would see it. A moved meeting should retain its reason and source request so another operator can explain the change without guessing.',
  'Reopened cases reveal where a support workflow lost context. Read the first interaction, the promise made, the evidence checked, the next action, and the reason the customer returned. Classify the cause before proposing a fix. A missing field, unclear macro, system defect, new customer fact, and unavailable owner are different problems. Sample cases across shifts and channels, then change one control. The operator can preserve the timeline, acknowledge the gap, and route the decision. They should not rewrite policy just to make a reopen count look better.',
  'Exception aging needs a decision clock that people can interpret. Record when the item opened, what is blocked, what safe work may continue, which event pauses the clock, and who can close it. Group aging by cause so a missing approval is not treated like a system defect. An escalation should include verified facts, the missing decision, delay impact, safe interim action, and a precise request. The queue owner protects the record. The accountable manager sets priority and accepts any residual risk. Closure requires evidence, not relief that the item disappeared.',
  'A process change should tell the operator exactly when the new rule starts and what replaces the old one. Identify the affected queue, owner, examples, effective time, and retired instruction. Test a normal case, a boundary case, and a case where pausing is safest. Record questions from the first review sample and keep the policy owner involved when the written rule conflicts with the tool. A Philippines-based operator can acknowledge and apply an approved change. The client owner controls policy, risk acceptance, and any external commitment.'
] as const;

const sectionPlans = [
  ['Read the queue before staffing','Separate ready work from waiting work','Set a reviewable capacity signal','Plan for the approval gap','Test a quiet period','Review the first forecast','Write the manager decision','Keep the role bounded','Turn the sample into a next step','Close the planning loop'],
  ['Choose the cases that teach the work','Name the judgment in each example','Record the questions that remain','Version the approved routine','Practice the handoff','Review an exception aloud','Keep preference separate from policy','Protect the source record','Test the new operator','Schedule the next refresh'],
  ['Define the requested outcome','Classify before responding','Keep context with the task','Make waiting visible','Route the decision','Protect sensitive attachments','Sample misroutes','Write the acknowledgement','Set shift ownership','Review the labels'],
  ['Observe the support action','Separate cause from score','Coach the next behavior','Use a mixed sample','Keep policy ownership clear','Record disagreement','Review the customer path','Change one control','Protect the agent boundary','Return to the sample'],
  ['Prove access and ownership','Run the ordinary case','Test the missing approver','Classify cutover failures','Confirm the acceptance test','Protect the rollback path','Sample the first shift','Record unresolved risk','Keep approval with the owner','Close the launch review'],
  ['Define the reporting population','Reconcile the source fields','Handle late arrivals','Test the boundary rows','Explain a variance','Separate formula from definition','Keep the extract traceable','Review the accepted result','Assign recurring defects','Set the next cutoff'],
  ['State the acceptance condition','Record the dependency','Send a useful follow-up','Use escalation triggers','Distinguish acknowledgement from evidence','Preserve the commitment','Review repeated delay','Keep promises authorized','Close with proof','Schedule the next check'],
  ['Map task to permission','Check current and historical access','Use named accounts','Review the role change','Handle a mismatch','Keep evidence controlled','Separate review from approval','Record the exception','Remove what is no longer needed','Set the recertification date'],
  ['Capture the calendar request','Show the trade-off','Protect fixed commitments','Coordinate the approved option','Check the recipient view','Record a late change','Escalate the risky conflict','Review timezone assumptions','Sample the finished event','Refine the request form'],
  ['Replay the first contact','Classify the reopen','Preserve the promise','Check the handoff','Sample across shifts','Repair the smallest control','Separate tool and policy defects','Protect customer context','Review the changed case','Repeat the analysis'],
  ['Start the exception clock','Separate work from waiting','Group by cause','Write the escalation packet','Protect ownership across shifts','Set a consequence-based priority','Require evidence for closure','Review old and new items','Keep safe work visible','Return to the decision owner'],
  ['Name the rule change','Retire the old instruction','Test the boundary','Record the first questions','Keep effective time visible','Review the changed queue','Pause when evidence is missing','Separate training from policy','Protect the approval boundary','Set the follow-up sample']
] as const;

export const august20BlogPosts: readonly August20Post[] = sources.map(([slug,title,excerpt,opening], i) => ({
  slug, title, excerpt, published: '2026-08-20', image: image(slug),
  sections: sectionPlans[i].map((sectionTitle, sectionIndex) => ({
    title: sectionTitle,
    body: `${sectionIndex === 0 ? opening : ''} ${routeContexts[i]} ${expansions[(i + sectionIndex) % expansions.length]} ${sectionIndex % 2 === 0 ? opening : routeContexts[i]}`.trim()
  }))
}));
