const thumbnail = '/philippines-team.jpg';

const records = [
  ['offshore-bookkeeping-document-collection', 'Offshore Bookkeeping Document Collection: Make Month-End Inputs Complete', 'bookkeeping document collection', 'separate missing receipts from transactions that need accountant judgment', 'the source file, period, account, and follow-up owner', 'a support worker classifies a transaction instead of flagging it', '2026-08-13'],
  ['philippines-customer-renewal-coordination', 'Philippines Customer Renewal Coordination: Keep Decisions With the Account Owner', 'customer renewal coordination', 'assemble account history and customer questions before a renewal conversation', 'the renewal date, approved terms, and owner response', 'a tentative renewal is described as accepted', '2026-08-13'],
  ['offshore-claims-processing-administration', 'Offshore Claims Processing Administration: Route Evidence Before Review', 'claims processing administration', 'check whether a claim packet has the required identifiers and attachments', 'the intake checklist, received evidence, and examiner handoff', 'an incomplete claim is placed in the review queue as ready', '2026-08-13'],
  ['philippines-real-estate-listing-administration', 'Philippines Real Estate Listing Administration: Keep Changes Traceable', 'real estate listing administration', 'compare proposed listing edits with the approved source and market owner', 'the source field, requested edit, and publication approval', 'a listing update changes a material property detail without review', '2026-08-13'],
  ['offshore-technical-support-ticket-triage', 'Offshore Technical Support Ticket Triage: Sort Symptoms Before Solutions', 'technical support ticket triage', 'capture the user symptom, environment, reproduction status, and urgency', 'the original report, diagnostic steps, and assigned specialist', 'a triage note presents a guess as a technical resolution', '2026-08-13'],
  ['philippines-healthcare-scheduling-support', 'Philippines Healthcare Scheduling Support: Protect Patient Choice and Privacy', 'healthcare scheduling support', 'offer only approved appointment options and route clinical questions', 'the scheduling request, consent path, and clinic owner', 'a scheduling assistant interprets symptoms or discloses protected details', '2026-08-13'],
  ['offshore-hr-records-administration', 'Offshore HR Records Administration: Update Files Without Losing History', 'HR records administration', 'match an approved personnel change to the correct employee record', 'the authorization, effective date, and before-after audit note', 'an old record is overwritten so the reason for change disappears', '2026-08-13'],
  ['philippines-ecommerce-returns-coordination', 'Philippines E-commerce Returns Coordination: Close the Loop on Exceptions', 'e-commerce returns coordination', 'match the customer request to order facts and the approved returns rule', 'the order event, item condition, disposition, and next owner', 'a return exception is promised before the merchant decides', '2026-08-13'],
  ['offshore-vendor-onboarding-administration', 'Offshore Vendor Onboarding Administration: Separate Collection From Approval', 'vendor onboarding administration', 'collect required vendor information and identify missing compliance fields', 'the submitted form, verification status, and approving owner', 'collected information is treated as approval to activate a vendor', '2026-08-13'],
  ['philippines-property-maintenance-coordination', 'Philippines Property Maintenance Coordination: Turn Reports Into Safe Work Orders', 'property maintenance coordination', 'record location, access limits, urgency, and the requested repair outcome', 'the resident report, work order, vendor update, and close check', 'a safety concern is handled as routine maintenance', '2026-08-13'],
  ['offshore-sales-operations-data-hygiene', 'Offshore Sales Operations Data Hygiene: Improve CRM Records Carefully', 'sales operations data hygiene', 'identify duplicates and stale fields before proposing a CRM change', 'the original value, evidence, change reason, and sample review', 'a cleanup removes context that a seller needs for a live opportunity', '2026-08-13'],
  ['philippines-insurance-policy-service-support', 'Philippines Insurance Policy Service Support: Route Facts Without Advice', 'insurance policy service support', 'record the policyholder request and distinguish service facts from coverage questions', 'the policy identifier, requested change, and licensed owner', 'a service reply implies that a claim or coverage decision is settled', '2026-08-13'],
  ['offshore-construction-invoice-administration', 'Offshore Construction Invoice Administration: Check Packets Before Payment Review', 'construction invoice administration', 'match invoice fields to the contract, purchase order, and receiving evidence', 'the invoice packet, variance note, and payment approver', 'an administrative match is mistaken for authorization to pay', '2026-08-13'],
  ['philippines-recruiting-candidate-scheduling', 'Philippines Recruiting Candidate Scheduling: Make Every Handoff Respectful', 'recruiting candidate scheduling', 'confirm availability, interview context, accommodations, and the right contact', 'the candidate preference, confirmed slot, and interviewer owner', 'private candidate information is copied into an unnecessary channel', '2026-08-13'],
  ['offshore-subscription-support-escalations', 'Offshore Subscription Support Escalations: Make Account Changes Reviewable', 'subscription support escalations', 'classify the customer request and identify which account action is permitted', 'the customer request, account state, approval, and result', 'a support reply changes a plan or refund without authority', '2026-08-13'],
  ['philippines-logistics-exception-desk', 'Philippines Logistics Exception Desk: Give Delays a Named Next Step', 'logistics exception handling', 'pair the carrier event with the customer promise and operational owner', 'the shipment milestone, exception reason, and next checkpoint', 'an estimate becomes a customer guarantee', '2026-08-13'],
  ['offshore-nonprofit-grant-administration', 'Offshore Nonprofit Grant Administration: Keep Evidence With the Requirement', 'grant administration', 'map each requested grant field to its source document and reviewer', 'the requirement, source citation, submission status, and owner', 'a missing attachment is silently filled with an assumption', '2026-08-13'],
  ['philippines-digital-asset-metadata-support', 'Philippines Digital Asset Metadata Support: Keep the Library Findable', 'digital asset metadata support', 'apply approved naming and tagging rules while flagging ambiguous rights information', 'the asset version, metadata change, source, and approver', 'an assistant invents a rights statement or overwrites the master asset', '2026-08-13'],
  ['offshore-education-enrollment-administration', 'Offshore Education Enrollment Administration: Route Records With Care', 'education enrollment administration', 'check enrollment forms for completeness without deciding eligibility', 'the submitted record, missing field, privacy path, and registrar owner', 'a missing detail is interpreted as an admissions decision', '2026-08-13'],
  ['philippines-fleet-service-administration', 'Philippines Fleet Service Administration: Keep Vehicle Issues Moving', 'fleet service administration', 'record the vehicle, operational impact, inspection facts, and dispatch authority', 'the service request, odometer or asset identifier, vendor update, and closure check', 'an unsafe vehicle is returned to service without the responsible decision', '2026-08-13'],
  ['offshore-market-research-interview-coordination', 'Offshore Market Research Interview Coordination: Protect the Study Record', 'market research interview coordination', 'schedule approved participants and preserve consent and study context', 'the recruitment source, consent status, interview slot, and researcher owner', 'a coordinator changes the study screener or exposes participant identity', '2026-08-13'],
  ['philippines-accounts-payable-exception-routing', 'Philippines Accounts Payable Exception Routing: Surface Mismatches Early', 'accounts payable exception routing', 'compare invoice, purchase order, and receipt facts before routing a mismatch', 'the three-way match status, exception reason, and approver', 'a discrepancy is forced through because the queue is old', '2026-08-13'],
] as const;

export const august13BlogPosts = records.map(([slug, title, focus, , , , published]) => ({
  slug, title,
  excerpt: `A practical guide to ${focus} for leaders defining a Philippines-based support role with clear evidence, ownership, and approval boundaries.`,
  minutes: 9,
  published,
  image: thumbnail,
  citations: ['https://www.nist.gov/privacy-framework', 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm'],
}));

export const august13BlogDetails = Object.fromEntries(records.map(([slug, title, focus, first, proof, risk]) => [slug, {
  keyTakeaways: [`Define the input and finish line for ${focus}.`, `Keep ${first} within a written approval boundary.`, `Review ${proof} rather than relying on activity totals.`],
  sections: [
    { title: 'Name the request and its finished state', body: `${title} works best when the first request is concrete. Describe the source, required fields, expected output, due point, and person who accepts the work. For ${focus}, use two real examples and one deliberately incomplete example so the support role can recognize when to pause.` },
    { title: 'Separate preparation from authority', body: `A Philippines-based support role can gather facts, update an approved record, and route the next action. It should not make the decision reserved for the client, accountant, clinician, licensed specialist, registrar, or other accountable owner. In this lane, ${first}. Put that boundary beside the task rather than hiding it in general policy.` },
    { title: 'Keep a reviewable evidence trail', body: `The useful record contains ${proof}. Store the source and the decision in the approved system, use named accounts, and record why an exception was routed. A private message may alert a manager, but it should not be the only place where a business-critical decision survives.` },
    { title: 'Sample ordinary work and exceptions', body: `Review a normal case and a difficult case together. Check factual accuracy, completeness, timeliness, and whether the next owner can act without repeating the investigation. Watch for the failure where ${risk}; record the missing rule or source field that made it possible.` },
    { title: 'Improve one control at a time', body: `After a review, change one instruction, example, field, or escalation rule and assign an owner for the revision. Keep a short record of what changed and why. Expand the role only when it can produce consistent, reviewable outcomes for ${focus} without turning unclear decisions into silent guesses.` },
  ],
  internalLinks: [{ label: 'Review operations support', href: '/services/operations-support', note: 'Build the role around a visible queue and named reviewer.' }, { label: 'Read the handoff workflow guide', href: '/blog/offshore-team-handoff-workflow', note: 'Keep status and ownership with the work.' }],
  relatedArticles: ['offshore-team-handoff-workflow', 'offshore-outsourcing-access-control', 'outsourcing-operations-reporting'],
  banners: [{ label: 'Role planning checkpoint', title: 'Turn the guide into a role brief', body: 'List the work, tools, reviewer, and approval limits before launch.', href: '/contact-us', linkText: 'Plan the role' }, { label: 'Next step', title: 'Start with a controlled queue', body: 'Use a small sample a manager can inspect before increasing volume.', href: '/contact-us', linkText: 'Scope the workflow' }, { label: 'Ready to scope?', title: 'Make the handoff visible', body: 'Keep decisions and open risks with the approved record.', href: '/contact-us', linkText: 'Discuss the workflow' }],
  sources: [{ name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Reference for identifying privacy risk and selecting safeguards.' }, { name: 'International Labour Organization guidance', url: 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm', note: 'Reference for clear expectations and accountable work arrangements.' }],
}])) as Record<string, any>;
