const thumbnail = '/philippines-team.jpg';

const records = [
  { slug: 'offshore-accounts-receivable-follow-up', title: 'Offshore Accounts Receivable Follow-Up: Keep Promises and Evidence Together', published: '2026-08-12', focus: 'receivables follow-up', first: 'separate factual reminders from payment decisions', proof: 'the account record, promise date, and next owner', risk: 'a customer is contacted twice after making a payment' },
  { slug: 'philippines-property-management-admin', title: 'Philippines Property Management Admin: Organize Requests Without Losing Context', published: '2026-08-12', focus: 'property management administration', first: 'sort maintenance, tenant, and vendor requests by urgency and authority', proof: 'the request status, property identifier, and approved next action', risk: 'a contractor receives an instruction without owner approval' },
  { slug: 'offshore-insurance-document-intake', title: 'Offshore Insurance Document Intake: Build a Reviewable First Pass', published: '2026-08-12', focus: 'insurance document intake', first: 'identify the document type and missing fields before routing it', proof: 'the received-file checklist and reviewer decision', risk: 'an incomplete document is treated as a complete submission' },
  { slug: 'philippines-ecommerce-catalog-support', title: 'Philippines E-commerce Catalog Support: Keep Product Records Consistent', published: '2026-08-12', focus: 'e-commerce catalog support', first: 'define which product fields may be changed and what needs approval', proof: 'the source record, change reason, and reviewer sample', risk: 'a listing change removes a detail customers rely on' },
  { slug: 'offshore-logistics-tracking-desk', title: 'Offshore Logistics Tracking Desk: Turn Status Questions Into Clear Actions', published: '2026-08-12', focus: 'logistics tracking support', first: 'match each status question to the carrier record and escalation rule', proof: 'the tracking event, customer promise, and next checkpoint', risk: 'an estimated arrival is presented as a guarantee' },
  { slug: 'philippines-medical-practice-admin-boundaries', title: 'Philippines Medical Practice Admin: Define Safe Administrative Boundaries', published: '2026-08-12', focus: 'medical practice administration', first: 'limit the role to scheduling, records preparation, and approved communication', proof: 'the request type, privacy path, and named clinical owner', risk: 'administrative staff are asked to interpret clinical information' },
  { slug: 'offshore-real-estate-lead-coordination', title: 'Offshore Real Estate Lead Coordination: Qualify the Handoff, Not the Buyer', published: '2026-08-12', focus: 'real estate lead coordination', first: 'capture contact permission, stated need, and the licensed owner', proof: 'the lead source, consent record, and next response', risk: 'an assistant gives advice that belongs to a licensed professional' },
  { slug: 'philippines-legal-intake-administration', title: 'Philippines Legal Intake Administration: Route Facts Without Giving Advice', published: '2026-08-12', focus: 'legal intake administration', first: 'record the matter category, urgency, and requested callback without interpreting it', proof: 'the intake fields, conflict-check status, and attorney owner', risk: 'a prospective client receives an implied legal conclusion' },
  { slug: 'offshore-podcast-production-coordination', title: 'Offshore Podcast Production Coordination: Make the Editorial Handoff Specific', published: '2026-08-12', focus: 'podcast production coordination', first: 'turn each episode request into assets, deadlines, and approval points', proof: 'the episode brief, file status, and final approver', risk: 'an unapproved edit is published as final' },
  { slug: 'philippines-hr-interview-coordination', title: 'Philippines HR Interview Coordination: Protect Candidate Experience', published: '2026-08-12', focus: 'interview coordination', first: 'confirm availability, role context, and who may answer candidate questions', proof: 'the consented contact record and interview handoff', risk: 'private candidate information is copied into an informal channel' },
  { slug: 'offshore-purchase-order-administration', title: 'Offshore Purchase Order Administration: Keep Preparation Separate From Approval', published: '2026-08-12', focus: 'purchase order administration', first: 'match a request to an approved vendor, item, and cost center', proof: 'the request source, approval trail, and receiving status', risk: 'a prepared order is mistaken for permission to buy' },
  { slug: 'philippines-nonprofit-donor-support', title: 'Philippines Nonprofit Donor Support: Handle Questions With Care', published: '2026-08-12', focus: 'nonprofit donor support', first: 'identify the donor request and use the approved privacy and acknowledgment path', proof: 'the contact preference, case outcome, and escalation owner', risk: 'a sensitive donor detail is exposed in a broad team note' },
  { slug: 'offshore-saas-customer-success-admin', title: 'Offshore SaaS Customer Success Admin: Keep Account Health Actionable', published: '2026-08-12', focus: 'SaaS customer success administration', first: 'turn product usage and customer requests into owned follow-up items', proof: 'the account signal, agreed outcome, and next review date', risk: 'an internal health label is presented to a customer as a fact' },
  { slug: 'philippines-travel-operations-support', title: 'Philippines Travel Operations Support: Coordinate Changes Without Overpromising', published: '2026-08-12', focus: 'travel operations support', first: 'record itinerary facts, supplier rules, and the authority for each change', proof: 'the booking record, traveler request, and confirmed supplier response', risk: 'a tentative option is described as a confirmed booking' },
  { slug: 'offshore-construction-project-admin', title: 'Offshore Construction Project Admin: Keep Field Information Moving', published: '2026-08-12', focus: 'construction project administration', first: 'route submittals, meeting actions, and document revisions to named owners', proof: 'the revision, due date, and acceptance record', risk: 'an outdated drawing is used because the latest version is unclear' },
  { slug: 'philippines-finance-reconciliation-support', title: 'Philippines Finance Reconciliation Support: Surface Exceptions Early', published: '2026-08-12', focus: 'finance reconciliation support', first: 'compare approved source records and isolate mismatches for review', proof: 'the source pair, variance explanation, and approver', risk: 'a missing record is silently forced to balance' },
  { slug: 'offshore-marketplace-seller-support', title: 'Offshore Marketplace Seller Support: Resolve Cases With a Traceable Record', published: '2026-08-12', focus: 'marketplace seller support', first: 'classify the seller issue, applicable policy, and evidence needed', proof: 'the case category, policy reference, and resolution owner', risk: 'a policy exception is granted without a documented decision' },
  { slug: 'philippines-digital-agency-client-coordination', title: 'Philippines Digital Agency Client Coordination: Make Revisions Unambiguous', published: '2026-08-12', focus: 'digital agency client coordination', first: 'turn client feedback into a versioned task with one approver', proof: 'the requested change, asset version, and acceptance note', risk: 'a designer works from conflicting feedback in separate channels' },
  { slug: 'offshore-facilities-service-desk', title: 'Offshore Facilities Service Desk: Prioritize Requests by Impact', published: '2026-08-12', focus: 'facilities service desk support', first: 'capture location, safety impact, and access constraints before dispatch', proof: 'the work order, vendor update, and closure check', risk: 'a safety-related request is queued behind standard work' },
  { slug: 'philippines-technical-documentation-support', title: 'Philippines Technical Documentation Support: Keep Instructions Testable', published: '2026-08-12', focus: 'technical documentation support', first: 'write the user goal, prerequisites, and expected result before editing instructions', proof: 'the tested steps, version, and subject-matter review', risk: 'a plausible instruction is published without being tested' },
  { slug: 'offshore-membership-administration', title: 'Offshore Membership Administration: Keep Renewals and Exceptions Visible', published: '2026-08-12', focus: 'membership administration', first: 'separate standard renewal notices from payment and cancellation decisions', proof: 'the member request, account state, and authorized outcome', risk: 'a failed payment triggers a message that ignores the member’s context' },
  { slug: 'philippines-supply-chain-data-cleanup', title: 'Philippines Supply Chain Data Cleanup: Improve Records Without Erasing History', published: '2026-08-12', focus: 'supply chain data cleanup', first: 'identify duplicate, stale, and conflicting fields before changing a source record', proof: 'the original value, change reason, and review sample', risk: 'a cleanup removes the history needed to explain a shipment issue' },
] as const;

export const august11BlogPosts = records.map((record) => ({
  slug: record.slug,
  title: record.title,
  excerpt: `A practical guide to ${record.focus} for leaders building a Philippines-based role with clear ownership, review, and customer-safe boundaries.`,
  minutes: 10,
  published: record.published,
  image: thumbnail,
  citations: ['https://www.nist.gov/privacy-framework', 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm'],
}));

export const august11BlogDetails = Object.fromEntries(records.map((record) => [record.slug, {
  keyTakeaways: [`Define the queue and finish line for ${record.focus}.`, `Keep ${record.first} within written approval boundaries.`, `Review ${record.proof} instead of relying on activity counts.`],
  sections: [
    { title: 'Define the request before assigning it', body: `${record.title} starts with a request that another person can understand. Write the input, expected output, due time, and acceptance owner. For ${record.focus}, state which cases are standard and which need a client decision before work begins.` },
    { title: 'Separate preparation from authority', body: `The support role can prepare information, update the approved record, and route the next step. Keep judgment, money movement, customer promises, legal interpretation, and other high-impact decisions with a named owner. In particular, ${record.first}.` },
    { title: 'Keep evidence with the work', body: `A useful record shows ${record.proof}. Use named accounts, the minimum access needed, and an approved system for customer or business context. Do not make a private message the only place where a decision or exception exists.` },
    { title: 'Review normal cases and exceptions', body: `Sample standard work and at least one difficult case. Check accuracy, completeness, timeliness, and whether the next owner can act without repeating the investigation. Watch for the common failure where ${record.risk}; record the cause rather than blaming the person first.` },
    { title: 'Improve the role from what you learn', body: `After review, clarify one instruction, example, or escalation rule at a time. Assign an owner for the change and keep the previous decision history. Expand the queue only when the role can produce consistent, reviewable outcomes for ${record.focus}.` },
  ],
  internalLinks: [{ label: 'Review operations support', href: '/services/operations-support', note: 'Build the role around a visible queue and named reviewer.' }, { label: 'Read the handoff workflow guide', href: '/blog/offshore-team-handoff-workflow', note: 'Keep status and ownership with the work.' }],
  relatedArticles: ['offshore-team-handoff-workflow', 'offshore-outsourcing-access-control', 'outsourcing-operations-reporting'],
  banners: [{ label: 'Role planning checkpoint', title: 'Turn the guide into a role brief', body: 'List the work, tools, reviewer, and approval limits before launch.', href: '/contact-us', linkText: 'Plan the role' }, { label: 'Next step', title: 'Start with a controlled queue', body: 'Use a small sample a manager can inspect before increasing volume.', href: '/contact-us', linkText: 'Scope the workflow' }, { label: 'Ready to scope?', title: 'Make the handoff visible', body: 'Keep decisions and open risks with the approved record.', href: '/contact-us', linkText: 'Discuss the workflow' }],
  sources: [{ name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Reference for identifying privacy risk and selecting safeguards.' }, { name: 'International Labour Organization guidance', url: 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm', note: 'Reference for clear expectations and accountable work arrangements.' }],
}])) as Record<string, any>;
