const thumbnail = '/philippines-team.jpg';
type Row = readonly [string, string, string, string, string, string, string, string];
const records: readonly Row[] = [
 ['philippines-operations-support-work-queue-design','Philippines Operations Support Work Queues: Design Coverage Around Decisions','operations support work queues','A queue is useful only when urgency, dependency, and decision ownership are visible together.','Separate completable work from work waiting on a client decision.','A queue sorted only by age hides blocked work.','2026-08-17','Move blocked items to the right owner rather than asking an operator to guess.'],
 ['offshore-customer-support-escalation-matrix','Offshore Customer Support Escalation Matrices: Keep Promises With the Owner','customer support escalation matrices','Support quality depends on a precise boundary between explaining an approved answer and making a new promise.','Map refunds, account, safety, and policy exceptions to named owners.','A friendly response can create an unauthorized commitment.','2026-08-17','Test ordinary, urgent, and contradictory cases before expanding coverage.'],
 ['philippines-admin-support-inbox-ownership','Philippines Admin Support Inbox Ownership: Preserve Context Across the Day','admin support inbox ownership','Inbox delegation works when every message has a next action, owner, and deadline.','Use labels for waiting, drafting, approval, and closed work.','Forwarding a message without history forces reconstruction.','2026-08-17','Review reopened threads to find missing context, not just unread-count reduction.'],
 ['offshore-reporting-qa-source-reconciliation','Offshore Reporting and QA: Reconcile Sources Before Publishing a Number','reporting and QA source reconciliation','Reporting should expose source disagreement rather than smooth it into a confident figure.','Define source hierarchy, period, denominator, and reviewer for every metric.','A spreadsheet can be arithmetically correct but use the wrong population.','2026-08-17','Keep a variance note beside the metric and route definition disputes.'],
 ['philippines-customer-support-shift-handoff','Philippines Customer Support Shift Handoffs: Transfer the Case, Not the Guess','customer support shift handoffs','A handoff preserves what the customer was told, checked, and still permitted.','Require case state, next action, promise boundary, and escalation reason.','Absent reasoning makes the next shift repeat failed steps.','2026-08-17','Audit cases at both ends of coverage, including routine cases.'],
 ['offshore-operations-support-sop-ownership','Offshore Operations SOPs: Assign an Owner for Every Changeable Step','operations SOP ownership','A procedure is control only when somebody owns its examples, exceptions, and review date.','Write the normal path separately from stop conditions.','An unowned SOP becomes stale while operators follow it.','2026-08-17','Review the SOP after a real exception and classify the cause.'],
 ['philippines-admin-support-calendar-triage','Philippines Admin Support Calendar Triage: Protect the Meeting Purpose','calendar triage','Scheduling support should reduce coordination work without changing the decision a meeting must produce.','Capture outcome, attendees, preparation, timezone, and trade-offs.','A full meeting can fail when its question disappears.','2026-08-17','Sample rescheduled meetings and check that decision context survived.'],
 ['offshore-customer-support-knowledge-source-control','Offshore Customer Support Knowledge Sources: Stop Answers at the Evidence Gap','customer support knowledge source control','The safest answer is bounded by the current approved source, not confidence.','Version policy answers, identify source owners, and route contradictions.','An old help article can turn a fast reply into a policy error.','2026-08-17','Include stale-source and conflicting-source examples in review.'],
 ['philippines-reporting-qa-exception-review','Philippines Reporting QA Exception Reviews: Explain Why a Metric Failed','reporting QA exception reviews','Exception review should distinguish bad input, definition, calculation, and dependency defects.','Give each defect category an example and require source evidence.','A pass-rate number cannot tell a manager what to fix.','2026-08-17','Track exception types by period, not as a permanent individual score.'],
 ['offshore-admin-support-approval-routing','Offshore Admin Support Approval Routing: Complete the Packet Without Taking the Decision','admin approval routing','Preparation creates leverage when it makes an authorized decision easy to inspect.','Collect fields, source documents, missing evidence, and approver.','A complete packet can be mistaken for approval.','2026-08-17','Return incomplete packets with precise missing-field reasons.'],
 ['philippines-customer-support-identity-check-boundaries','Philippines Customer Support Identity Checks: Keep Verification Inside the Role Boundary','customer support identity checks','A support operator can run an approved check without inventing a substitute.','List allowed factors, stop conditions, escalation owner, and minimum record.','Urgency can pressure an agent to bypass account protection.','2026-08-17','Use redacted mismatch, recovery, and sensitive-data examples.'],
 ['offshore-operations-support-vendor-follow-up','Offshore Operations Vendor Follow-Up: Turn Promises Into Checkpoints','vendor follow-up','Follow-up verifies an expected deliverable instead of producing more status noise.','Record commitment, evidence due, dependency, checkpoint, and owner.','“In progress” is not proof a dependency cleared.','2026-08-17','Escalate missed checkpoints with the original evidence gap.'],
 ['philippines-admin-support-document-version-control','Philippines Admin Support Document Control: Route the Right Version','document version control','Document administration is a source-of-truth problem before a filing problem.','Capture identity, effective date, version, access class, and approver.','A neatly named file can still be obsolete or overexposed.','2026-08-17','Test duplicates, superseded versions, and unclear effective dates.'],
 ['offshore-customer-support-refund-escalation','Offshore Customer Support Refund Escalation: Separate Facts From Permission','refund escalation','Support can assemble order facts while an authorized owner decides exceptions.','Define evidence, policy path, approval owner, and permitted wording.','A calming promise can create financial consequences.','2026-08-17','Review escalations for missing evidence and overpromising language.'],
 ['philippines-reporting-qa-reconciliation-calendar','Philippines Reporting QA Calendars: Make Period Cutoffs Explicit','reporting period cutoffs','Reporting fails quietly when systems close periods on different dates.','Publish cutoff, timezone, late-arrival treatment, and restatement owner.','Late transactions can be counted twice or omitted.','2026-08-17','Compare normal close with late-source reconciliation.'],
 ['offshore-admin-support-travel-coordination-boundaries','Offshore Admin Support Travel Coordination: Preserve Approval and Passenger Context','travel coordination','Travel administration organizes approved options while safety and exceptions remain owned.','Record requirements, policy, itinerary facts, approvals, and constraints.','An unstated preference or exception creates risk and rework.','2026-08-17','Check changes preserve rationale, approval trail, and communication.'],
 ['philippines-customer-support-queue-priority','Philippines Customer Support Queue Priority: Rank Impact Before Age','support queue priority','Priority is a rule about customer impact and risk, not only ticket age.','Combine consequence, deadline, dependency, vulnerability, and escalation.','Age-only ordering can bury severe new issues.','2026-08-17','Have the owner explain each top position in a mixed sample.'],
 ['offshore-operations-support-access-review','Offshore Operations Support Access Reviews: Match Permissions to Actual Work','operations access reviews','Access should follow defined work and shrink when the role changes.','Inventory systems, actions, fields, named accounts, reviewer, and removal trigger.','Permissions accumulate when nobody compares them with actual work.','2026-08-17','Review access after a task retires or an operator changes lanes.'],
 ['philippines-admin-support-data-minimization','Philippines Admin Support Data Minimization: Give the Role Only What the Task Needs','admin support data minimization','Narrow access improves privacy and task clarity around a specific outcome.','Remove fields, exports, downloads, and retention that do not help.','Copying a whole record adds exposure without improving decisions.','2026-08-17','Ask whether each field is necessary and removed at close.'],
 ['offshore-customer-support-quality-sampling','Offshore Customer Support Quality Sampling: Review Cases That Teach You Something','customer support quality sampling','A sample should reveal risk and instruction gaps, not just produce a score.','Stratify by channel, case type, escalation, newness, and outcome.','A sample excluding difficult cases flatters a weak boundary.','2026-08-17','Record the sample frame and selection reason.'],
 ['philippines-reporting-qa-metric-definition','Philippines Reporting QA Metric Definitions: Stop Counting the Wrong Work','metric definition control','Evidence requires explicit population, event, period, exclusions, and owner.','Write a metric card with an example that should not count.','Teams can report different numbers accurately under different definitions.','2026-08-17','Resolve definition disputes before changing formulas or coaching.'],
 ['offshore-admin-support-remote-onboarding','Offshore Admin Support Onboarding: Train the Handoff Before the Volume','admin support onboarding','A new role should prove it can receive, perform, pause, and hand off work before full volume.','Use redacted samples, limited access, a reviewer, and stop rules.','Ideal examples leave operators unprepared for incomplete requests.','2026-08-17','Advance on repeatable boundary judgment, not speed alone.'],
];

export const august17BlogPosts = records.map(([slug,title,focus,thesis,boundary,risk,published]) => ({ slug, title, excerpt: `${thesis} A practical guide for leaders designing Philippines-based ${focus} with clear ownership and reviewable evidence.`, minutes: 10, published, image: thumbnail, citations: ['https://www.nist.gov/privacy-framework','https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm'] }));
export const august17BlogDetails = Object.fromEntries(records.map(([slug,title,focus,thesis,boundary,risk,,checkpoint]) => [slug, { keyTakeaways: [thesis,boundary,checkpoint], sections: [
 { title: 'Define the work and finish line', body: `${title} starts with the real queue, not a job title. For ${focus}, document the input, output, source systems, timing, and named accepting owner. Include an ordinary and incomplete case so a Philippines-based operator can distinguish work to complete from work to pause.` },
 { title: 'Keep preparation separate from authority', body: `${boundary} Write the boundary beside the task and name the owner who decides exceptions. The operator can make facts inspectable, but should not convert a draft, match, status, or escalation into permission belonging to the client, manager, specialist, or system owner.` },
 { title: 'Leave evidence with the record', body: `A useful ${focus} record shows the source used, action taken, unresolved question, and next checkpoint. Keep the original request and important reasoning in the approved work system. A private message may alert a reviewer, but should not be the only place a decision survives.` },
 { title: 'Test the difficult case', body: `Test a normal case, missing-input case, and boundary case. Watch for this failure: ${risk} Classify whether the missing control was an input, instruction, access rule, review step, or owner response. That diagnosis is more useful than a generic reminder to be careful.` },
 { title: 'Improve coverage from review evidence', body: `${checkpoint} After review, change one example, field, escalation rule, or permission and assign an owner. Expand the queue only when the role produces consistent, inspectable outcomes without hiding uncertainty or moving client judgment into an offshore support task.` },
 ], internalLinks: [{label:'Review operations support',href:'/services/operations-support',note:'Define the queue, reviewer, and approval boundary.'},{label:'Review customer support',href:'/services/customer-support',note:'Keep customer promises and exceptions with the right owner.'}], banners: [{label:'Role planning checkpoint',title:'Turn the guide into a clear role brief',body:'List the work queue, tools, reviewer, and approval limits before expanding coverage.',href:'/contact-us',linkText:'Plan the role'},{label:'Next step',title:'Start with a reviewable sample',body:'Use normal and exception cases to test the handoff before volume increases.',href:'/contact-us',linkText:'Scope the workflow'},{label:'Ready to scope?',title:'Make the boundary visible',body:'Keep decisions and open risks with the approved record.',href:'/contact-us',linkText:'Discuss the workflow'}], sources: [{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Reference for identifying privacy risk and selecting safeguards.'},{name:'International Labour Organization guidance',url:'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm',note:'Reference for clear expectations and accountable work arrangements.'}] }])) as Record<string, any>;
