const image = '/philippines-team.jpg';
type Topic = { slug: string; title: string; focus: string; question: string; decision: string; failure: string; test: string; boundary: string; records: string; cadence: string; published: string };

const topics: readonly Topic[] = [
 { slug:'philippines-operations-support-intake-completeness', title:'Philippines Operations Support Intake: Test Completeness Before Work Starts', focus:'operations support intake', question:'whether a request contains enough information to enter a Philippines-based operations queue', decision:'which fields are essential, which can be clarified, and which require the client owner', failure:'operators beginning incomplete work and hiding the missing decision inside a private message', test:'a mixed sample of complete, ambiguous, duplicated, and time-sensitive requests', boundary:'the operator can identify and route missing information but cannot invent scope or priority', records:'request source, required fields, missing evidence, next owner, deadline, and the reason a task was accepted or paused', cadence:'at the start of each shift and after a recurring request changes' ,
  published: '2026-08-18' },
 { slug:'offshore-customer-support-macro-governance', title:'Offshore Customer Support Macros: Govern Shortcuts Without Hiding Judgment', focus:'customer support response macros', question:'which parts of a customer reply can be standardized without turning a shortcut into an unauthorized promise', decision:'when an approved macro fits, when it needs a verified variable, and when a human owner must review it', failure:'agents sending polished language that is factually stale or broader than the policy allows', test:'old, revised, escalated, and missing-context cases across the main support channels', boundary:'the Filipino support operator may use approved wording but cannot publish a new policy or exception', records:'macro version, source policy, inserted facts, reviewer, customer outcome, and escalation reason', cadence:'whenever a policy changes and during a small weekly sample' ,
  published: '2026-08-18' },
 { slug:'philippines-admin-support-purchase-order-checks', title:'Philippines Admin Support Purchase Orders: Check the Packet Before Approval', focus:'purchase-order administration', question:'whether an order packet is complete enough for an authorized person to decide', decision:'what the administrator verifies and what remains a budget or commercial approval', failure:'a neatly assembled request being mistaken for a purchase decision', test:'new suppliers, amendments, recurring orders, missing tax fields, and conflicting totals', boundary:'the operator prepares and reconciles evidence but does not approve spend or change commercial terms', records:'requester, supplier, line items, supporting document, budget owner, discrepancy, and approval state', cadence:'before every approval handoff and at month-end for recurring patterns' ,
  published: '2026-08-18' },
 { slug:'offshore-reporting-qa-late-data-treatment', title:'Offshore Reporting QA: Decide How Late Data Enters the Period', focus:'late-arriving reporting data', question:'whether a late record belongs in the current period, a restatement, or an exception log', decision:'the approved treatment for timing, source correction, and definition changes', failure:'quietly moving rows until a dashboard looks consistent', test:'normal close, late file, corrected file, duplicate event, and changed cutoff cases', boundary:'the reporting operator applies the approved treatment but does not redefine the period', records:'arrival time, source period, treatment, denominator impact, reviewer, and restatement owner', cadence:'at every close and when a source misses its handoff' ,
  published: '2026-08-18' },
 { slug:'philippines-customer-support-reopened-case-analysis', title:'Philippines Customer Support Reopened Cases: Find the Broken Handoff', focus:'reopened customer support cases', question:'why a case marked complete returned and what information was missing at closure', decision:'whether the cause was source quality, wording, ownership, system state, or an unmet customer need', failure:'treating reopenings as individual carelessness without repairing the workflow', test:'routine cases, escalations, transfers, and cases reopened after a promised follow-up', boundary:'the agent documents the reason and next action while the client owner decides policy or service changes', records:'original request, closure evidence, reopening trigger, prior promise, new owner, and corrective action', cadence:'weekly, with a separate review after a material escalation' ,
  published: '2026-08-18' },
 { slug:'offshore-operations-support-exception-taxonomy', title:'Offshore Operations Support Exceptions: Build Categories That Lead to Action', focus:'operations exception taxonomy', question:'which kind of exception occurred and which owner can remove its cause', decision:'whether an item is a missing input, rule gap, system defect, dependency, or authorized override', failure:'keeping every unusual case in one vague bucket called “issue”', test:'a month of exceptions coded independently by two reviewers', boundary:'the operator classifies evidence under an approved taxonomy but does not waive a control', records:'exception type, trigger, affected step, evidence, temporary handling, owner, and due date', cadence:'during weekly operations review and after a new exception pattern appears' ,
  published: '2026-08-18' },
 { slug:'philippines-admin-support-renewal-calendar-control', title:'Philippines Admin Support Renewal Calendars: Separate Notice From Commitment', focus:'contract and subscription renewal calendars', question:'how to surface an approaching renewal without implying that the business has decided to continue', decision:'which dates trigger preparation, review, notice, and an authorized commitment', failure:'an administrative reminder being read as an instruction to renew', test:'auto-renewal, notice windows, changed owners, and records with conflicting dates', boundary:'the operator maintains dates and prepares options; the business owner accepts, cancels, or renegotiates', records:'agreement identity, effective date, notice deadline, owner, source, action state, and approval', cadence:'on a fixed review rhythm plus threshold reminders before notice dates' ,
  published: '2026-08-18' },
 { slug:'offshore-customer-support-channel-routing', title:'Offshore Customer Support Channel Routing: Match the Case to the Safest Path', focus:'multichannel customer support routing', question:'which channel and queue can handle a case without losing identity, context, or urgency', decision:'whether a request stays in chat, moves to a protected case, or needs a named specialist', failure:'sending a customer between channels while the important context disappears', test:'attachments, account recovery, accessibility needs, urgent risk, and duplicate contacts', boundary:'the agent routes and summarizes the case but does not relax verification or risk controls', records:'channel, verified context, transfer reason, customer expectation, receiving owner, and next checkpoint', cadence:'at launch, after channel changes, and in recurring transfer samples' ,
  published: '2026-08-18' },
 { slug:'philippines-reporting-qa-reconciliation-ownership', title:'Philippines Reporting QA Reconciliation: Assign the Difference Before the Deadline', focus:'reconciliation ownership', question:'who must explain a difference when two approved reporting sources disagree', decision:'whether the issue belongs to source operations, metric definition, calculation, or business ownership', failure:'asking the preparer to make an unsupported adjustment simply to meet a reporting deadline', test:'unmatched totals, duplicate rows, period shifts, and intentional exclusions', boundary:'the QA operator preserves the discrepancy and routes it; the metric owner decides the accepted meaning', records:'both source values, comparison rule, variance, evidence, owner, disposition, and deadline', cadence:'at each reporting cycle and after a recurring variance crosses its agreed threshold' ,
  published: '2026-08-18' },
 { slug:'offshore-admin-support-shared-inbox-delegation', title:'Offshore Admin Support Shared Inboxes: Delegate Without Losing Accountability', focus:'shared inbox delegation', question:'how a shared inbox can distribute work while keeping one accountable owner for every thread', decision:'which messages are routine, which need approval, and which must remain with the business owner', failure:'multiple people replying or nobody knowing who promised the next action', test:'new requests, replies to closed threads, copied managers, and messages with attachments', boundary:'the operator labels, drafts, and routes messages but does not make an unapproved commitment', records:'thread owner, state, deadline, draft status, approval need, attachment location, and close evidence', cadence:'at handoff times and in a daily review of active threads' ,
  published: '2026-08-18' },
 { slug:'philippines-operations-support-capacity-signals', title:'Philippines Operations Support Capacity: Read Queue Signals Before Adding Coverage', focus:'operations capacity signals', question:'whether a queue needs more coverage, a clearer rule, or a lower source of avoidable demand', decision:'how backlog, arrival rate, blocked time, rework, and deadline exposure should be interpreted together', failure:'treating every backlog increase as a staffing problem', test:'a period with a volume spike, a dependency outage, and an instruction change', boundary:'the operator reports evidence and patterns; the manager decides coverage, scope, or process investment', records:'arrival, completion, blocked reason, rework, due-date risk, and the assumption behind any conclusion', cadence:'weekly, with an immediate review when deadline risk becomes visible' ,
  published: '2026-08-18' },
 { slug:'offshore-customer-support-knowledge-gap-routing', title:'Offshore Customer Support Knowledge Gaps: Route Unanswered Questions Safely', focus:'customer support knowledge-gap routing', question:'what an agent should do when approved sources do not answer the customer’s actual question', decision:'whether to clarify, pause, escalate, or publish a reviewed knowledge update', failure:'filling an evidence gap with confident improvisation', test:'contradictory articles, new product behavior, edge-case accounts, and incomplete records', boundary:'the agent explains what is known and routes the gap; the policy owner approves new guidance', records:'question, sources checked, contradiction, safe interim wording, owner, and update decision', cadence:'same-day for material cases and weekly for recurring unanswered themes' ,
  published: '2026-08-18' },
 { slug:'philippines-admin-support-file-naming-retrieval', title:'Philippines Admin Support File Naming: Design Retrieval Around the Work', focus:'administrative file naming and retrieval', question:'whether another authorized teammate can find the right document without guessing from a filename', decision:'which identifiers, dates, versions, and access labels are required for retrieval', failure:'a tidy folder containing duplicates, superseded files, or names that hide the effective version', test:'duplicate uploads, amended documents, missing dates, and a handoff to a new reviewer', boundary:'the operator applies the naming rule and flags ambiguity but does not alter a document’s legal or business meaning', records:'document type, owner, effective date, version, access class, location, and supersession link', cadence:'at filing and during a monthly retrieval sample' ,
 published: '2026-08-18' },
 { slug:'offshore-reporting-qa-denominator-control', title:'Offshore Reporting QA Denominators: Prove What the Percentage Actually Measures', focus:'reporting denominator control', question:'whether a percentage describes the intended population rather than a convenient subset', decision:'which events belong in the denominator and how exclusions, duplicates, and late records are handled', failure:'presenting a precise rate whose population nobody can reproduce', test:'included, excluded, duplicate, null, and late records against a metric card', boundary:'the analyst checks and documents the denominator; the metric owner resolves meaning disputes', records:'population rule, source fields, exclusions, sample evidence, calculation, reviewer, and limitation', cadence:'when a metric is introduced, then at every material definition change', published:'2026-08-18' },
 { slug:'philippines-customer-support-callback-promises', title:'Philippines Customer Support Callbacks: Track the Promise Without Overpromising', focus:'customer support callback control', question:'how to record a callback request so the customer expectation and business authority remain aligned', decision:'who may schedule, what timeframe is supported, and when the request must escalate', failure:'an agent offering a precise callback time that the responsible team never accepted', test:'urgent requests, time-zone differences, missed callbacks, and requests outside the approved lane', boundary:'the support operator records and coordinates an approved callback but cannot guarantee another team’s action', records:'request time, timezone, reason, promised window, owner, confirmation, and missed-checkpoint action', cadence:'at every callback handoff and in a daily missed-promise review', published:'2026-08-18' },
 { slug:'offshore-operations-support-vendor-evidence', title:'Offshore Operations Vendor Follow-Up: Ask for Evidence, Not Another Status', focus:'vendor follow-up evidence', question:'what proof shows that a vendor dependency actually cleared', decision:'which artifact, acceptance condition, and owner confirm completion', failure:'repeating “in progress” updates while downstream work waits on an unverified assumption', test:'on-time delivery, partial delivery, changed scope, and a missed checkpoint', boundary:'the operator requests and records evidence; the client owner accepts delivery or changes the relationship', records:'commitment, due date, evidence requested, dependency, checkpoint, received artifact, and acceptance owner', cadence:'at each checkpoint and immediately after a missed commitment', published:'2026-08-18' },
 { slug:'philippines-admin-support-approval-packet-audit', title:'Philippines Admin Support Approval Packets: Make Review Fast Without Making It Automatic', focus:'approval packet preparation', question:'whether a reviewer can understand the request, evidence, gaps, and decision required at a glance', decision:'what the administrator may assemble and what the approver must explicitly decide', failure:'a complete-looking packet creating pressure to approve without reading its assumptions', test:'ordinary, exception, incomplete, and conflicting-evidence packets', boundary:'the operator improves inspectability but never signs for the approver or resolves an authority gap', records:'request, evidence index, assumptions, missing items, recommendation status, approver, and decision', cadence:'before submission and in a periodic sample of completed packets', published:'2026-08-18' },
 { slug:'offshore-customer-support-escalation-context', title:'Offshore Customer Support Escalations: Carry the Context the Next Owner Needs', focus:'customer support escalation context', question:'what the receiving owner must know to act without forcing the customer or agent to repeat the case', decision:'which facts, checks, promises, and open questions belong in the escalation', failure:'forwarding a ticket with urgency but no evidence or specific decision request', test:'technical defects, policy exceptions, account risk, and cases transferred across shifts', boundary:'the agent summarizes and routes the case; the receiving owner decides the exception or remedy', records:'customer goal, facts checked, source links, impact, promise status, exact decision requested, and next contact', cadence:'at every escalation and during a weekly review of returned escalations', published:'2026-08-18' },
 { slug:'philippines-reporting-qa-source-change-log', title:'Philippines Reporting QA Source Changes: Explain Why Yesterday’s Number Moved', focus:'reporting source change logs', question:'how a changed source or transformation affects a previously reported number', decision:'whether the change needs a restatement, a note, a new definition, or no action', failure:'replacing a number without preserving the reason, scope, or reviewer', test:'schema changes, corrected source records, transformation edits, and backfilled history', boundary:'the QA operator identifies and documents impact; the reporting owner approves the communication and treatment', records:'old and new source, change date, affected periods, impact estimate, evidence, approval, and notice', cadence:'whenever a source changes and during close review', published:'2026-08-18' },
 { slug:'offshore-admin-support-calendar-dependency-map', title:'Offshore Admin Support Calendars: Map Dependencies Before Scheduling the Work', focus:'administrative calendar dependencies', question:'which people, documents, approvals, and time zones must align for a scheduled event to succeed', decision:'what can be moved, what is fixed, and who owns a conflict', failure:'filling an open slot while leaving preparation, approval, or handoff work impossible', test:'reschedules, absent approvers, cross-time-zone attendees, and short-notice changes', boundary:'the operator coordinates the calendar but does not change the meeting’s decision owner or business purpose', records:'outcome, attendees, preparation, timezone, dependency, fallback, approval, and final confirmation', cadence:'when scheduling and after every material reschedule', published:'2026-08-18' },
 { slug:'philippines-operations-support-work-in-progress-limits', title:'Philippines Operations Support WIP Limits: Protect Reviewable Work', focus:'work-in-progress limits', question:'how much simultaneous work a support lane can carry without losing quality or ownership', decision:'what may enter the lane, what waits, and who can authorize an exception', failure:'starting more tasks to look busy while blocked and unfinished work accumulates', test:'normal volume, urgent insertion, absent reviewer, and a dependency outage', boundary:'the operator follows the agreed limit and surfaces risk; the manager changes capacity or priority', records:'active items, state, blocker, reviewer load, exception reason, and next admission point', cadence:'at shift planning and whenever the blocked lane grows', published:'2026-08-18' },
 { slug:'offshore-customer-support-sensitive-data-redaction', title:'Offshore Customer Support Redaction: Keep Case Context Without Repeating Sensitive Data', focus:'customer support sensitive-data redaction', question:'how to preserve enough context for a support handoff while limiting unnecessary exposure', decision:'which fields the receiving role needs, which should be masked, and which require a protected route', failure:'copying an entire customer record into tickets, chat, or screenshots', test:'identity details, payment references, attachments, exports, and cross-team transfers', boundary:'the operator uses the approved redaction path and escalates uncertainty; the data owner defines access and retention', records:'purpose, minimum fields, redaction check, protected location, recipient, retention step, and exception owner', cadence:'before every transfer involving sensitive fields and in periodic samples', published:'2026-08-18' },
];
const frames = [
 'Treat the first pass as a triage conversation written into the queue: identify the requested outcome, name the evidence already present, and make the next unanswered question impossible to miss.',
 'Use the handoff as the unit of design. A useful handoff lets a second person reconstruct what happened, why the item is waiting, and what authority is needed without reopening every message.',
 'Read the workflow as a set of competing clocks: customer expectation, reporting period, approval window, service level, and the time required to verify a source. The safest path makes those clocks visible.',
 'Separate the work record into facts, interpretation, and action. Facts can be checked; interpretation can be challenged; action can be assigned. Blending them makes a polished note look more certain than the evidence allows.',
 'Design the review around failure recovery rather than ideal throughput. Ask how the lane behaves when the input is late, the owner is absent, the instruction changes, or two records disagree.',
 'Start with the smallest durable artifact that would help a new reviewer make the next safe move. Add fields only when a real exception proves that the existing record cannot explain the decision.',
 'A good queue is a map of ownership, not merely a list of tasks. Every waiting state should say who can unblock it, what proof is required, and when the item should be reconsidered.',
 'Make time-zone and shift boundaries explicit. The person closing a task may not be the person who promised the next step, so the record must carry the promise, its owner, and the checkpoint.',
 'Test the rule against an item that looks routine but contains one consequential ambiguity. This reveals whether the workflow rewards careful pausing or quietly rewards confident guessing.',
 'Keep the operator’s preparation work separate from the principal’s decision. Better evidence shortens review; it does not transfer budget, policy, risk, or customer authority to the support lane.',
 'Use a disagreement as useful evidence. When two reviewers classify the same item differently, preserve both readings, identify the missing rule, and route the definition question to its owner.',
 'The practical benchmark is recoverability: can another authorized person understand the state, reproduce the check, and continue the work after an interruption? If not, speed has hidden a continuity cost.',
 'Avoid measuring a queue only by completed items. Count returns, blocked time, duplicate handling, missing approvals, and corrections because these show whether the process is producing usable work.',
 'When a source changes, preserve the before-and-after story. A later reviewer needs the old value, new value, effective point, affected records, and approval trail—not just the corrected output.',
 'A calendar, inbox, or folder becomes operational infrastructure when other work depends on it. Its owner should be able to see dependencies, conflicts, and fallback choices before they become urgent.',
 'Make sensitive information earn its place in the record. State the purpose, carry the minimum useful context, and point to the protected source rather than copying a complete record into a wider lane.',
 'A recurring exception deserves a named category only when the category changes the next action. Otherwise taxonomy becomes decoration and operators spend time choosing labels that do not help an owner respond.',
 'Give reviewers a decision-shaped packet. Put the question first, evidence second, gaps third, and authority last. This makes an approval faster to inspect while preserving the fact that approval remains a human act.',
 'Treat a promise as a controlled data point. Record who made it, what was actually authorized, when it should be checked, and what happens if the checkpoint passes without proof.',
 'Use examples from the lane’s real edges: amendments, duplicates, transfers, missing context, urgent requests, and changed definitions. These are more instructive than a generic idealized workflow.',
 'Capacity is a diagnosis, not a number. Compare arrivals, completions, rework, blocked time, review load, and deadline exposure before concluding that additional coverage is the answer.',
 'Close the loop with a small review sample and a specific owner. The purpose is not to create a ceremony; it is to discover whether the written rule still matches the work people actually receive.'
];
const expand = (t: Topic, angle: string, detail: string, index: number) => `${t.title} addresses ${t.focus} in a Philippines-based offshore support setting. The operating question is ${t.question}. That question should be written before anyone chooses a tool, assigns a queue, or asks an operator to move faster. ${frames[index]} ${angle} ${detail}

Start with an observable record. It should show ${t.records}, distinguish a verified fact from an assumption, and identify the next owner when work cannot proceed. Do not hide uncertainty in a polished status word. ${t.failure} is a warning that the workflow has confused preparation with authority or completion with acceptance. A well-designed lane can collect evidence, reconcile fields, draft a response, preserve a customer expectation, or surface a conflict. It cannot invent a missing policy, waive a control, approve spend, change a metric definition, or promise another team’s action. ${t.boundary}

The test should include ${t.test}. Review one ordinary case, one ambiguous case, one late or conflicting case, and one case that crosses a shift or time zone. For each, ask what the operator could know, what the record proves, where the work pauses, and who is empowered to continue it. This produces a practical boundary rather than a vague instruction to use judgment. ${t.cadence} creates a feedback loop: inspect returns, blocked items, duplicate effort, and unexplained changes, then give the owner a concrete correction to approve. The goal is reviewable work with clear responsibility, not the appearance of certainty. A useful review also asks whether the source was current, whether the requested outcome was specific, whether a queue state matched reality, and whether a receiving owner could act without reopening discovery. Keep examples concrete: a request with a missing attachment, a customer whose expectation needs careful wording, a report whose population has changed, an administrative packet that still needs approval, or a dependency described only as in progress. In each example, preserve the original fact, record the uncertainty, state the safe next action, and name the person who can resolve the decision. Do not use completion language to conceal waiting. Do not use urgency language to bypass an approval. Do not copy sensitive material into a convenience note merely because the approved record is slower to access. The routine is successful when another authorized person can audit the reasoning, understand the boundary, and continue the work without guessing.`;
export const august18BlogPosts = topics.map(t => ({ slug:t.slug, title:t.title, excerpt:`A practical guide to ${t.focus} for Philippines-based offshore operations, with clear evidence, review points, and decision boundaries.`, minutes:12, published:t.published, image, citations:['https://www.nist.gov/privacy-framework'] }));
export const august18BlogDetails = Object.fromEntries(topics.map((t, index) => [t.slug, { keyTakeaways:[`Define ${t.question}.`,`Separate preparation from the authorized ${t.decision}.`,`Use ${t.test} to review the workflow.`], sections:[
 {title:'Name the operating question',body:expand(t,`Write the question in language a reviewer can answer from the record. Start with the decision the work supports and the evidence that makes the next step safe.`,`${t.decision} should be stated before volume, speed, or coverage is discussed.`, index)},
 {title:'Build the path around evidence',body:expand(t,`Make the next action visible. A useful state says whether the item is ready, waiting for a named owner, returned for clarification, or complete with evidence attached.`,`${t.failure} is a design signal: inspect the missing field, unclear owner, or misleading status before blaming the person who encountered it.`, index)},
 {title:'Exercise the boundary cases',body:expand(t,`A clean example proves only that the happy path is easy. Deliberately include an exception and ask whether the operator knows when to pause.`,`${t.test} should be reviewed by someone who can explain why the selected path was permitted and what would have required escalation.`, index)},
 {title:'Keep authority with the owner',body:expand(t,`Detailed preparation and explicit authority let offshore support move repeatable work forward without silent substitutions.`,`${t.boundary}. The boundary protects the operator from being held responsible for a decision the business never assigned.`, index)},
 {title:'Review the loop and improve it',body:expand(t,`Compare the written rule with a small set of real records. Look for rework, unexplained waiting, reopened items, duplicate effort, and decisions made outside the approved record.`,`${t.records} makes the review concrete; assign an owner and a date for checking whether a correction helped.`, index)},
 ], internalLinks:[{label:'Review operations support',href:'/services/operations-support',note:'Define the queue, reviewer, and approval boundary.'},{label:'Review customer support',href:'/services/customer-support',note:'Keep customer promises and exceptions with the right owner.'}], sources:[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Reference for organizing privacy risk and safeguards.'}] }])) as Record<string, any>;
