const thumbnail = '/philippines-team.jpg';

const records = [
  ['philippines-inbox-triage', 'Philippines Inbox Triage: Turn Mixed Requests Into Clear Queues', 'inbox triage', 'classify the request, urgency, customer context, and next owner', 'the original message, category, promised response, and escalation reason', 'a guessed answer is sent before the responsible owner reviews it', '2026-08-14'],
  ['offshore-vendor-follow-up', 'Offshore Vendor Follow-Up: Keep Commitments Visible Without Chasing Noise', 'vendor follow-up', 'track the agreed action, evidence requested, and checkpoint date', 'the vendor promise, source thread, open dependency, and accountable owner', 'a polite update is mistaken for confirmation that the work is complete', '2026-08-14'],
  ['philippines-calendar-coordination', 'Philippines Calendar Coordination: Protect Focus Time and Decision Context', 'calendar coordination', 'offer approved times while preserving meeting purpose and attendee context', 'the requested outcome, time-zone assumption, attendees, and unresolved choice', 'a meeting is moved without carrying the decision or preparation needed', '2026-08-14'],
  ['offshore-data-entry-controls', 'Offshore Data Entry Controls: Make Repetitive Updates Easy to Audit', 'data entry controls', 'enter approved values and flag ambiguity before changing the source record', 'the source document, field changed, operator, and exception note', 'a plausible value is entered when the source is incomplete or conflicting', '2026-08-14'],
  ['philippines-customer-feedback-coding', 'Philippines Customer Feedback Coding: Preserve Meaning Behind the Label', 'customer feedback coding', 'apply a defined theme while retaining the customer wording and context', 'the source comment, selected theme, confidence note, and review sample', 'a single label hides a product defect or a request needing escalation', '2026-08-14'],
  ['offshore-document-indexing', 'Offshore Document Indexing: Find the Record Without Rewriting It', 'document indexing', 'name and classify files using approved metadata and version rules', 'the file identifier, document date, version, access class, and exception', 'an indexer silently replaces an unclear title or deletes a duplicate', '2026-08-14'],
  ['philippines-lead-research-briefs', 'Philippines Lead Research Briefs: Separate Public Facts From Assumptions', 'lead research briefs', 'collect public business facts that match a defined prospect question', 'the source URL, observed fact, date checked, and confidence boundary', 'an inferred need or unverified contact detail is presented as fact', '2026-08-14'],
  ['offshore-order-status-support', 'Offshore Order Status Support: Explain Events Without Inventing Promises', 'order status support', 'match the customer question to the latest approved order event', 'the order milestone, source system, customer wording, and next checkpoint', 'a carrier estimate becomes a guaranteed delivery statement', '2026-08-14'],
  ['philippines-expense-receipt-review', 'Philippines Expense Receipt Review: Surface Missing Context Before Approval', 'expense receipt review', 'match a receipt to the stated business purpose and required fields', 'the receipt, expense line, missing evidence, and approving owner', 'administrative completeness is treated as approval of the expense', '2026-08-14'],
  ['offshore-knowledge-base-maintenance', 'Offshore Knowledge Base Maintenance: Keep Help Articles Tied to Owners', 'knowledge base maintenance', 'compare an article with its approved source and flag stale instructions', 'the source owner, last review, changed step, and unresolved question', 'a writer updates a policy-sensitive instruction without authorization', '2026-08-14'],
  ['philippines-returns-coordination', 'Philippines Returns Coordination: Route the Case With the Right Evidence', 'returns coordination', 'collect order, item, timing, and requested outcome before routing the case', 'the order event, return reason, evidence, policy path, and decision owner', 'a support note promises an exception that only the merchant can approve', '2026-08-14'],
  ['offshore-recruiting-sourcing-support', 'Offshore Recruiting Sourcing Support: Keep Candidate Research Consistent', 'recruiting sourcing support', 'find candidates against approved criteria and record the source context', 'the criterion, public profile source, screening boundary, and recruiter owner', 'a coordinator makes a suitability judgment or records sensitive speculation', '2026-08-14'],
  ['philippines-invoice-coding', 'Philippines Invoice Coding: Improve Handoffs Between Intake and Review', 'invoice coding', 'map invoice details to approved coding options and flag uncertainty', 'the invoice field, coding rule, evidence, variance, and reviewer', 'a missing purchase-order detail is filled in from a guess', '2026-08-14'],
  ['offshore-property-guest-support', 'Offshore Property Guest Support: Coordinate Requests With Clear Safety Limits', 'property guest support', 'record the guest request, access constraint, urgency, and service owner', 'the guest message, property detail, vendor status, and close check', 'a safety or maintenance decision is made without the responsible property owner', '2026-08-14'],
  ['philippines-marketplace-catalog-review', 'Philippines Marketplace Catalog Review: Keep Product Facts Source-Based', 'marketplace catalog review', 'compare listing fields with approved product information before routing edits', 'the source field, proposed correction, image or document reference, and approver', 'an unsupported claim or specification is added to improve a listing', '2026-08-14'],
  ['offshore-hr-file-administration', 'Offshore HR File Administration: Route Records Without Expanding Access', 'HR file administration', 'check approved personnel documents for completeness and correct placement', 'the document type, employee identifier, retention path, and exception owner', 'private information is copied into an unnecessary working file', '2026-08-14'],
  ['philippines-logistics-exception-desk', 'Philippines Logistics Exception Desks: Give Delays a Fact-Based Next Step', 'logistics exception handling', 'pair the operational event with its impact, dependency, and next checkpoint', 'the milestone, exception code, affected order, and accountable owner', 'a temporary estimate is communicated as a fixed recovery commitment', '2026-08-14'],
  ['offshore-event-registration-support', 'Offshore Event Registration Support: Keep Attendee Changes Reviewable', 'event registration support', 'update approved registration details while routing special requests', 'the attendee request, consent or preference, changed field, and event owner', 'an attendee preference or access need is shared more broadly than needed', '2026-08-14'],
  ['philippines-legal-intake-administration', 'Philippines Legal Intake Administration: Organize Facts Before Counsel Review', 'legal intake administration', 'capture matter facts and supporting documents without offering legal conclusions', 'the request, jurisdiction clue, source file, missing fact, and counsel owner', 'an administrative summary is framed as legal advice or a case decision', '2026-08-14'],
  ['offshore-survey-response-coding', 'Offshore Survey Response Coding: Make Themes Reproducible', 'survey response coding', 'apply an agreed codebook and retain a path back to the original response', 'the response ID, code, rationale, codebook version, and reviewer sample', 'an ambiguous answer is forced into a precise category', '2026-08-14'],
  ['philippines-membership-record-support', 'Philippines Membership Record Support: Handle Changes With a Visible Trail', 'membership record support', 'match a member request to the approved account action and evidence', 'the request, account state, authorization, changed field, and result', 'a support update changes eligibility or benefits without the named owner', '2026-08-14'],
  ['offshore-purchase-request-routing', 'Offshore Purchase Request Routing: Make the Approval Path Obvious', 'purchase request routing', 'check request details and send the packet to the right purchasing owner', 'the requested item, business reason, supplier context, evidence, and approver', 'routing a request is mistaken for permission to place the order', '2026-08-14'],
] as const;

export const august14BlogPosts = records.map(([slug, title, focus, , , , published]) => ({
  slug, title,
  excerpt: `A practical guide to ${focus} for leaders defining a Philippines-based support role with clear evidence, ownership, and approval boundaries.`,
  minutes: 9,
  published,
  image: thumbnail,
  citations: ['https://www.nist.gov/privacy-framework', 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm'],
}));

export const august14BlogDetails = Object.fromEntries(records.map(([slug, title, focus, first, proof, risk]) => [slug, {
  keyTakeaways: [`Define the input and finish line for ${focus}.`, `Keep ${first} inside a written approval boundary.`, `Review ${proof} rather than relying on activity totals.`],
  sections: [
    { title: 'Define the queue before assigning it', body: `${title} becomes useful when the request, source, required fields, expected output, and accepting owner are explicit. For ${focus}, write examples of an ordinary case, an incomplete case, and a case that must pause. That gives a Philippines-based support role a consistent starting point.` },
    { title: 'Separate preparation from authority', body: `A support role may gather facts, update an approved record, and route the next action. It should not make the decision reserved for the client, licensed specialist, manager, or accountable owner. In this lane, ${first}. Put the boundary beside the task and include the escalation destination.` },
    { title: 'Keep evidence with the work', body: `A reviewable record contains ${proof}. Link the source, identify the person who owns the decision, and record why an exception was routed. A private message can alert a manager, but it should not be the only place where a business-critical fact survives.` },
    { title: 'Test normal cases and exceptions', body: `Review a normal case and a difficult case together. Check factual accuracy, completeness, timeliness, and whether the next owner can act without repeating the investigation. Watch for the failure where ${risk}; capture the missing source field or rule that allowed it.` },
    { title: 'Improve the rule from evidence', body: `After a review, change one instruction, example, field, or escalation rule and assign an owner for the revision. Keep a short record of what changed and why. Expand the role only when it can produce consistent, reviewable outcomes for ${focus} without turning uncertainty into a silent guess.` },
  ],
  internalLinks: [{ label: 'Review operations support', href: '/services/operations-support', note: 'Build the role around a visible queue and named reviewer.' }, { label: 'Read the handoff workflow guide', href: '/blog/offshore-team-handoff-workflow', note: 'Keep status and ownership with the work.' }],
  relatedArticles: ['offshore-team-handoff-workflow', 'offshore-outsourcing-access-control', 'outsourcing-operations-reporting'],
  banners: [{ label: 'Role planning checkpoint', title: 'Turn the guide into a role brief', body: 'List the work, tools, reviewer, and approval limits before launch.', href: '/contact-us', linkText: 'Plan the role' }, { label: 'Next step', title: 'Start with a controlled queue', body: 'Use a small sample a manager can inspect before increasing volume.', href: '/contact-us', linkText: 'Scope the workflow' }, { label: 'Ready to scope?', title: 'Make the handoff visible', body: 'Keep decisions and open risks with the approved record.', href: '/contact-us', linkText: 'Discuss the workflow' }],
  sources: [{ name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Reference for identifying privacy risk and selecting safeguards.' }, { name: 'International Labour Organization guidance', url: 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm', note: 'Reference for clear expectations and accountable work arrangements.' }],
}])) as Record<string, any>;
