const thumbnail = '/philippines-team.jpg';

const records = [
  ['offshore-bookkeeping-close-checklist', 'Offshore Bookkeeping Close Checklists: Give Reviewers a Complete Packet', 'bookkeeping close checklists', 'organize account-period evidence before a bookkeeper reviews the close', 'the account list, source status, open question, and reviewer', 'a missing document is treated as a finished close', '2026-08-13'],
  ['philippines-customer-renewal-briefs', 'Philippines Customer Renewal Briefs: Prepare Facts Before the Conversation', 'customer renewal briefs', 'assemble account history and open requests without making the renewal decision', 'the renewal date, approved terms, customer question, and owner', 'a draft recommendation is presented as an accepted renewal', '2026-08-13'],
  ['offshore-insurance-claim-intake-review', 'Offshore Insurance Claim Intake: Check Evidence Before Examination', 'insurance claim intake', 'check claim packets for identifiers, attachments, and missing facts', 'the intake checklist, received evidence, exception reason, and examiner', 'an incomplete packet is labeled ready for a coverage decision', '2026-08-13'],
  ['philippines-property-listing-change-control', 'Philippines Property Listing Change Control: Keep Source Edits Traceable', 'property listing change control', 'compare requested listing edits with the approved source before routing them', 'the source field, proposed value, requestor, and approving owner', 'an unreviewed edit changes a material property detail', '2026-08-13'],
  ['offshore-helpdesk-symptom-capture', 'Offshore Helpdesk Symptom Capture: Improve the First Technical Handoff', 'helpdesk symptom capture', 'record the user symptom, environment, reproduction status, and urgency', 'the original report, known steps, impact, and assigned specialist', 'a triage note presents a guess as a technical fix', '2026-08-13'],
  ['philippines-clinic-appointment-coordination', 'Philippines Clinic Appointment Coordination: Keep Scheduling Separate From Care', 'clinic appointment coordination', 'offer approved appointment options and route clinical questions to the clinic', 'the scheduling request, consent path, selected slot, and clinic owner', 'an administrator interprets symptoms or shares unnecessary health details', '2026-08-13'],
  ['offshore-personnel-change-records', 'Offshore Personnel Change Records: Preserve the Reason for Every Update', 'personnel change records', 'match an approved personnel change to the correct employee record', 'the authorization, effective date, before-after values, and audit note', 'an old record is overwritten and the change reason disappears', '2026-08-13'],
  ['philippines-commerce-return-casework', 'Philippines Commerce Return Casework: Route Exceptions With the Order Facts', 'commerce return casework', 'match a customer return request to order facts and the approved rule', 'the order event, item condition, requested outcome, and next owner', 'a return exception is promised before the merchant decides', '2026-08-13'],
  ['offshore-supplier-file-completeness', 'Offshore Supplier File Completeness: Separate Collection From Activation', 'supplier file completeness', 'collect required supplier information and flag missing compliance fields', 'the submitted field, verification status, exception, and approving owner', 'collected information is treated as approval to activate a supplier', '2026-08-13'],
  ['philippines-property-repair-request-routing', 'Philippines Property Repair Request Routing: Turn Reports Into Safe Handoffs', 'property repair request routing', 'record location, access limits, urgency, and the requested repair outcome', 'the resident report, work order, vendor update, and close check', 'a safety concern is handled as ordinary maintenance', '2026-08-13'],
  ['offshore-crm-record-stewardship', 'Offshore CRM Record Stewardship: Improve Data Without Erasing Context', 'CRM record stewardship', 'identify duplicates and stale fields before proposing a CRM change', 'the original value, evidence, change reason, and sample review', 'a cleanup removes context that a seller needs for an active opportunity', '2026-08-13'],
  ['philippines-policy-service-request-routing', 'Philippines Policy Service Request Routing: Keep Facts Separate From Advice', 'policy service request routing', 'record the policyholder request and separate service facts from coverage questions', 'the policy identifier, requested change, evidence, and licensed owner', 'a service reply implies that coverage or a claim decision is settled', '2026-08-13'],
  ['offshore-contractor-invoice-packet-review', 'Offshore Contractor Invoice Packets: Check Support Before Payment Review', 'contractor invoice packet review', 'match invoice fields to the contract, purchase order, and receiving evidence', 'the invoice packet, variance note, disputed field, and payment approver', 'an administrative match is mistaken for authorization to pay', '2026-08-13'],
  ['philippines-interview-calendar-coordination', 'Philippines Interview Calendar Coordination: Protect Candidate Handoffs', 'interview calendar coordination', 'confirm availability, interview context, accommodations, and the right contact', 'the candidate preference, confirmed slot, accommodation note, and interviewer', 'private candidate information is copied into an unnecessary channel', '2026-08-13'],
  ['offshore-account-change-support', 'Offshore Account Change Support: Make Requests Easy to Review', 'account change support', 'classify the customer request and identify which account action is permitted', 'the customer request, account state, approval, and result', 'a support reply changes a plan or refund without authority', '2026-08-13'],
  ['philippines-shipment-delay-escalation', 'Philippines Shipment Delay Escalation: Give Every Exception a Next Owner', 'shipment delay escalation', 'pair the carrier event with the customer promise and operational owner', 'the shipment milestone, exception reason, next checkpoint, and owner', 'an estimate becomes a customer guarantee', '2026-08-13'],
  ['offshore-foundation-grant-file-review', 'Offshore Foundation Grant File Review: Tie Each Requirement to Evidence', 'foundation grant file review', 'map each requested grant field to its source document and reviewer', 'the requirement, source citation, submission status, and owner', 'a missing attachment is silently filled with an assumption', '2026-08-13'],
  ['philippines-digital-library-tagging', 'Philippines Digital Library Tagging: Keep Metadata Changes Reviewable', 'digital library tagging', 'apply approved naming and tagging rules while flagging unclear rights information', 'the asset version, metadata change, source, and approver', 'an assistant invents a rights statement or overwrites the master asset', '2026-08-13'],
  ['offshore-student-record-intake', 'Offshore Student Record Intake: Route Incomplete Files With Care', 'student record intake', 'check enrollment forms for completeness without deciding eligibility', 'the submitted record, missing field, privacy path, and registrar owner', 'a missing detail is interpreted as an admissions decision', '2026-08-13'],
  ['philippines-vehicle-service-desk', 'Philippines Vehicle Service Desks: Keep Fleet Issues Moving Safely', 'vehicle service desks', 'record the vehicle, operational impact, inspection facts, and dispatch authority', 'the service request, asset identifier, vendor update, and closure check', 'an unsafe vehicle is returned to service without the responsible decision', '2026-08-13'],
  ['offshore-research-participant-scheduling', 'Offshore Research Participant Scheduling: Protect the Study Record', 'research participant scheduling', 'schedule approved participants and preserve consent and study context', 'the recruitment source, consent status, interview slot, and researcher owner', 'a coordinator changes the screener or exposes participant identity', '2026-08-13'],
  ['philippines-invoice-mismatch-routing', 'Philippines Invoice Mismatch Routing: Surface Exceptions Before Approval', 'invoice mismatch routing', 'compare invoice, purchase order, and receipt facts before routing a mismatch', 'the match status, exception reason, evidence, and approver', 'a discrepancy is forced through because the queue is old', '2026-08-13'],
] as const;

export const august13BlogPosts = records.map(([slug, title, focus, , , , published]) => ({
  slug, title,
  excerpt: `A practical guide to ${focus} for leaders defining a Philippines-based support role with clear evidence, ownership, and approval boundaries.`,
  minutes: 9,
  published,
  image: thumbnail,
  citations: ['https://www.nist.gov/privacy-framework', 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm'],
}));

export const august13BlogDetails = Object.fromEntries(records.map(([slug, title, focus, first, proof, risk]) => [slug, {
  keyTakeaways: [`Define the input and finish line for ${focus}.`, `Keep ${first} within a written approval boundary.`, `Review ${proof} rather than relying on activity totals.`],
  sections: [
    { title: 'Name the request and its finished state', body: `${title} works best when the first request is concrete. Describe the source, required fields, expected output, due point, and person who accepts the work. For ${focus}, use two real examples and one deliberately incomplete example so the support role can recognize when to pause.` },
    { title: 'Separate preparation from authority', body: `A Philippines-based support role can gather facts, update an approved record, and route the next action. It should not make the decision reserved for the client, accountant, clinician, licensed specialist, registrar, or other accountable owner. In this lane, ${first}. Put that boundary beside the task rather than hiding it in general policy.` },
    { title: 'Keep a reviewable evidence trail', body: `The useful record contains ${proof}. Store the source and the decision in the approved system, use named accounts, and record why an exception was routed. A private message may alert a manager, but it should not be the only place where a business-critical decision survives.` },
    { title: 'Sample ordinary work and exceptions', body: `Review a normal case and a difficult case together. Check factual accuracy, completeness, timeliness, and whether the next owner can act without repeating the investigation. Watch for the failure where ${risk}; record the missing rule or source field that made it possible.` },
    { title: 'Improve one control at a time', body: `After a review, change one instruction, example, field, or escalation rule and assign an owner for the revision. Keep a short record of what changed and why. Expand the role only when it can produce consistent, reviewable outcomes for ${focus} without turning unclear decisions into silent guesses.` },
  ],
  internalLinks: [{ label: 'Review operations support', href: '/services/operations-support', note: 'Build the role around a visible queue and named reviewer.' }, { label: 'Read the handoff workflow guide', href: '/blog/offshore-team-handoff-workflow', note: 'Keep status and ownership with the work.' }],
  relatedArticles: ['offshore-team-handoff-workflow', 'offshore-outsourcing-access-control', 'outsourcing-operations-reporting'],
  banners: [{ label: 'Role planning checkpoint', title: 'Turn the guide into a role brief', body: 'List the work, tools, reviewer, and approval limits before launch.', href: '/contact-us', linkText: 'Plan the role' }, { label: 'Next step', title: 'Start with a controlled queue', body: 'Use a small sample a manager can inspect before increasing volume.', href: '/contact-us', linkText: 'Scope the workflow' }, { label: 'Ready to scope?', title: 'Make the handoff visible', body: 'Keep decisions and open risks with the approved record.', href: '/contact-us', linkText: 'Discuss the workflow' }],
  sources: [{ name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework', note: 'Reference for identifying privacy risk and selecting safeguards.' }, { name: 'International Labour Organization guidance', url: 'https://www.ilo.org/global/topics/non-standard-employment/WCMS_534825/lang--en/index.htm', note: 'Reference for clear expectations and accountable work arrangements.' }],
}])) as Record<string, any>;
