export const september9CampaignDate='2026-09-09' as const;
const image='/philippines-team.jpg';
const sources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'Philippine National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'}];
const blogs=[
['philippines-customer-identity-verification-desk','Philippines customer identity verification desk: a bounded operating guide','identity evidence and account references','recovery, disclosure, and suspected impersonation'],
['offshore-invoice-dispute-intake-lane','Offshore invoice dispute intake: build a decision-ready case','invoice lines, contracts, delivery evidence, and prior contact','credits, write-offs, tax, and settlement terms'],
['philippines-returns-warehouse-exception-board','Philippines returns exception boards: connect the parcel to the decision','order, carrier, warehouse, and item-condition records','eligibility overrides, fraud findings, and refunds'],
['offshore-credential-expiry-review-routine','Offshore credential expiry reviews: prevent silent access gaps','credential owners, roles, dependencies, expiry, and last use','privilege expansion, emergency bypass, and renewal approval'],
['philippines-content-localization-handoff','Philippines content localization handoffs: preserve meaning and approval','approved source copy, glossary, locale, and protected terms','legal meaning, pricing, regulated claims, and launch timing'],
['offshore-chargeback-evidence-assembly','Offshore chargeback evidence assembly: organize facts before submission','transaction, authorization, delivery, contact, and deadline records','dispute strategy, refunds, fraud conclusions, and disclosure'],
['philippines-facilities-maintenance-intake','Philippines facilities maintenance intake: triage without guessing severity','site, location, observed condition, impact, access, and photos','safety classification, shutdown, vendor choice, and spend'],
['offshore-legal-hold-administration-support','Offshore legal hold administration support: protect the instruction boundary','approved notices, custodians, systems, matter IDs, and acknowledgments','hold scope, privilege, preservation sufficiency, and release'],
['philippines-product-sample-fulfillment-queue','Philippines product sample fulfillment: control eligibility and inventory','requester, recipient, approved SKU, quantity, consent, and inventory','eligibility, pricing, substitutions, export rules, and claims'],
['offshore-training-attendance-reconciliation','Offshore training attendance reconciliation: distinguish presence from completion','rosters, session versions, attendance events, assessments, and roles','waivers, competency, discipline, and production access'],
['philippines-warranty-claim-document-check','Philippines warranty claim document checks: prepare the file, preserve the decision','product, serial, purchase proof, issue details, dates, and images','coverage, misuse findings, replacement, refund, and repair'],
['offshore-data-deletion-request-coordination','Offshore data deletion request coordination: trace the request safely','request, identity check, scope, systems, deadlines, and owners','legal applicability, exemptions, retention conflicts, and response language']
] as const;
export const september9BlogPosts=blogs.map(([slug,title,topic])=>({slug,title,excerpt:`A practical September 9 guide to ${topic} with explicit ownership and review.`,minutes:10,published:september9CampaignDate,image,citations:sources.map(s=>s.url)}));
export const september9BlogDetails=Object.fromEntries(blogs.map(([slug,title,topic,boundary])=>[slug,{keyTakeaways:[`Build the record from ${topic}.`,`Keep ${boundary} with a named client owner.`,'Reconcile the downstream result before closure.'],sections:[
{title:'Open one traceable record',body:`${title} begins with ${topic}. Preserve the original source, received time, and accountable owner in the approved system. Compare identifiers before joining records and label missing or conflicting evidence rather than guessing. The specialist prepares a reviewable case; the source remains authoritative.`},
{title:'Make the decision boundary visible',body:`${boundary} require an authorized client owner. Name that owner, a backup, the required evidence, and what may continue while a decision is pending. Urgency does not expand permission, and silence is not approval.`},
{title:'Limit access and exposure',body:'Use individual accounts, minimum necessary fields, and approved storage. Record source version, actor, action, approval, and time. NIST frameworks organize control questions; Philippine privacy law supplies local accountability context, but the client procedure defines the pass rule.'},
{title:'Verify the live outcome',body:`For ${title.toLowerCase()}, compare the authorized action with every downstream record, notice, and integration. Check partial saves, duplicates, stale messages, and later source changes. Leave unresolved items with an owner and review time.`},
{title:'Pilot and review',body:'Test an ordinary case, missing input, conflicting source, access failure, and consequential exception. Sample reopened work as well as completions. Findings apply only to the tested queue, systems, period, and rules; revise instructions where reviewers disagree.'}],internalLinks:[{label:'Plan an operations support role',href:'/services/operations-support',note:'Turn the queue into a bounded role brief.'},{label:'Review the research library',href:'/research',note:'Test assumptions with transparent methods.'}],banners:[{label:'Scope',title:'Name the decision owner',body:'Write stop conditions into the queue.',href:'/contact-us',linkText:'Scope the role'},{label:'Pilot',title:'Test awkward cases',body:'Include missing evidence and exceptions.',href:'/contact-us',linkText:'Plan the pilot'},{label:'Review',title:'Inspect the finish line',body:'Reconcile the live result.',href:'/contact-us',linkText:'Contact us'}],faqs:[{question:'What can the specialist decide?',answer:'Only routine actions explicitly allowed by the current role brief.'},{question:'What proves completion?',answer:'A source-linked record shows the permitted action, downstream result, owner, and open exceptions.'}],sources}])) as Record<string,any>;
const studies=[
['offshore-work-queue-interruption-cost-study','Offshore queue interruption cost: a workflow measurement study','restart burden after pauses','arrival, interruption, dependency, resume, handling, and outcome'],
['philippines-offshore-reviewer-agreement-analysis','Philippines offshore quality reviews: an agreement analysis','whether reviewers apply the same rule','policy, sample, classifications, reasons, disagreements, and adjudication'],
['offshore-handoff-information-loss-research','Offshore handoff information loss: a traceability review','which facts disappear across handoffs','source, handoff fields, promises, decisions, recipients, and final state'],
['philippines-offshore-permission-creep-study','Philippines offshore permission creep: a task-to-access study','whether current rights match actual work','tasks, roles, rights, usage logs, exceptions, owners, and review dates'],
['offshore-exception-recurrence-analysis','Offshore exception recurrence: separating repeat signals from repeated noise','repeat workflow exceptions without overstating cause','exceptions, task family, source, rule, system, decision, correction, and recurrence']
] as const;
export const september9ResearchPosts=studies.map(([slug,title,question,evidence])=>({slug,title,excerpt:`A transparent study of ${question}.`,published:september9CampaignDate,thumbnail:image,cluster:'Workflow Design' as const,stats:['Scope: one defined queue and review window','Observed records are separated from causal inference'],sections:[
{heading:'Question and scope',body:`This study asks ${question}. Define the queue, unit, roles, systems, policy version, and time window first. It evaluates a workflow, not the ability or character of Filipino professionals.`},
{heading:'Method',body:`Build a documented cohort containing routine cases and exceptions. Capture ${evidence}. Prefer attributable system records, minimize personal data, record exclusions, and have a second reviewer independently classify a subset.`},
{heading:'Analysis and inference limits',body:'Report counts and rates with numerator, denominator, window, exclusions, and missing-data volume. Sequence and association show where to investigate but do not prove cause. NIST frameworks provide control context; the client procedure supplies the operational pass condition.'},
{heading:'Decision use',body:'Propose one owned change—an intake field, source label, permission, routing rule, worked example, or review checkpoint—then retest under the same definitions. Consequential decisions remain with the authorized client owner.'},
{heading:'Limitations',body:'Results apply only to the sampled queue, period, systems, people, and rules. Small cohorts miss rare events; missing logs, later edits, selection choices, and reviewer knowledge can distort findings. This is not legal advice, an audit opinion, a productivity forecast, or evidence about the wider Philippines workforce.'}],sources}));
