export const september18CampaignDate = '2026-09-18' as const;

const image = '/philippines-team.jpg';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'A primary source for access, protection, detection, response, and recovery controls.' },
  { name: 'Philippine Data Privacy Act of 2012', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html', note: 'The official statutory text for Philippine personal-data responsibilities.' },
  { name: 'National Privacy Commission: Data Privacy Accountability and Compliance Framework', url: 'https://privacy.gov.ph/wp-content/uploads/2023/05/NPC-Circular-No.-2023-06-DPA-Compliance-and-Accountability-Framework.pdf', note: 'Official accountability guidance for organizations processing personal data.' },
] as const;

export type BlogCampaignTopic = {
  slug: string;
  title: string;
  excerpt: string;
  queue: string;
  evidence: string;
  checks: string;
  boundary: string;
  awkward: string;
  finish: string;
  service: 'operations-support' | 'customer-support' | 'admin-support' | 'reporting-and-qa';
};

const topics: readonly BlogCampaignTopic[] = [
  { slug:'philippines-customer-support-chargeback-evidence-packet', title:'Philippines customer support chargeback evidence packets: organize the facts without arguing the case', excerpt:'A practical workflow for assembling order, delivery, and customer-contact records while the client retains dispute strategy and submission authority.', queue:'new payment disputes that require a response by a stated deadline', evidence:'the processor notice, order record, payment reference, delivery proof, refund history, and customer conversation', checks:'match the account, amount, currency, transaction date, disputed reason, response deadline, and permitted evidence types', boundary:'The client decides the legal or commercial position, selects the evidence to submit, writes representations, and sends the response through the payment processor.', awkward:'a dispute that names one transaction while the customer conversation refers to a second order and a partial refund', finish:'the client-approved packet is attached to the correct processor case, the submission status is visible, and every excluded item has a reason' ,service:'customer-support'},
  { slug:'offshore-operations-subscription-renewal-notice-audit', title:'Offshore subscription renewal notice audit: prove the right message reached the right account', excerpt:'A record-by-record check of renewal notices, delivery results, account terms, and unresolved exceptions before a subscription renews.', queue:'upcoming subscription renewals with a required customer notice', evidence:'the current contract or plan record, renewal date, approved notice version, recipient, send event, and delivery result', checks:'confirm the account identifier, plan, renewal timing, recipient authority, template version, channel, and bounce or suppression state', boundary:'The client owns pricing, contract interpretation, cancellation decisions, notice requirements, and any promise that changes the customer agreement.', awkward:'a notice marked sent to an address that bounced after the account administrator left the customer organization', finish:'the approved recipient has a traceable delivery result or the case is open with a named client owner before the renewal deadline',service:'operations-support'},
  { slug:'philippines-ecommerce-return-reason-quality-review', title:'Philippines ecommerce return-reason QA: keep the code tied to what the customer said', excerpt:'A quality review for return classifications that preserves the customer record and avoids convenient guesses.', queue:'completed or pending returns whose reason codes feed product, refund, and warehouse reporting', evidence:'the customer request, order line, item received status, agent note, selected reason code, and current taxonomy', checks:'compare the customer wording with the code definition, distinguish one item from the whole order, and record ambiguity instead of inferring intent', boundary:'The client decides refund eligibility, suspected abuse, product defects, policy exceptions, and changes to the return taxonomy.', awkward:'a customer who lists poor fit and visible damage in the same message while returning two different items', finish:'each order line has a supported code or an explicit unresolved state, and downstream refund and inventory records agree with the authorized decision',service:'reporting-and-qa'},
  { slug:'offshore-admin-board-meeting-action-register', title:'Offshore board meeting action registers: capture ownership without rewriting the decision', excerpt:'A controlled way to turn approved minutes into a usable action register while preserving governance boundaries.', queue:'approved board or committee minutes that contain actions, requested follow-ups, and future decision points', evidence:'the approved minutes, action wording, named owner, due date, dependencies, status source, and later board-approved changes', checks:'quote or accurately paraphrase the approved action, separate an action from discussion, identify the accountable person, and link any dependency', boundary:'The board secretary or authorized governance owner approves minutes, interprets resolutions, changes owners or deadlines, and decides what may be disclosed.', awkward:'discussion that suggests a follow-up but the approved minutes do not record a motion, owner, or deadline', finish:'every registered action traces to approved minutes, owners can see their items, and disputed interpretations remain with the governance owner',service:'admin-support'},
  { slug:'philippines-logistics-proof-of-delivery-exception-queue', title:'Philippines proof-of-delivery exception queues: investigate the gap before closing the shipment', excerpt:'A practical exception lane for missing signatures, mismatched locations, unreadable images, and disputed delivery records.', queue:'shipments whose proof of delivery is missing, unreadable, inconsistent, or challenged', evidence:'the shipment identifier, carrier event history, delivery address, timestamp, recipient field, image or signature, and customer contact record', checks:'match the shipment and address, preserve carrier timestamps, inspect legibility, compare recipient details, and note any customer denial without changing it', boundary:'The client or carrier owner decides liability, refunds, replacement shipments, fraud findings, and customer compensation.', awkward:'a carrier image that shows a parcel at the wrong door while the scan location and written address appear to match', finish:'the evidence gap is resolved in the system of record or the exception has a named decision owner, next action, and customer-update deadline',service:'operations-support'},
  { slug:'offshore-customer-support-vulnerable-customer-handoff', title:'Offshore vulnerable-customer handoffs: respond safely without making a clinical judgment', excerpt:'A support handoff for signs of distress, accessibility needs, coercion, or financial vulnerability with clear emergency and privacy limits.', queue:"customer contacts that match the client's written vulnerability or immediate-safety triggers", evidence:"the customer's own words, contact channel, account context needed for the case, actions already taken, current location only when the approved procedure requires it, and available specialist route", checks:'use the exact trigger list, avoid diagnostic labels, confirm the permitted next step, limit repeated questioning, and keep sensitive details in the approved case field', boundary:'The client owns emergency policy, clinical or legal judgments, account restrictions, financial relief, disclosures, and contact with emergency services.', awkward:'a customer who hints at coercion, refuses a call, and asks that no message be sent to the contact details already on the account', finish:'the customer receives the safest approved response available, the correct specialist or emergency owner accepts the handoff, and the record contains only necessary facts',service:'customer-support'},
  { slug:'philippines-accounts-payable-duplicate-invoice-screen', title:'Philippines accounts payable duplicate-invoice screening: flag the match before money moves', excerpt:'A pre-payment control for likely duplicate invoices across file names, invoice numbers, entities, amounts, and dates.', queue:'supplier invoices received before approval or payment scheduling', evidence:'the source invoice, supplier master record, purchase order when used, invoice number, entity, amount, currency, tax fields, receipt time, and prior invoice history', checks:'normalize harmless formatting differences, compare supplier and entity, test exact and near invoice-number matches, inspect amounts and dates, and distinguish a credit note from a bill', boundary:'The client approves invoices, releases payments, interprets tax, changes supplier details, accepts duplicates, and investigates fraud.', awkward:'two invoices with the same amount and service period but different invoice numbers after a supplier changed billing systems', finish:"each likely match is linked and held for review, cleared invoices keep the reviewer's reason, and the payment queue reflects the authorized disposition",service:'reporting-and-qa'},
  { slug:'offshore-saas-user-access-request-intake', title:'Offshore SaaS access-request intake: make approval and scope visible before provisioning', excerpt:'A least-privilege intake process for new users, role changes, temporary access, and rejected requests.', queue:'requests to create, change, extend, or remove access to client software', evidence:'the named user, manager, business reason, requested system, role or permissions, start and end dates, device or location condition, and approval record', checks:"verify the requester through an approved channel, compare the role with the access catalog, identify conflicts, set expiry for temporary access, and confirm the approver's authority", boundary:'The client system owner approves access, accepts segregation-of-duty risk, chooses privileged roles, and authorizes exceptions.', awkward:'an urgent request from a senior employee for administrator access when the named approver is unavailable', finish:'the approved scope is provisioned to the named account and independently checked, or the unapproved request remains closed without access',service:'admin-support'},
  { slug:'philippines-customer-support-warranty-claim-intake', title:'Philippines warranty claim intake: collect usable evidence without promising coverage', excerpt:'A customer-support workflow for product, purchase, symptom, and evidence capture while the client retains warranty decisions.', queue:'customers asking for repair, replacement, credit, or another remedy under a stated warranty', evidence:'the product identifier, purchase record, claimant details needed by policy, reported symptom, event timeline, requested evidence, prior service, and contact preference', checks:'match the product and purchase, use the current policy version, request only relevant evidence, distinguish intake from diagnosis, and record safety triggers immediately', boundary:'The client decides coverage, technical cause, remedy, exceptions, recalls, legal duties, and any promise of repair, replacement, or refund.', awkward:'a product outside the recorded period that had an earlier repair and now presents a possible safety concern', finish:'the claim file is complete enough for the authorized reviewer or clearly lists the missing item, owner, and next customer update',service:'customer-support'},
  { slug:'offshore-operations-marketplace-listing-suppression-triage', title:'Offshore marketplace listing suppression triage: restore the evidence trail before editing', excerpt:'A disciplined first-response process for suppressed product listings, conflicting platform messages, and risky quick fixes.', queue:'marketplace listings that are hidden, restricted, rejected, or losing required attributes', evidence:'the listing identifier, marketplace notice, current product record, last approved content, change history, policy reference, inventory status, and account owner', checks:'preserve the original notice, identify the affected market and SKU, compare the live and approved record, locate the last change, and separate content errors from account or product restrictions', boundary:'The client decides policy interpretation, regulated claims, appeals, brand changes, product eligibility, and final edits to commercial content.', awkward:'a listing suppressed after an automated attribute update even though the visible copy did not change', finish:'the root evidence and proposed correction are with the right owner, approved edits are reflected on the live listing, and the suppression state is rechecked',service:'operations-support'},
  { slug:'philippines-reporting-dashboard-filter-regression-check', title:'Philippines dashboard filter regression checks: catch a quiet reporting break', excerpt:'A repeatable QA routine for filters, date windows, joins, permissions, exports, and totals after a dashboard change.', queue:'business dashboards after a release, data-model update, permission change, or reported discrepancy', evidence:'the dashboard version, data refresh time, defined test cases, source query or approved comparison report, user role, filters, expected result, and actual result', checks:'run fixed ordinary and edge cases, reset hidden filters, compare totals and row samples, test restricted roles, and record whether the defect is in data, logic, display, or access', boundary:'The client metric owner defines business logic, approves restatements, grants data access, and decides whether reporting is fit for business use.', awkward:'a month-end view whose total is correct for administrators but omits one region for managers because a permission join changed', finish:'all required tests pass against the approved expectation or the dashboard carries a visible incident owner, affected scope, and next update',service:'reporting-and-qa'},
  { slug:'offshore-admin-customer-reference-request-coordination', title:'Offshore customer reference requests: coordinate the introduction without spending goodwill', excerpt:'A careful workflow for matching, approving, scheduling, and closing customer-reference requests.', queue:'sales or partnership requests to speak with an existing customer about their experience', evidence:'the requesting account, opportunity context, requested topic, target timing, proposed reference customer, consent record, relationship owner, contact history, and participation limits', checks:'confirm the request is complete, review recent reference load, verify current consent, check conflicts or sensitive account status, and route the proposed match to the relationship owner', boundary:'The client decides which customer to approach, what may be disclosed, whether an incentive is appropriate, and whether the commercial context makes the request suitable.', awkward:'a high-value prospect requesting an urgent call with a customer who previously agreed in principle but has already taken several reference calls this quarter', finish:'both sides have an approved purpose and schedule, participation limits are recorded, follow-up is complete, and the reference history reflects the actual outcome',service:'admin-support'},
] as const;

export function buildBlogCampaignDetail(topic: BlogCampaignTopic) {
  const serviceHref = {
    'operations-support': 'project-coordination-support',
    'customer-support': 'customer-experience-support',
    'admin-support': 'shared-services-administration',
    'reporting-and-qa': 'back-office-quality-review',
  }[topic.service];
  return {
    keyTakeaways: [
      `Build the case from ${topic.evidence}.`,
      `Use explicit checks: ${topic.checks}.`,
      topic.boundary,
      `Close only when ${topic.finish}.`,
    ],
    sections: [
      { title: 'Define the queue before assigning it', body: `${topic.title} starts with a narrow intake rule. The queue contains ${topic.queue}. Give each item one stable identifier, one current owner, a received time, a due time based on the real source, and a visible status. Requests sent in chat or forwarded email still need to enter that record before work begins. Otherwise two people can act on different copies while each believes the other copy is current. Write down what qualifies, what belongs somewhere else, and who can change that rule. A Philippines-based specialist should be able to look at an item and tell whether it is ready, incomplete, duplicated, or outside scope. If the answer depends on private history or someone's memory, the intake design needs more work.` },
      { title: 'Assemble the source record', body: `The working evidence is ${topic.evidence}. Link to the approved source system where possible instead of building a second database in a personal sheet. Record the source version or retrieval time when a field may change. Keep customer, employee, supplier, and account data to the minimum needed for this task. The Philippine Data Privacy Act places accountability on organizations that control or process personal information, so convenience is not a reason to copy an entire record into a broad tracker. When two sources disagree, preserve both values and their origins. Do not silently pick the one that makes the case easier to close. A concise conflict note gives the client owner a decision they can actually review.` },
      { title: 'Run checks that another person can repeat', body: `The procedure should require the specialist to ${topic.checks}. Put the checks in the same order workers encounter the evidence, and show one clean example beside one borderline example. A checkbox alone proves little unless the underlying field or source remains traceable. For each completed check, capture the actor, time, result, and any relevant source link. Avoid free-text conclusions when a small controlled status will do, but leave room for a factual note when the evidence does not fit the expected path. A second worker should be able to repeat the review without asking what the first worker meant. That repeatability matters more than a perfectly tidy dashboard.` },
      { title: 'Keep consequential decisions with the client', body: `${topic.boundary} The offshore role can gather records, apply documented rules, prepare a draft, and route an exception. It should not turn an unanswered request into approval or use job seniority as a substitute for the named authorization path. List observable triggers for escalation, the primary owner, a backup, the response window, and the safe action while the case waits. If the deadline arrives first, preserve the item and report the exposure. Do not invent a result to keep an activity metric green. Good role design makes a correct stop easy to recognize and treats a well-supported escalation as completed work for the specialist.` },
      { title: 'Practice the case people are likely to mishandle', body: `Use ${topic.awkward} as a calibration exercise before the queue goes live. Give the same source packet and current procedure to an operator and reviewer, then ask each person to state the supported facts, missing facts, permitted next action, and decision owner. Compare their reasoning, not only their final label. If they reach different answers, fix the definition or example before adding volume. Also rehearse a duplicate request, an unavailable approver, a source update that arrives during review, and a system failure after someone presses save. The drill should expose where ownership becomes vague and which part of the evidence is hard to retrieve.` },
      { title: 'Design the handoff for different working hours', body: `A Philippines-based team may finish its shift while a client owner is still offline. The handoff needs more than a status such as "pending." It should state what happened, which source was checked, what remains uncertain, the exact decision requested, the consequence of waiting, and the next review time. Keep that note with the case. The incoming worker should acknowledge ownership through a named account rather than receiving credentials or an unexplained screenshot. NIST Cybersecurity Framework 2.0 organizes security work around governance, identification, protection, detection, response, and recovery. Those ideas are useful here because a handoff must protect the record and still support recovery when a step fails.` },
      { title: 'Reconcile the downstream result', body: `The last workflow status is not proof that the intended result occurred. Close the case only when ${topic.finish}. Compare the approved instruction with the live record that should now reflect it. Look for a duplicate action, a stale integration, a notice left in draft, or a change applied to the wrong account. If another system updates later, keep the item in a reconciliation state until that check is possible. Record rejected and reversed actions as well as successful ones. This produces an honest queue history and helps the manager distinguish slow review from failed execution. The specialist can perform the comparison; the authorized client owner decides how to correct a consequential mismatch.` },
      { title: 'Review a mixed sample and improve the instruction', body: `During the first weeks, review a small mixed sample that includes ordinary work, exceptions, handoffs, rejected proposals, and reopened cases. Check intake completeness, source traceability, adherence to the stated boundary, review time, and downstream agreement. Do not publish a universal productivity or quality claim from one client queue. The useful output is a list of specific instruction changes, each with an owner and effective date. Retire outdated examples so workers do not have two active rules. Where the sample shows repeated missing data, repair the intake. Where it shows inconsistent decisions, send the question to the policy owner. Where it shows an application fault, assign the system owner. The routine gets stronger when each observed defect changes the right part of the process.`, },
    ],
    internalLinks: [
      { label: `Explore ${topic.service.replaceAll('-', ' ')}`, href: `/services/${serviceHref}`, note: 'Turn this workflow into a scoped Philippines-based role.' },
      { label: 'Review the research library', href: '/research', note: 'Test operating assumptions with stated methods and limits.' },
    ],
    banners: [
      { label:'Scope the queue', title:'Write the evidence and stopping point first', body:'Define the repeatable work, client decision owner, and awkward case before assigning access.', href:'/contact-us', linkText:'Plan the role' },
      { label:'Pilot the handoff', title:'Test one ordinary case and one exception', body:'See whether the operator and reviewer reach the same supported next step.', href:'/contact-us', linkText:'Discuss a pilot' },
      { label:'Review the result', title:'Inspect the live downstream record', body:'Reconcile what was approved with what the system actually shows.', href:'/contact-us', linkText:'Scope the workflow' },
    ],
    faqs: [
      { question:'What should the Philippines-based specialist own?', answer:'The specialist can own documented intake, evidence checks, preparation, routing, and reconciliation. The client keeps the consequential decisions named in the procedure.' },
      { question:'What happens when the records disagree?', answer:'Keep both sources visible, record the conflict, pause at the written stopping point, and send a bounded decision request to the named client owner.' },
      { question:'How should managers review the work?', answer:'Use a mixed sample of ordinary items, exceptions, handoffs, rejected proposals, and reopened cases. Compare each result with its source and downstream record.' },
    ],
    sources,
  };
}

export const september18BlogPosts = topics.map((topic) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  minutes: 10,
  published: september18CampaignDate,
  image,
  citations: sources.map((source) => source.url),
}));

export const september18BlogDetails = Object.fromEntries(topics.map((topic) => [topic.slug, buildBlogCampaignDetail(topic)])) as Record<string, ReturnType<typeof buildBlogCampaignDetail>>;
