export const campaignDate = '2026-08-31';
const image = '/philippines-team.jpg';
const nist = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Risk-management guidance for governing and reviewing access.' };
const npc = { name: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'The controller remains accountable when processing is subcontracted.' };
const npcRules = { name: 'Philippine National Privacy Commission, implementing rules', url: 'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/', note: 'Rules for processor contracts and organizational, physical, and technical safeguards.' };

const seeds = [
  ['philippines-offshore-invoice-processing-controls','Philippines offshore invoice processing: a control-first workflow','Separate invoice preparation from payment authority with a queue, evidence rules, and a clear exception path.','Define the invoice queue','List the documents, fields, matching rules, system destination, and finish state. A completed record should show its source and any open exception.','Separate preparation from release','A Philippines-based specialist may prepare a payment batch, but bank-detail changes and payment release stay with named client owners.','Review the evidence','Sample invoices against purchase orders, approvals, system entries, and exception outcomes. Activity totals do not prove accuracy.'],
  ['offshore-saas-renewal-administration-playbook','Offshore SaaS renewal administration: a practical playbook','Surface renewal facts early while budget and contract decisions stay with the client.','Build one renewal register','Record the owner, renewal date, notice window, current price, users, and contract location. Flag missing fields instead of guessing.','Work backward from notice','Gather usage and owner intent before the cancellation deadline. Escalate unanswered requests on a written schedule.','Close the decision loop','Save the approval, vendor confirmation, price, and next renewal date. Route ending products into data export and access removal.'],
  ['philippines-customer-refund-escalation-matrix','Philippines customer refund escalation matrix','Give support agents precise refund lanes, evidence requirements, and fast escalation for unusual cases.','Classify routine requests','Define lanes by product, reason, age, amount, and payment method. State which cases agents may resolve and which need approval.','Preserve the case evidence','Record the order, request, delivery evidence, policy version, amount, and proposed action in the case system.','Audit promises and outcomes','Review approved, denied, and escalated cases. Check customer wording, approval evidence, payment outcome, and time to closure.'],
  ['offshore-crm-data-cleanup-quality-plan','Offshore CRM data cleanup: a quality plan that preserves evidence','Clean records through reversible queues, field rules, and sampled review instead of mass edits.','Write field rules first','Name the authoritative source for every field and include examples for blanks, conflicts, inactive accounts, and duplicates.','Quarantine ambiguity','Put uncertain legal entities, shared inboxes, and records tied to open deals in an exception queue. Do not force a guess.','Sample by risk','Compare source, original value, new value, rule used, and reviewer decision. Expand batches only after the error rate is acceptable.'],
  ['philippines-ecommerce-catalog-operations-checklist','Philippines ecommerce catalog operations checklist','Organize product updates around approved source data, preview checks, and rollback-ready publishing.','Prepare an approved source packet','Provide identifiers, copy, price, variants, inventory rules, images, and market restrictions. State which system wins when records disagree.','Stage and preview','Check variants, image order, mobile display, links, tax class, shipping fields, and search visibility before release.','Record the release','Save changed identifiers, approver, publication time, live check, and rollback instruction. Pause the batch if validation fails.'],
  ['offshore-recruiting-interview-scheduling-sop','Offshore recruiting interview scheduling SOP','Move coordination offshore while recruiters retain candidate judgment and hiring decisions.','Map each interview stage','List the duration, participants, scheduling window, location, template, and approval needed before a candidate advances.','Protect candidate information','Limit access to scheduling fields. Keep resumes, compensation notes, and feedback out of informal channels.','Handle exceptions carefully','Route accommodations, interviewer conflicts, repeated no-shows, and complaints to named owners without interpreting policy.'],
  ['philippines-insurance-document-indexing-workflow','Philippines insurance document indexing workflow','Index policy and claim documents with constrained access, naming rules, and a separate decision lane.','Build the document taxonomy','Define classes and required metadata, including record identifier, date, sender, version, and sensitivity.','Constrain the role','The specialist may classify, name, upload, and route files. Coverage and claim decisions remain with designated client staff.','Resolve imperfect inputs','Unreadable pages, mixed customers, duplicates, and suspicious files enter an exception queue while the original is preserved.'],
  ['offshore-sales-proposal-production-handoff','Offshore sales proposal production: the approval handoff','Assemble proposals offshore without transferring pricing, legal, or commitment authority.','Create an input gate','Require the customer, scope, products, approved price inputs, owner, due date, and template before drafting begins.','Mark decision fields','Discounts, delivery commitments, security answers, and nonstandard terms need named reviewers and visible placeholders.','Preserve version evidence','Record who reviewed pricing, scope, and terms, then save the exact issued version beside the opportunity.'],
  ['philippines-logistics-exception-desk-guide','Philippines logistics exception desk: an operating guide','Route shipment exceptions through evidence, response clocks, and client-owned commercial decisions.','Normalize exception signals','Map carrier feeds, warehouse notes, customer messages, and order records to a small set of reason codes.','Set the next allowed action','Specify evidence and permitted actions for each code. Keep refunds, reshipments, and delivery promises within written limits.','Review recurring causes','Inspect samples by carrier, route, warehouse, product, and reason code before changing an upstream process.'],
  ['offshore-knowledge-base-maintenance-routine','Offshore knowledge base maintenance: a safe publishing routine','Keep support guidance current through owner-approved changes, link checks, and expiration dates.','Inventory before rewriting','Record each page, audience, owner, review date, product area, and usage signal. Route duplicates and orphaned pages for review.','Trace every change','Link the draft to an approved release, policy, or incident. New customer promises require business-owner approval.','Publish with an exit route','Save the prior version, test the live page and search result, record the release, and set the next review date.'],
  ['philippines-month-end-reporting-support-calendar','Philippines month-end reporting support calendar','Build a close-support calendar around source locks, reconciliations, and client sign-off.','Map dependencies by day','List each input, source, cutoff, owner, expected arrival, and downstream report. Define what can proceed when an input is late.','Keep judgment with the controller','Unexpected accruals, classifications, material variances, and policy questions go to the client accounting owner.','Run a close retrospective','Record late inputs, rework, findings, and workarounds. Fix one recurring cause before the next close.'],
  ['offshore-vendor-onboarding-document-checklist','Offshore vendor onboarding document checklist','Collect supplier records through controlled intake while risk acceptance and payment setup remain client decisions.','Define the vendor packet','List registration, tax, contact, service, security, insurance, agreement, and payment records required for each vendor class.','Protect payment details','Verify bank instructions through a trusted path outside the requesting email. Collection does not grant approval authority.','Separate review lanes','Legal, security, privacy, finance, and business owners record their decisions independently before onboarding closes.'],
] as const;

export const august31BlogPosts = seeds.map(([slug,title,excerpt]) => ({slug,title,excerpt:`Published August 31, 2026. ${excerpt}`,minutes:9,published:campaignDate,image,citations:[nist.url,npc.url]}));
export const august31BlogDetails = Object.fromEntries(seeds.map(([slug,,,_h1,b1,h2,b2,h3,b3]) => [slug,{
  keyTakeaways:[b1,b2,b3], sections:[{title:_h1,body:b1},{title:h2,body:b2},{title:h3,body:b3}],
  internalLinks:[{label:'Plan an operations support role',href:'/services/operations-support',note:'Turn the workflow into tasks, controls, and a first-week review.'},{label:'Review related research',href:'/research',note:'Check the assumptions behind Philippines-based staffing decisions.'}],
  banners:[{label:'Scope checkpoint',title:'Put the workflow into a role brief',body:'Name the queue, access, approvals, and reviewer before hiring.',href:'/contact-us',linkText:'Discuss the role'},{label:'Pilot checkpoint',title:'Start with a reviewable batch',body:'Use a small sample to test the process and control points.',href:'/contact-us',linkText:'Plan a pilot'},{label:'Next step',title:'Build the handoff around real work',body:'Translate this guide into a staffing plan a manager can inspect.',href:'/contact-us',linkText:'Contact us'}],
  faqs:[{question:'What stays with the client?',answer:'Keep policy, legal, financial, customer, and risk decisions with a named client owner unless written delegation says otherwise.'},{question:'How should a pilot start?',answer:'Use representative examples, limited access, a small live batch, and a scheduled review before expanding.'}], sources:[nist,npc,npcRules]
}])) as Record<string,any>;

export const august31ResearchPosts = [
 {slug:'philippine-digital-economy-workforce-planning-2026',title:'Philippine digital economy workforce: what national data can and cannot tell a buyer',excerpt:'Use national employment data as market context without treating it as proof of provider or candidate fit.',sections:[{heading:'Question and source',body:'This report asks what the Philippine Statistics Authority digital economy account contributes to an offshore staffing decision. The 2024 account is preliminary and its method remains under refinement.'},{heading:'Reported signal',body:'The PSA reported 11.30 million digital-economy workers in 2024, equal to 23.1 percent of national employment. This broad category is not an available candidate pool.'},{heading:'Limits',body:'The release does not establish a provider\'s reach, candidate skill, wage, availability, security practice, or retention. A national count cannot support a hiring promise.'},{heading:'Buyer application',body:'Test the real decision with a role brief, funnel evidence, work samples, interviews, access controls, and a reviewed pilot.'}],sources:[{name:'Philippine Statistics Authority, 2024 digital economy account',url:'https://psa.gov.ph/content/digital-economy-contributes-85-percent-philippine-economy-2024'}]},
 {slug:'philippines-outsourcing-processor-accountability-study',title:'Philippines outsourcing and processor accountability: a buyer control study',excerpt:'A source-based reading of controller responsibility when personal information processing is outsourced.',sections:[{heading:'Question and method',body:'Does outsourcing personal-data work transfer accountability? This study reads the Philippine Data Privacy Act and implementing rules. It is operational guidance, not legal advice.'},{heading:'Source finding',body:'Section 14 permits subcontracted processing but keeps the controller responsible for safeguards, confidentiality, and prevention of unauthorized use.'},{heading:'Control implications',body:'Buyers need a purpose, data inventory, role-based access, processor duties, incident contacts, subprocessor terms, retention rules, and an end-of-service process.'},{heading:'Decision check',body:'Before launch, identify the parties, test account provisioning and revocation, confirm the incident path, and inspect an audit record.'}],sources:[npc,npcRules]},
 {slug:'offshore-work-sampling-review-design-study',title:'Offshore work sampling: how to design a review that finds useful errors',excerpt:'Choose review samples by risk instead of relying on a single activity percentage.',sections:[{heading:'Research question',body:'How should a manager review recurring work when checking every item is impractical? The useful unit is a completed decision or record with its evidence and outcome.'},{heading:'Stratify the queue',body:'Separate ordinary work, new variants, high-value items, sensitive cases, overrides, and exceptions. Review more from risky or unfamiliar groups.'},{heading:'Classify findings',body:'Record the defect, impact, clarity of the instruction, compliance with the rule, and whether a control detected it.'},{heading:'Use the result',body:'Correct affected work, find whether the cause sits in training, source data, system design, workload, approval delay, or the written rule, then adjust review.'}],sources:[nist]},
 {slug:'philippines-cross-border-data-contract-controls-2026',title:'Philippines cross-border data contracts: five controls to verify before launch',excerpt:'Review Philippine privacy sources for buyers moving personal-data work across borders.',sections:[{heading:'Scope and sources',body:'This report reviews the Data Privacy Act, implementing rules, and the National Privacy Commission 2024 model clauses advisory. It is not jurisdiction-specific legal advice.'},{heading:'Five controls',body:'Verify roles, purpose and data categories, recipients and locations, security and incident duties, and return or deletion at the end of service.'},{heading:'Test contract against operation',body:'Compare the signed scope with actual systems, permissions, exports, administrators, subprocessors, backups, and retention settings.'},{heading:'Launch decision',body:'Run privacy and security review, test one account through revocation, confirm the incident contact, and preserve the evidence.'}],sources:[npc,npcRules,{name:'NPC Advisory No. 2024-01',url:'https://privacy.gov.ph/wp-content/uploads/2024/06/Published-NPC-Advisory-No.-2024-01-Contractual-Clauses-for-Cross-Border-Transfers_30May24.pdf'}]},
 {slug:'offshore-role-pilot-evidence-framework',title:'Offshore role pilots: an evidence framework for the first ten working days',excerpt:'Test task fit, access, handoffs, exceptions, and manager load before expanding an offshore role.',sections:[{heading:'Objective',body:'A pilot tests whether a defined workflow can operate safely with the proposed role, tools, schedule, and reviewers. Write questions and stop conditions first.'},{heading:'Evidence',body:'Track assignments, outputs, source evidence, review findings, exceptions, approval delays, access changes, and manager time.'},{heading:'Interpretation',body:'Separate worker performance from defects in the brief, source material, system, workload, and client response.'},{heading:'Expansion decision',body:'The client owner decides whether to expand, revise, repeat, or stop, then records reasons, risks, new access, and owners for open actions.'}],sources:[nist,{name:'NPC third-party guidance',url:'https://privacy.gov.ph/third-parties/'}]},
].map(post=>({...post,excerpt:`Published August 31, 2026. ${post.excerpt}`,published:campaignDate,thumbnail:image,cluster:'Workflow Design',stats:['Campaign publication: August 31, 2026','Source-backed operating analysis']}));
