import type { ResearchPost } from './fleet-data';
import { buildResearchSections, type ResearchStudyTopic } from './campaign-2026-09-18-research';

export const september22ResearchDate = '2026-09-22';
const sources = [
  {name:'NIST: Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST: SP 800-53 Rev. 5 Security and Privacy Controls',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'NIST: SP 800-171 Rev. 3',url:'https://csrc.nist.gov/pubs/sp/800/171/r3/final'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippine National Privacy Commission: Implementing Rules',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
  {name:'Philippine Statistics Authority: Labor Force Survey',url:'https://psa.gov.ph/statistics/labor-force-survey'},
  {name:'World Bank: Philippines Digital Economy Report',url:'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf'},
  {name:'ISO: ISO 9001 Quality Management Systems',url:'https://www.iso.org/iso-9001-quality-management.html'},
  {name:'FTC: CAN-SPAM Act Compliance Guide',url:'https://www.ftc.gov/business-guidance/privacy-security/can-spam-act-compliance-guide-business'},
  {name:'UK ICO: Right to Erasure',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/individual-rights/right-to-erasure/'}
] as const;

const topics: readonly ResearchStudyTopic[] = [
  {slug:'offshore-accounts-payable-invoice-approval-segregation-study',title:'Invoice-Approval Segregation in Offshore Accounts Payable',excerpt:'A decision-grade study for testing invoice preparation and approval boundaries without giving a support role payment authority.',subject:'accounts-payable invoice-approval segregation',population:'received invoices, matched invoices, duplicate candidates, exception packets, approval requests, and released items for one legal entity and review period',fields:'supplier, invoice identifier, purchase order, receipt evidence, amount, currency, preparer, approver, exception code, approval time, and payment state',errors:'self-approval, missing evidence, duplicate candidates, approval after release, unexplained overrides, wrong-entity routing, and shared-account activity',owner:'controller, accounts-payable manager, or designated payment approver',reserved:'approve an invoice, release payment, change supplier bank details, waive a control, or determine accounting treatment',service:'/services/finance-operations-support',label:'Explore Finance Operations Support'},
  {slug:'philippines-customer-support-refund-authority-boundary-study',title:'Refund-Authority Boundaries in Philippines Customer Support',excerpt:'A research design for testing whether refund cases are prepared and escalated consistently without unsupported customer promises.',subject:'customer-support refund authority',population:'refund inquiries, eligible routine cases, partial-refund requests, disputed cases, duplicate contacts, exceptions, and completed refunds during a stated period',fields:'request channel, order reference, governing policy version, eligibility facts, amount, reason, operator action, approver, promise, decision, and customer notification',errors:'unsupported promises, inconsistent eligibility, missing approvals, duplicate refunds, wrong amounts, policy-version errors, privacy leakage, and premature closure',owner:'customer-experience, finance, or refund-policy owner',reserved:'waive policy, approve an exception, release funds, change refund limits, or make a legal commitment',service:'/services/customer-experience-support',label:'Explore Customer Experience Support'},
  {slug:'offshore-data-retention-disposition-evidence-research',title:'Data-Retention Disposition Evidence in Offshore Operations',excerpt:'A bounded method for studying whether retention and deletion requests remain traceable without allowing an operations role to make legal judgments.',subject:'data-retention disposition evidence',population:'records reaching a retention trigger, deletion requests, legal-hold flags, duplicates, backups, exceptions, and completed dispositions in a defined system and period',fields:'record class, source, owner, governing schedule, trigger date, hold state, request identity, review decision, action time, system evidence, and exception',errors:'missing schedules, premature deletion, overdue retention, incomplete system coverage, unverified requesters, hold conflicts, and untraceable dispositions',owner:'privacy, legal, records-management, or designated data owner',reserved:'interpret law, set a retention period, lift a legal hold, approve an exception, or certify complete erasure',service:'/services/data-management-support',label:'Explore Data Management Support'},
  {slug:'offshore-marketing-consent-suppression-integrity-study',title:'Consent and Suppression Integrity in Offshore Marketing Operations',excerpt:'A source-backed test for whether marketing lists preserve consent, opt-out, and suppression evidence across routine campaign work.',subject:'marketing consent and suppression integrity',population:'new contacts, imported contacts, consent updates, unsubscribes, hard bounces, complaints, duplicates, suppressions, and campaign selections for a stated period',fields:'contact identifier, source, consent basis, capture time, jurisdiction, preference, opt-out time, suppression state, campaign, operator, and exception',errors:'missing provenance, late suppression, reintroduced contacts, conflicting preferences, duplicate profiles, wrong-jurisdiction rules, and unexplained manual overrides',owner:'marketing operations, privacy, or campaign-policy owner',reserved:'select a legal basis, override an opt-out, reinterpret consent, approve a disputed audience, or send an unapproved campaign',service:'/services/marketing-operations-support',label:'Explore Marketing Operations Support'},
  {slug:'philippines-project-dependency-aging-escalation-research',title:'Dependency Aging and Escalation in Philippines Project Coordination',excerpt:'A practical research framework for separating coordination delay from decisions that remain with project and client owners.',subject:'project dependency aging and escalation',population:'open dependencies, blocked tasks, decision requests, handoffs, reopened items, overdue responses, and resolved dependencies across one project interval',fields:'dependency, requesting task, owner, opened time, required decision, evidence packet, due point, reminders, response, downstream effect, and closure basis',errors:'unnamed owners, hidden blockers, duplicate chasing, unclear questions, stale due dates, unsupported status changes, and closure without evidence',owner:'project manager, workstream owner, or designated client decision-maker',reserved:'change scope, accept risk, approve budget, commit another team, revise a milestone, or declare completion',service:'/services/project-coordination-support',label:'Explore Project Coordination Support'}
];

export const september22ResearchPosts: readonly ResearchPost[] = topics.map((topic) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  published: september22ResearchDate,
  thumbnail: '/research/research-default.svg',
  cluster: topic.subject.includes('authority') || topic.subject.includes('retention') ? 'Hiring Controls' : 'Workflow Design',
  stats: ['Evidence-complete, boundary-correct disposition is the primary measure', 'Sources and operating assumptions checked September 22, 2026'],
  sections: buildResearchSections(topic),
  sources,
  serviceHandoff: {href:topic.service,label:topic.label,body:`Turn the findings on ${topic.subject} into a bounded Philippines-based role brief with documented access, examples, review, and escalation.`}
}));
