import type { ResearchPost } from './fleet-data';

export const september18ResearchDate = '2026-09-18';
const sources = [
  {name:'NIST: Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST: SP 800-53 Rev. 5 Security and Privacy Controls',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'NIST: SP 800-171 Rev. 3',url:'https://csrc.nist.gov/pubs/sp/800/171/r3/final'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippine National Privacy Commission: Implementing Rules',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
  {name:'Philippine Statistics Authority: Labor Force Survey',url:'https://psa.gov.ph/statistics/labor-force-survey'},
  {name:'World Bank: Philippines Digital Economy Report',url:'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf'},
  {name:'ISO: ISO 9001 Quality Management Systems',url:'https://www.iso.org/iso-9001-quality-management.html'},
  {name:'CISA: Cybersecurity Performance Goals',url:'https://www.cisa.gov/cyber-guidance/cybersecurity-performance-goals'},
  {name:'ILO: Working from home: From invisibility to decent work',url:'https://www.ilo.org/publications/working-home-invisibility-decent-work'}
] as const;

export type ResearchStudyTopic={slug:string;title:string;excerpt:string;subject:string;population:string;fields:string;errors:string;owner:string;reserved:string;service:string;label:string};
type T=ResearchStudyTopic;
const topics:readonly T[]=[
 {slug:'philippines-offshore-vendor-master-duplicate-detection-study',title:'Vendor-Master Duplicate Detection in Philippines Procurement Support',excerpt:'A decision-grade study design for finding duplicate supplier records without allowing a review role to merge identities or change payment instructions.',subject:'vendor-master duplicate detection',population:'active, inactive, newly requested, and recently changed supplier records for one legal entity and one stated review period',fields:'legal name, trading name, permitted registration identifier, approved address, bank-change state, requester, creation time, and source-system identifier',errors:'exact duplicates, formatting variants, related but distinct entities, reused contact details, missing identifiers, and false-positive matches',owner:'procurement or finance master-data owner',reserved:'approve a merge, deactivate a supplier, accept a new supplier, or change payment instructions',service:'/services/procurement-administration',label:'Explore Procurement Administration'},
 {slug:'philippines-offshore-crm-lead-routing-integrity-research',title:'CRM Lead-Routing Integrity for Philippines Revenue Operations',excerpt:'A research framework for measuring whether leads reach the right queue with source, ownership, and exception evidence intact.',subject:'CRM lead-routing integrity',population:'new, reassigned, duplicated, enriched, rejected, and exception-routed leads received through defined channels during a stated period',fields:'source channel, received time, territory inputs, account match, consent state, routing-rule version, owner, exception reason, and disposition',errors:'wrong-territory assignments, duplicate ownership, stale rules, missing consent evidence, unowned records, and unexplained overrides',owner:'revenue operations or sales-policy owner',reserved:'change territory policy, accept a disputed account match, suppress outreach, or promise a response',service:'/services/revenue-operations-support',label:'Explore Revenue Operations Support'},
 {slug:'offshore-month-end-close-evidence-completeness-study',title:'Month-End Close Evidence Completeness in Offshore Finance Operations',excerpt:'A bounded method for testing whether close-support packets are reviewable without shifting accounting judgment or approval authority.',subject:'month-end close evidence completeness',population:'scheduled reconciliations, supporting schedules, proposed entries, returned packets, and late-source exceptions for one close cycle',fields:'account, period, source report, preparer, retrieval time, balance, variance, explanation, reviewer question, approval state, and posting reference',errors:'missing sources, unexplained variances, stale extracts, unsupported adjustments, wrong-period evidence, reviewer returns, and unapproved postings',owner:'controller or designated accounting reviewer',reserved:'approve an entry, determine materiality, select an accounting treatment, or certify the close',service:'/services/finance-operations-support',label:'Explore Finance Operations Support'},
 {slug:'philippines-technical-support-incident-escalation-threshold-study',title:'Incident Escalation Thresholds in Philippines Technical Support',excerpt:'A source-backed test for whether a technical support desk recognizes severity without inventing diagnosis or business impact.',subject:'technical-support incident escalation thresholds',population:'routine tickets, repeat contacts, degraded-service reports, access incidents, suspected security events, and major-impact simulations',fields:'symptom, affected service, user count, start time, recurrence, workaround, security indicator, source, severity, escalation time, and owner response',errors:'under-escalation, over-escalation, unsupported severity, lost timestamps, premature closure, duplicates, and data sent through the wrong channel',owner:'incident commander, security owner, or designated service owner',reserved:'declare an incident, communicate business impact, authorize containment, or restore service',service:'/services/technical-support-desk',label:'Explore Technical Support Desk'},
 {slug:'offshore-knowledge-change-adoption-research',title:'Knowledge-Change Adoption in Offshore Customer Support',excerpt:'A research design for checking whether approved policy and product changes reach frontline answers before stale guidance reaches customers.',subject:'knowledge-change adoption',population:'approved changes, superseded articles, linked macros, sampled contacts, acknowledgements, and exceptions within a stated adoption window',fields:'source owner, version, effective time, affected content, publication time, acknowledgement, sampled use, conflict flag, escalation, and correction',errors:'late publication, stale macros, broken links, unacknowledged changes, conflicting sources, unsupported promises, and untraceable corrections',owner:'knowledge, product, policy, or customer-experience owner',reserved:'interpret policy, approve customer wording, authorize an exception, or publish a disputed change',service:'/services/customer-experience-support',label:'Explore Customer Experience Support'}
];

export const buildResearchSections=(t:ResearchStudyTopic)=>[
 {heading:'Executive finding',body:`${t.subject} is delegable only when the unit of review, permitted action, source hierarchy, stop conditions, and reviewer are explicit. Counting completed records is insufficient. A credible result shows whether the role used the right source, stayed inside authority, preserved contradictory evidence, and routed unresolved decisions to a named owner. Speed is secondary to traceability because a fast but unsupported action can create rework, privacy exposure, financial risk, or a misleading commitment. A documented escalation is therefore a successful controlled outcome when evidence or authority is absent. This conclusion is an operating inference from the control principles in the listed sources, not a claim that any particular provider or team has achieved a stated result.`},
 {heading:'Research question and scope',body:`Can a Philippines-based support role perform ${t.subject} consistently without becoming the decision-maker? Study ${t.population}. Capture ${t.fields}. Management must set the period, systems, channels, exclusions, evidence standard, and acceptable outcomes before sampling. Otherwise difficult cases can be removed after the fact or completion redefined. The role may collect, compare, classify, prepare, and route information. It may not ${t.reserved}; that authority remains with the ${t.owner}. The study should identify both routine work and the boundary cases most likely to invite unsupported judgment. The purpose is a bounded staffing decision, not a universal conclusion about offshore work.`},
 {heading:'Methodology',body:`Use a retrospective stratified review followed by a prospective pilot. Build a complete inventory for the stated period and remove test records only through a written exclusion rule. Separate ordinary items from exceptions, returns, duplicates, and owner-dependent cases. Sample every stratum rather than reviewing only successful closures. Two reviewers should independently apply one rubric to an overlap sample, compare disagreements, and repair ambiguous definitions before scoring the remainder. For every item, compare the action with the approved source version and authority boundary. Record missingness instead of inferring a value. Use redacted or synthetic cases for training and threshold tests; do not export personal information merely to simplify analysis. Report the numerator, denominator, exclusions, unresolved cases, source versions, and reviewer disagreement. After a control change, repeat a focused sample to test whether the intervention improved the workflow rather than just changing its labels.`},
 {heading:'Measures that support a decision',body:`The primary measure is evidence-complete, boundary-correct disposition: the share of reviewed items with a required source, permitted action, attributable actor, and reproducible final state. Report separate rates for ${t.errors}. Add median and upper-percentile handling time, but split active handling from system delay and owner waiting. Show the return rate and a reason for each return. Measure escalation completeness by whether the packet states the question, source, attempted checks, consequence, and requested owner action. Where reviewers classify outcomes, report agreement before reconciliation; a high final score achieved only after discussion can conceal an unclear rule. Do not turn a blended average into an individual performance claim. Case mix, missing records, policy changes, and outages belong beside the result.`},
 {heading:'Analysis and interpretation',body:`A low score does not identify its cause. Review failures in sequence: source availability, instruction clarity, access, system behavior, case complexity, operator action, reviewer consistency, and owner response. If the current source is absent or contradictory, repair governance before coaching the operator. If permissions are broad, reduce them to the approved tasks and retain named accounts and authentication controls. If exceptions recur, create a reason code and destination instead of relying on private-message workarounds. Compare routine and exception cohorts, inspect the tails of the age distribution, and preserve examples that contradict the dominant pattern. Facts are the observed record fields and timestamps. Analysis is the consistent application of the rubric. Causal explanations remain hypotheses unless the design tests them. Recommendations should therefore target the observed failure and state the uncertainty that remains.`},
 {heading:'Implementation guidance',body:`Begin with a role brief, field dictionary, source register, three ordinary examples, three boundary cases, an escalation template, and daily pilot review. The ${t.owner} owns policy and consequential decisions. The offshore role may own queue hygiene, evidence preparation, and prompt routing inside the procedure. Define a safe holding state so the operator is not rewarded for guessing. Give access only to the systems and actions required by the approved task. Preserve the original request, governing source, operator action, owner response, and correction history. Expand volume only after both routine work and exceptions are reviewable. A useful readiness gate asks whether a new reviewer can reconstruct what happened without relying on memory or private chat. If not, improve the record before scaling.`},
 {heading:'Limitations and uncertainty',body:`This is a documentary workflow-study design, not a performance, savings, legal-compliance, or market-wide claim. NIST, CISA, ISO, Philippine authorities, the World Bank, the ILO, and the Philippine Statistics Authority provide context for governance, privacy, security, quality systems, digital work, and labor conditions. They do not establish the result of a client process. Internal records may contain late updates, missing channels, inconsistent clocks, or decisions made outside the system. One period may miss seasonality and rare high-impact cases. Reviewer judgment can shift after calibration. Publish the evidence date, cohort, exclusions, source versions, and unresolved uncertainty. Repeat after material changes to systems, scope, policy, location, or staffing.`},
 {heading:'Decision checklist',body:`Before delegation, name the queue, source of truth, permitted actions, prohibited decisions, required fields, privacy rule, access profile, exception states, reviewer, and response owner. During the pilot, verify that the operator can find the current source, recognize an incomplete case, preserve original evidence, avoid unsupported inference, ask a precise question, and resume after an owner response. After the pilot, inspect a mixed sample rather than only completed work. Decide whether to expand, revise, or pause based on the failure modes. Expansion is reasonable only when the workflow makes the safe action easier than improvisation. A useful record shows what was known, what remained uncertain, what the role could do, and who accepted the consequential decision.`},
 {heading:'Review cadence and reporting',body:`Use a short review cadence during launch, then lengthen it only when the evidence supports doing so. A daily pilot check can catch source confusion and permission gaps before they spread across a larger queue. A weekly summary should show volume by case type, evidence-complete dispositions, returns by reason, active handling time, owner waiting, unresolved exceptions, and any change to the governing source. Keep the underlying case references so a manager can test the summary against the record. Do not rank workers from a small or uneven sample. If one operator receives more complex cases, separate that case mix before comparing results. Record corrective actions with an owner and a review date. Close an action only after a follow-up sample shows whether the defect changed. If the same exception keeps returning, revisit the service definition or approval path instead of treating every occurrence as an isolated mistake. This cadence keeps ${t.subject} tied to operating evidence and gives the ${t.owner} a clear place to resolve decisions that should not migrate into the support role.`},
 {heading:'FAQs',body:`Is escalation a failed outcome? No; when evidence or authority is missing, a timely complete escalation is correct. Should the role receive administrator access to avoid delays? No; access should follow approved tasks, and recurring gaps belong with the system owner. Can one pilot prove future quality? No; it supports a bounded decision for the tested queue, period, people, tools, and rules. Should personal information be copied into a research sheet? Avoid it; use minimum necessary fields, controlled systems, redaction, or synthetic data. Who decides? The ${t.owner} retains authority to ${t.reserved}. When should the study repeat? After material workflow, policy, access, channel, or staffing changes and periodically enough to detect drift.`}
];

export const september18ResearchPosts:readonly ResearchPost[]=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:september18ResearchDate,thumbnail:'/research/research-default.svg',cluster:t.subject.includes('evidence')||t.subject.includes('threshold')?'Hiring Controls':'Workflow Design',stats:['Evidence-complete disposition is the primary measure','Owner waiting and active handling must be reported separately'],sections:buildResearchSections(t),sources,serviceHandoff:{href:t.service,label:t.label,body:`Turn the findings on ${t.subject} into a bounded Philippines-based role brief with documented access, examples, review, and escalation.`}}));
