export const september10CampaignDate = '2026-09-10' as const;
const image = '/philippines-team.jpg';
const blogSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'Republic Act No. 10173, Data Privacy Act of 2012', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html' },
];
const blogs = [
  ['philippines-shared-inbox-attachment-review', 'Philippines shared-inbox attachment review: contain the risky file', 'email attachments, sender context, case records, and approved storage', 'opening unknown files, overriding security warnings, and deciding whether a message is malicious'],
  ['offshore-customer-address-change-queue', 'Offshore customer address changes: verify before updating the record', 'the request, current account record, approved verification result, and requested address', 'identity exceptions, account recovery, fraud decisions, and policy overrides'],
  ['philippines-purchase-order-acknowledgment-desk', 'Philippines purchase-order acknowledgments: turn supplier replies into a usable queue', 'purchase orders, supplier acknowledgments, promised dates, quantities, and line-level differences', 'commercial concessions, substitutions, cancellations, and supplier commitments'],
  ['offshore-crm-consent-record-cleanup', 'Offshore CRM consent cleanup: repair evidence without inventing permission', 'consent source, purpose, timestamp, channel, record owner, and suppression status', 'granting consent, interpreting law, restoring suppressed contacts, and changing retention policy'],
  ['philippines-service-appointment-confirmation-workflow', 'Philippines service appointment confirmations: close the scheduling loop', 'approved appointments, customer contact preferences, technician windows, location details, and dependencies', 'pricing promises, technical diagnosis, unsafe access, and eligibility exceptions'],
  ['offshore-product-catalog-image-qa', 'Offshore product catalog image QA: check the asset before it goes live', 'approved image files, SKU mappings, alt text, crop rules, and channel previews', 'usage rights, regulated claims, brand exceptions, and final publication approval'],
  ['philippines-expense-receipt-matching-routine', 'Philippines expense receipt matching: build a reviewable exception file', 'submitted receipts, transaction records, dates, amounts, currencies, and cost-center references', 'reimbursement approval, tax treatment, policy waivers, and suspected fraud'],
  ['offshore-webinar-registration-support', 'Offshore webinar registration support: manage the list without blurring consent', 'registration records, event rules, consent fields, attendee questions, and delivery status', 'marketing permission, speaker commitments, refunds, and privacy exceptions'],
  ['philippines-vendor-insurance-certificate-tracking', 'Philippines vendor insurance tracking: monitor evidence without judging coverage', 'approved vendor requirements, certificate fields, effective dates, expiry dates, and named owners', 'coverage adequacy, legal interpretation, vendor suspension, and risk acceptance'],
  ['offshore-knowledge-base-broken-link-review', 'Offshore knowledge-base link reviews: find dead ends before agents do', 'the current article version, link destination, access result, anchor text, and owning team', 'rewriting policy, approving a replacement source, access expansion, and publication'],
  ['philippines-sales-demo-follow-up-administration', 'Philippines sales-demo follow-up: keep promises attached to the record', 'meeting notes, approved follow-up language, promised materials, owners, and due dates', 'pricing, contract terms, product commitments, qualification, and closing decisions'],
  ['offshore-customer-document-expiry-reminders', 'Offshore customer document expiry reminders: notify without making the decision', 'approved document types, recorded expiry dates, notice cadence, delivery results, and case owners', 'validity rulings, deadline waivers, account restrictions, and legal advice'],
] as const;
export const september10BlogPosts = blogs.map(([slug, title, evidence]) => ({ slug, title, excerpt: `A practical guide to handling ${evidence} in a bounded Philippines-based support workflow.`, minutes: 9, published: september10CampaignDate, image, citations: blogSources.map((source) => source.url) }));
export const september10BlogDetails = Object.fromEntries(blogs.map(([slug, title, evidence, boundary], index) => [slug, {
  keyTakeaways: [`Keep one case record tied to ${evidence}.`, `Leave ${boundary} with the client owner named in the procedure.`, 'Check the downstream record before calling the work complete.'],
  sections: [
    { title: 'Start with the actual queue', body: `${title} works best as a narrow queue, not a loose request sent through chat. The intake record should identify ${evidence}. Keep the source file or source-system link with the case. If two records disagree, show the conflict and stop at the point the written procedure requires.` },
    { title: 'Write down the safe stopping point', body: `The support specialist can complete repeatable checks and prepare the next action. ${boundary} stay with an authorized client reviewer. The procedure should say who that person is, what evidence they need, and what happens when they are unavailable. A due date does not silently widen the role.` },
    { title: index % 2 === 0 ? 'Keep the evidence useful' : 'Protect the record while it moves', body: 'Give each worker an individual account and only the fields needed for this queue. Store notes in the approved system, not a private spreadsheet. Record the source, action, actor, time, and review result. Where personal data appears, collect and retain only what the client procedure permits.' },
    { title: 'Test an awkward case', body: `A useful pilot includes one ordinary item and a case with missing, stale, or conflicting evidence. It should also test an unavailable reviewer and a failed system update. Watch the handoff in real time. The purpose is to find where the instruction fails before the queue grows, not to grade a person on an undefined rule.` },
    { title: 'Reconcile the finish', body: 'Before closure, compare the approved action with the live customer, supplier, finance, or content record that should have changed. Check for duplicate updates and notices that were prepared but never sent. Leave every unresolved item open with an owner and next review time.' },
  ],
  internalLinks: [{ label: 'Plan an operations support role', href: '/services/operations-support', note: 'Turn the queue into a role with explicit limits.' }, { label: 'Use the research library', href: '/research', note: 'Test workflow assumptions with a stated method.' }],
  banners: [{ label: 'Scope', title: 'Put the stopping point in writing', body: 'Name the evidence, permitted action, and decision owner.', href: '/contact-us', linkText: 'Plan the role' }, { label: 'Pilot', title: 'Try one difficult example', body: 'Test missing evidence and an unavailable reviewer.', href: '/contact-us', linkText: 'Scope a pilot' }, { label: 'Review', title: 'Inspect the live result', body: 'Close only after the downstream record agrees.', href: '/contact-us', linkText: 'Discuss the workflow' }],
  faqs: [{ question: 'What can the offshore specialist decide?', answer: 'Only the routine actions that the current client procedure explicitly assigns to the role.' }, { question: 'What should happen when evidence conflicts?', answer: 'Keep both sources visible, pause the consequential action, and route the case to the named owner.' }],
  sources: blogSources,
}])) as Record<string, any>;
const researchSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf' },
  { name: 'NIST Privacy Framework 1.0', url: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.01162020.pdf' },
  { name: 'Republic Act No. 10173, Data Privacy Act of 2012', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html' },
  { name: 'NIST SP 800-61 Rev. 3, Incident Response Recommendations', url: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final' },
  { name: 'NIST SP 800-53 Rev. 5, Security and Privacy Controls', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
];
const studies = [
  ['philippines-offshore-escalation-packet-retrievability-study', 'Can a reviewer find the evidence in an offshore escalation packet?', 'Measure whether a client reviewer can retrieve the source, issue, requested decision, and deadline without asking the operator to reconstruct the case.', 'packet opened to all required fields found', 'missing fields, retrieval time, follow-up questions, and reviewer agreement'],
  ['offshore-queue-duplicate-work-detection-research', 'Duplicate work in offshore queues: a record-linkage study', 'Test how often two workers begin the same underlying request because channels or identifiers fail to connect it.', 'request first received to duplicate recognized', 'shared identifiers, channel, assignment time, work performed, and final disposition'],
  ['philippines-offshore-policy-exception-aging-analysis', 'How long do offshore policy exceptions wait for an owner?', 'Describe the time that correctly escalated exceptions spend waiting for an authorized decision.', 'exception first flagged to owner decision recorded', 'queue stage, severity rule, owner, reminders, pauses, and resolution'],
  ['offshore-customer-record-correction-reversal-study', 'Do offshore customer-record corrections stay corrected?', 'Follow approved data corrections to see whether imports, integrations, or later edits reverse the change.', 'approved correction to end of the observation window', 'source value, approved value, systems touched, later changes, actor, and reason'],
  ['philippines-offshore-instruction-example-boundary-test', 'Do worked examples cover the boundary of an offshore role?', 'Test whether operators and reviewers distinguish permitted routine work from cases that require client judgment.', 'case presented to classification and stated next action', 'instruction version, case features, classification, reason, confidence, and adjudication'],
] as const;
export const september10ResearchPosts = studies.map(([slug, title, question, unit, fields], index) => ({
  slug, title, excerpt: question, published: september10CampaignDate, thumbnail: image, cluster: index % 3 === 0 ? 'Scope Benchmarks' : index % 3 === 1 ? 'Workflow Design' : 'Hiring Controls',
  stats: [`Unit of analysis: ${unit}`, 'Results describe the sampled workflow, not the Philippine workforce'],
  sections: [
    { heading: 'Research question and scope', body: `${question} The scope is one named client queue, one current procedure version, the systems used by that queue, and a fixed observation window. Define the start and end events before collecting records. The unit of analysis is ${unit}. People, providers, and other queues outside that frame are out of scope.` },
    { heading: 'Methodology', body: `Create a consecutive or randomly selected cohort and document the selection rule. Capture ${fields}. Keep exclusions and missing records in a separate log rather than quietly dropping them. Remove direct personal identifiers from the analysis copy. A second reviewer independently codes at least a stated subset, then both reviewers record how disagreements were resolved.` },
    { heading: 'Measures and reporting', body: 'Report the cohort count, eligible count, excluded count, missing-data count, numerator, denominator, and observation dates. Show medians and ranges for elapsed-time measures because a few old cases can distort an average. For classification measures, publish the coding definitions and agreement count before adjudication. Breakdowns with very small cells should be combined or withheld to reduce privacy risk.' },
    { heading: 'Inference boundaries', body: 'The records can reveal sequence, frequency, delay, and association inside the sampled workflow. They cannot establish that location, nationality, or an individual worker caused the result. A change after an intervention is not proof that the intervention caused it unless the design controls credible alternatives. Treat each finding as a prompt for a bounded workflow test.' },
    { heading: 'Operational use', body: 'Choose one repair that matches the observed failure point, such as a required field, shared identifier, owner rota, integration rule, or clearer counterexample. Pilot the change on a limited queue and keep the original definitions for comparison. Client owners retain consequential decisions, including policy exceptions, account restrictions, financial approvals, and findings about worker performance.' },
    { heading: 'Limitations', body: 'The study may miss work handled outside the selected systems. Later edits can erase the original state, timestamps may reflect system processing rather than human action, and the sample may contain too few rare exceptions. Reviewer knowledge can affect coding. The findings do not estimate provider quality, worker productivity, legal compliance, or results for other clients or future periods.' },
    { heading: 'References and evidence use', body: 'The references below are primary government publications. NIST materials supply control and risk-management concepts. Philippine law and regulator materials supply privacy-accountability context. Neither source set supplies the study result. The result must come from the defined client cohort, and the client should obtain qualified legal advice for legal conclusions.' },
  ], sources: researchSources,
}));
