import type { ResearchPost } from './fleet-data';
import { buildResearchSections, type ResearchStudyTopic } from './campaign-2026-09-18-research';

export const september24ResearchDate = '2026-09-24';

const sources = [
  {name:'NIST: Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST: CSF 2.0 Quick-Start Guides',url:'https://www.nist.gov/cyberframework/quick-start-guides'},
  {name:'NIST: SP 800-53 Rev. 5 Security and Privacy Controls',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'NIST: SP 800-171 Rev. 3',url:'https://csrc.nist.gov/pubs/sp/800/171/r3/final'},
  {name:'NIST: SP 1305 Cybersecurity Supply Chain Risk Management',url:'https://csrc.nist.gov/pubs/sp/1305/final'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippine National Privacy Commission: Implementing Rules and Regulations',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
  {name:'Philippine National Privacy Commission: Advisory Opinions',url:'https://privacy.gov.ph/pips-and-pics/advisory-opinions/'},
  {name:'Philippine National Privacy Commission: Advisories and Circulars',url:'https://privacy.gov.ph/pips-and-pics/advisories-circulars/'},
  {name:'U.S. GAO: Financial Audit Manual, Volume 1',url:'https://www.gao.gov/products/gao-22-105894'}
] as const;

const topics: readonly ResearchStudyTopic[] = [
  {slug:'offshore-unapplied-cash-resolution-evidence-study',title:'Unapplied Cash Resolution Evidence in Offshore Finance Operations',excerpt:'A bounded study for testing whether incoming receipts are matched and routed with enough evidence while accounting decisions stay with the client.',subject:'unapplied cash resolution evidence',population:'unmatched receipts, partial matches, short payments, overpayments, deductions, duplicate candidates, reversals, and resolved items for one legal entity and review period',fields:'receipt identifier, payer, amount, currency, value date, remittance source, invoice candidate, customer account, match basis, exception reason, preparer, reviewer, and ledger state',errors:'unsupported matches, wrong-customer application, currency mismatch, duplicate application, missing remittance, unexplained write-offs, stale exceptions, and changes made without attributable review',owner:'controller, accounts-receivable manager, or designated cash-application reviewer',reserved:'approve a write-off, create a credit, change payment terms, resolve a customer dispute, post an unsupported match, or determine accounting treatment',service:'/services/finance-operations-support',label:'Explore Finance Operations Support'},
  {slug:'philippines-customer-complaint-reason-code-consistency-research',title:'Complaint Reason-Code Consistency in Philippines Customer Support',excerpt:'A research design for checking whether complaint records describe the customer issue consistently without turning classification into a policy decision.',subject:'customer complaint reason-code consistency',population:'new complaints, repeat contacts, reopened cases, multi-issue contacts, escalations, transfers, and closed complaints across defined channels and one review period',fields:'customer statement, product or service, contact channel, event time, selected reason code, secondary issue, policy source, operator action, escalation, owner decision, and closure basis',errors:'codes that contradict the customer statement, forced single-issue labels, missing policy versions, hidden repeat contacts, unsupported severity, premature closure, privacy leakage, and inconsistent coding between reviewers',owner:'customer-experience, complaints, quality, or policy owner',reserved:'decide redress, admit liability, change policy, determine regulatory status, promise an outcome, or close a disputed complaint',service:'/services/customer-experience-support',label:'Explore Customer Experience Support'},
  {slug:'offshore-crm-lifecycle-stage-provenance-study',title:'CRM Lifecycle-Stage Provenance in Offshore Revenue Operations',excerpt:'A source-backed method for testing whether CRM stage changes can be reconstructed without allowing a data-support role to invent buying intent.',subject:'CRM lifecycle-stage provenance',population:'new contacts, qualified records, recycled leads, converted opportunities, disqualified records, merged profiles, manual overrides, and reopened records during a stated period',fields:'record identifier, source event, prior stage, new stage, governing rule version, qualifying evidence, actor, change time, override reason, account owner, consent state, and downstream automation',errors:'stage changes without evidence, stale rule use, circular automation, duplicate profiles, missing consent context, unexplained overrides, false conversion, lost prior state, and owner changes disguised as qualification',owner:'revenue-operations, sales-operations, marketing-operations, or designated CRM policy owner',reserved:'declare sales qualification, infer customer intent, approve an exception, merge disputed identities, change territory policy, or commit a seller to follow-up',service:'/services/revenue-operations-support',label:'Explore Revenue Operations Support'},
  {slug:'philippines-purchase-requisition-evidence-completeness-study',title:'Purchase-Requisition Evidence Completeness in Philippines Procurement Support',excerpt:'A practical study for deciding whether requisitions reach approvers with complete evidence while supplier choice and spend authority remain client-owned.',subject:'purchase-requisition evidence completeness',population:'new requisitions, returned requests, amended requests, urgent requests, sole-source requests, cancelled items, and approved requisitions for one business unit and review period',fields:'requester, business purpose, item or service, quantity, required date, budget reference, supplier candidate, quote evidence, risk flags, approver path, revision history, and final disposition',errors:'missing purpose, inconsistent quantities, stale quotes, split requests, wrong approval path, unsupported urgency, absent conflict disclosure, duplicate demand, unauthorized supplier commitments, and approval before required review',owner:'procurement, budget, legal, security, or designated spend approver',reserved:'select a supplier, approve spend, waive competition, interpret contract terms, accept risk, create a purchase commitment, or decide that a requisition is necessary',service:'/services/procurement-administration',label:'Explore Procurement Administration'},
  {slug:'offshore-data-subject-request-identity-routing-research',title:'Identity and Routing Evidence for Data-Subject Requests in Offshore Administration',excerpt:'A privacy-aware research model for studying request intake, identity evidence, scope, and routing without shifting legal judgments to an administrative role.',subject:'data-subject request identity and routing evidence',population:'access, correction, deletion, objection, portability, restriction, and inquiry records received through approved channels during a defined review window',fields:'request channel, received time, claimed identity, account reference, request type, stated scope, jurisdiction flag, verification method, systems named, owner, due-date rule, correspondence, decision, and completion evidence',errors:'unverified requesters, excessive identity collection, misclassified rights, missing receipt times, incomplete system routing, insecure correspondence, unsupported deadline calculations, duplicate requests, and closure without owner evidence',owner:'privacy, legal, data-protection, records, or designated data owner',reserved:'interpret a legal right, choose the lawful response, deny a request, extend a deadline, disclose personal data, lift a hold, or certify that every system has completed an action',service:'/services/data-management-support',label:'Explore Data Management Support'}
];

export const september24ResearchPosts: readonly ResearchPost[] = topics.map((topic, index) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  published: september24ResearchDate,
  thumbnail: '/research/research-default.svg',
  cluster: index === 1 || index === 4 ? 'Hiring Controls' : index === 0 || index === 3 ? 'Scope Benchmarks' : 'Workflow Design',
  stats: ['Primary measure: evidence-complete, boundary-correct disposition', 'Sources and operating assumptions checked September 24, 2026'],
  sections: buildResearchSections(topic),
  sources,
  serviceHandoff: {href:topic.service,label:topic.label,body:`Turn the findings on ${topic.subject} into a bounded Philippines-based role brief with documented access, examples, review, and escalation.`}
}));
