export const september4CampaignDate = '2026-09-04' as const;
const image = '/philippines-team.jpg';

const blogDrafts = [
  ['offshore-order-cancellation-queue-controls', 'Offshore order cancellation queues: control the rush before fulfillment', 'A practical queue for stopping eligible orders without letting urgency bypass policy.', 'order status, fulfillment cutoff, payment state, and the customer request', 'warehouse release, refund approval, or a policy exception', 'the cancellation result, inventory state, payment outcome, and customer notice'],
  ['philippines-subscription-plan-change-support', 'Philippines subscription plan change support: keep billing effects visible', 'How a support specialist can prepare plan changes while pricing authority stays with the client.', 'current plan, billing date, entitlement, requested plan, and approved price table', 'credits, backdating, negotiated pricing, or eligibility exceptions', 'the saved plan, prorated amount, next invoice, entitlements, and confirmation'],
  ['offshore-property-maintenance-dispatch-triage', 'Offshore property maintenance dispatch: a safe triage workflow', 'Route tenant and site requests by documented urgency, access, and vendor rules.', 'property, unit, reported condition, occupants, access limits, and timestamp', 'safety classification, emergency authorization, spend, or return-to-use decisions', 'the dispatch record, vendor acceptance, access note, resolution evidence, and tenant update'],
  ['philippines-clinic-appointment-administration', 'Philippines clinic appointment administration: privacy-aware scheduling boundaries', 'Coordinate appointments and records without turning scheduling staff into clinical decision-makers.', 'patient identity fields, requested service, referral status, location, availability, and contact preference', 'clinical urgency, diagnosis, treatment, eligibility, or disclosure exceptions', 'the booked slot, permitted reminder, referral attachment, and handoff owner'],
  ['offshore-marketplace-seller-document-review', 'Offshore marketplace seller document review: an evidence-first intake', 'Prepare seller files for a consistent decision without quietly approving the merchant.', 'seller identity, entity record, marketplace category, submitted documents, and source timestamps', 'acceptance, sanctions disposition, risk rating, or an exception to marketplace policy', 'the document status, outstanding evidence, reviewer decision, and attributable notice'],
  ['philippines-travel-expense-precheck-workflow', 'Philippines travel expense prechecks: prepare claims without deciding policy', 'A repeatable way to check receipts, itinerary facts, and coding before manager approval.', 'traveler, trip purpose, dates, receipt, currency, expense category, and policy version', 'business-purpose judgment, exception approval, reimbursement, or tax treatment', 'the coded claim, exceptions, approval trail, payable status, and employee notice'],
  ['offshore-saas-user-access-request-queue', 'Offshore SaaS access request queues: least privilege from intake to closure', 'Turn access requests into reviewable packets with a named approver and revocation path.', 'requester identity, manager, system, role, business need, duration, and existing access', 'privileged access, conflicting duties, emergency grants, or risk acceptance', 'the account, effective permissions, approval reference, expiry, and audit record'],
  ['philippines-freight-document-exception-desk', 'Philippines freight document exception desks: keep shipment facts aligned', 'Resolve routine document gaps while logistics owners retain release and compliance decisions.', 'shipment reference, parties, route, carrier record, document version, dates, and declared quantities', 'cargo release, customs classification, legal interpretation, or financial guarantees', 'the corrected packet, carrier acknowledgment, unresolved variance, and next owner'],
  ['offshore-event-registration-support-process', 'Offshore event registration support: a clean attendee service process', 'Handle registrations, transfers, accessibility needs, and waitlists through one visible record.', 'attendee, ticket type, payment state, event rules, consent, and requested change', 'refund exceptions, complimentary access, safeguarding, or contractual commitments', 'the registration, badge data, payment result, accommodation handoff, and attendee message'],
  ['philippines-renewal-quote-data-preparation', 'Philippines renewal quote preparation: separate clean data from commercial judgment', 'Build a reliable renewal packet while account owners retain pricing and commitment authority.', 'account, contract dates, products, quantities, usage, approved price book, and open issues', 'discounts, term changes, concessions, forecast calls, or customer commitments', 'the source-backed draft, variances, approval, CRM record, and customer-ready version'],
  ['offshore-accounts-payable-duplicate-invoice-check', 'Offshore accounts payable duplicate invoice checks: find risk before posting', 'Compare invoice evidence across systems without deleting or rejecting a payable prematurely.', 'supplier, legal entity, invoice number, date, amount, currency, purchase order, and receipt', 'fraud conclusions, supplier disputes, posting, payment release, or write-off decisions', 'the candidate match, supporting links, reviewer disposition, ledger status, and supplier response'],
  ['philippines-product-return-intake-workflow', 'Philippines product return intake: a controlled path from request to receipt', 'Collect return evidence and keep refund, warranty, and disposition decisions with their owners.', 'customer, order, item, delivery record, stated reason, condition evidence, and policy version', 'eligibility exceptions, refund release, warranty judgment, or inventory disposition', 'the authorization, carrier event, received item, inspection handoff, refund state, and customer notice'],
] as const;

export const september4BlogPosts = blogDrafts.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 9, published: september4CampaignDate, image, citations: ['https://www.nist.gov/cyberframework', 'https://privacy.gov.ph/data-privacy-act/'] }));

export const september4BlogDetails = Object.fromEntries(blogDrafts.map(([slug, title, , inputs, decisions, closure]) => [slug, {
  keyTakeaways: [`Build the case from ${inputs}.`, `Send ${decisions} to a named client owner.`, `Close only after checking ${closure}.`],
  sections: [
    { title: 'Start with the actual request', body: `Open one case and record ${inputs}. Preserve what the requester supplied, including its time and channel, instead of rewriting the story into a cleaner version. Check the current approved source before touching a downstream system. If two records disagree, show the conflict and leave the item in an exception state. A Philippines-based specialist can assemble and compare the evidence, but should not fill an important gap from memory. This gives the next reviewer a record they can retrace without searching private messages.` },
    { title: 'Draw the authority line', body: `Routine preparation should have an explicit finish line. ${decisions.charAt(0).toUpperCase() + decisions.slice(1)} remain with the authorized client owner. Name that owner and a backup before the queue goes live. The specialist should send a bounded question with the relevant source links, impact, and next safe checkpoint. Silence is not approval, and an urgent request does not lower the evidence standard. Keeping this boundary visible protects the customer, the client, and the offshore teammate from improvised decisions.` },
    { title: 'Work from controlled systems', body: `Use named accounts and the least access that supports this workflow. Keep customer, employee, financial, or identity information inside approved fields; do not create a convenient shadow copy in personal storage. Record source versions, changes, approvals, and failed attempts when the systems allow it. The NIST Cybersecurity Framework is useful for organizing governance and access questions, while the Philippine Data Privacy Act provides the local accountability context for personal-information processing. Neither source decides the client's operating policy, so the role brief still needs concrete permissions and stop conditions.` },
    { title: 'Prove the outcome before closure', body: `Compare the approved action with ${closure}. Look for partial saves, duplicate actions, delayed integrations, and notices that no longer match the record. Preserve the earlier value and correction reason where the governing system supports history. If the result is incomplete, assign a next owner and checkpoint rather than labeling the case done. A closed item should tell a reviewer what arrived, what was permitted, what changed, who decided any exception, and what the requester was told.` },
    { title: 'Pilot a mixed sample', body: `Test ${title.toLowerCase()} with an ordinary case, missing evidence, conflicting sources, and one consequential exception. Ask two reviewers to identify the same permitted action and escalation point. Where they disagree, repair the instruction or example before adding volume. Review a small sample after launch, including returned and reopened cases. The sample describes the tested queue and period only; it is a management signal, not a promise of future accuracy or speed.` }
  ],
  internalLinks: [{ label: 'Plan an operations support role', href: '/services/operations-support', note: 'Turn the queue into a bounded role brief.' }, { label: 'Review the research library', href: '/research', note: 'Test the operating assumptions.' }],
  banners: [{ label: 'Scope checkpoint', title: 'Name the decision owner', body: 'Put permissions and exceptions in the role brief.', href: '/contact-us', linkText: 'Scope the role' }, { label: 'Pilot checkpoint', title: 'Review a mixed sample', body: 'Include routine work and a real exception.', href: '/contact-us', linkText: 'Plan the pilot' }, { label: 'Next step', title: 'Build an inspectable queue', body: 'Define the record, boundary, and finish line.', href: '/contact-us', linkText: 'Contact us' }],
  faqs: [{ question: 'What should the offshore role decide?', answer: 'Only routine actions expressly permitted in the current role brief. Material exceptions stay with the named client owner.' }, { question: 'What counts as complete?', answer: `Completion requires a check of ${closure}, plus a visible owner for anything unresolved.` }],
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'A risk-management framework for governance and access controls.' }, { name: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'The statutory context for accountable personal-information processing.' }]
}])) as Record<string, any>;

const researchSources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
  { name: 'International Labour Organization, Working anytime, anywhere', url: 'https://www.ilo.org/publications/working-anytime-anywhere-effects-world-work' }
];

const researchDrafts = [
  ['offshore-queue-reopen-rate-study', 'Offshore queue reopen rates: a cohort study for workflow quality', 'A method for separating premature closure from new information and policy change.', 'closed cases from one defined queue, closure reason, reopening time, actor, new evidence, and final disposition', 'premature closure, a genuinely new request, delayed system evidence, and a changed owner decision'],
  ['philippines-offshore-approval-wait-time-analysis', 'Philippines offshore approval wait time: an evidence-based analysis', 'Measure owner dependency without blaming the operator or treating every pause as waste.', 'request time, complete-packet time, decision owner, response time, reminders, decision, and downstream completion', 'operator preparation, owner waiting, system latency, rework, and work intentionally paused for control'],
  ['offshore-source-version-error-review', 'Offshore source-version errors: a reproducible review method', 'Test whether recurring work used the approved instruction in force when the action occurred.', 'case timestamps, cited source, source version, effective dates, retrieved copy, action, and reviewer result', 'retrieval mistakes, mislabeled libraries, ambiguous effective dates, and decisions made after the evidence changed'],
  ['philippines-shift-handoff-context-loss-study', 'Philippines shift handoff context loss: a controlled case review', 'Examine which facts disappear when work crosses shifts, channels, or ownership boundaries.', 'cases spanning a handoff, before-and-after records, customer commitments, open risks, new owner, and outcome', 'missing documentation, inaccessible evidence, contradictory updates, and later events that no handoff could contain'],
  ['offshore-exception-return-loop-analysis', 'Offshore exception return loops: finding why decision packets come back', 'A practical research design for incomplete packets, unclear questions, and unavailable owners.', 'submitted packets, required fields, evidence links, question wording, recipient, return reason, resubmission, and decision', 'missing facts, unclear authority, wrong routing, changed requirements, and a legitimate need for further investigation'],
] as const;

export const september4ResearchPosts = researchDrafts.map(([slug, title, excerpt, evidence, factors]) => ({
  slug, title, excerpt, published: september4CampaignDate, thumbnail: image, cluster: 'Workflow Design' as const,
  stats: ['Evidence window: one defined queue and review period', 'Interpretation separates workflow, system, source, and owner factors'],
  sections: [
    { heading: 'Research question and scope', body: `Can a defined offshore workflow produce an inspectable result when reviewers examine ${evidence}? State the queue, roles, policy version, review period, and unit of analysis before sampling. The study is about the tested process, not the general ability or trustworthiness of Filipino workers.` },
    { heading: 'Method', body: `Select a balanced cohort containing routine work and documented exceptions. Capture ${evidence}. Use system records where possible, minimize personal information, and redact working copies. Have a second reviewer apply the same definitions to a subset. Record disagreements rather than forcing consensus after seeing the outcome.` },
    { heading: 'Analysis and interpretation', body: `Separate ${factors}. Report counts with the cohort size and review window, and inspect the underlying cases before assigning a cause. A timing association does not prove that a person or location caused the result. NIST frameworks help organize governance, security, and privacy controls, but the client's written procedure supplies the operational pass rule.` },
    { heading: 'Decision use', body: `Use the findings to change one owned control: an intake field, source label, permission, routing rule, example, or review checkpoint. Keep consequential business decisions with the authorized client owner. Repeat the sample after the change using the same definitions, and retain unresolved cases instead of excluding them because they complicate the result.` },
    { heading: 'Limitations', body: `The evidence applies only to the sampled queue, period, systems, people, and rules. Small cohorts may miss rare exceptions, logging gaps may distort elapsed time, and reviewer knowledge can affect classification. The ILO source provides broad remote-work context; it does not establish performance for this organization. This method is an operating review, not a legal opinion, audit certification, or forecast of future results.` }
  ],
  sources: researchSources
}));
