export const september2CampaignDate = '2026-09-02';
const image = '/philippines-team.jpg';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Risk-management guidance for access and oversight.' },
  { name: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Accountability for personal-information processing.' },
  { name: 'Philippine National Privacy Commission, implementing rules', url: 'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/', note: 'Organizational, physical, and technical safeguards.' }
];

const blogs = [
  ['offshore-customer-refund-evidence-packet','Offshore customer refund evidence packets: a practical workflow','Prepare refund cases from the order, request, policy version, and approval trail.','order and payment records','refund approval and goodwill credits','transaction result and customer notice'],
  ['philippines-vendor-onboarding-document-check','Philippines vendor onboarding document checks: a controlled process','Turn supplier submissions into review-ready files without shifting vendor selection.','supplier, tax, banking, and contract documents','vendor acceptance and bank-change verification','review decisions and document versions'],
  ['offshore-inventory-discrepancy-triage-guide','Offshore inventory discrepancy triage: a source-first guide','Investigate stock mismatches before an authorized owner adjusts a balance.','item, location, quantity, timestamp, and movement records','inventory adjustment approval','reason code and corrected source balance'],
  ['philippines-insurance-claim-intake-support','Philippines insurance claim intake support: role boundaries and checks','Collect a complete claim notice while specialists retain coverage decisions.','policy reference, reported event, parties, and attachments','coverage, liability, and settlement judgment','handoff recipient, response, and next action'],
  ['offshore-ecommerce-catalog-change-control','Offshore ecommerce catalog change control: a publishing checklist','Publish approved product changes with preview, rollback, and live checks.','product, locale, channel, source fields, and effective time','pricing exceptions and regulated claims','prior value, release reference, and live result'],
  ['philippines-membership-renewal-support-playbook','Philippines membership renewal support: a service playbook','Handle routine renewals with verified accounts and clear pricing limits.','plan, renewal date, payment state, notices, and open cases','discounts, backdating, and eligibility exceptions','billing, access, and customer confirmation'],
  ['offshore-sales-demo-scheduling-workflow','Offshore sales demo scheduling: a clean handoff workflow','Coordinate demo requests without turning scheduling into deal authority.','requester, organization, time zone, product, and attendees','lead exceptions, pricing promises, and commitment dates','accepted agenda, reschedules, and account-owner handoff'],
  ['philippines-facilities-maintenance-request-triage','Philippines facilities maintenance request triage: an operations SOP','Route site requests by hazard, access, and service rules.','site, asset, reported condition, time, and restrictions','safety classification and return-to-use decisions','dispatch, work note, test, and reopening record'],
  ['offshore-legal-matter-billing-precheck','Offshore legal matter billing prechecks: an evidence routine','Prepare outside-counsel invoices without making legal or payment decisions.','matter, firm, period, rates, task codes, and expenses','legal necessity, privilege, and invoice approval','adjustments, firm response, and payable reference'],
  ['philippines-donor-record-update-procedure','Philippines donor record updates: a privacy-aware procedure','Maintain supporter records through verified requests and consent history.','trusted request, affected fields, and permitted evidence','identity merges, disputes, and consent exceptions','saved values, duplicate handling, and downstream lists'],
  ['offshore-training-session-administration','Offshore training session administration: from enrollment to records','Coordinate enrollment, course access, attendance, and completion records.','learner, course, cohort, prerequisites, and manager','waivers, protected content, and assessment disputes','attendance, completion evidence, and approved result'],
  ['philippines-warranty-registration-review','Philippines warranty registration review: a queue design guide','Validate product registration while policy owners retain eligibility decisions.','customer, product, purchase source, date, and receipt','late, transferred, altered, or unsupported products','saved registration, preference, and reference number']
] as const;

export const september2BlogPosts = blogs.map(([slug,title,excerpt]) => ({ slug, title, excerpt: `Published September 2, 2026. ${excerpt}`, minutes: 9, published: september2CampaignDate, image, citations: sources.slice(0,2).map(s=>s.url) }));
export const september2BlogDetails = Object.fromEntries(blogs.map(([slug,title,,inputs,boundary,closure]) => [slug, {
  keyTakeaways: [`Start with ${inputs}.`, `Route ${boundary} to a named client owner.`, `Verify ${closure} before closing the item.`],
  sections: [
    { title: 'Build the working record', body: `Collect ${inputs} in the approved system. Preserve the submitted wording and reporting timestamp. If a required source is missing or conflicts with another record, hold the item in a visible exception state instead of filling the gap from memory.` },
    { title: 'Keep authority with the owner', body: `The offshore specialist may prepare, compare, and route the routine work. ${boundary.charAt(0).toUpperCase()+boundary.slice(1)} remain with the named client owner. Record the question, evidence, recipient, and response so the queue does not hide a decision inside private messages.` },
    { title: 'Check the saved outcome', body: `Before closure, compare the approved action with ${closure}. Keep corrections attributable and retain the earlier value when the governing rule requires it. A completed task should show what changed, who authorized it, and what still needs attention.` },
    { title: 'Pilot the procedure', body: `Test ${title.toLowerCase()} with ordinary records, an incomplete input, and a consequential exception. Review the source version, permitted action, escalation, and final record before adding more volume.` }
  ],
  internalLinks: [{label:'Plan an operations support role',href:'/services/operations-support',note:'Turn the queue into a role brief.'},{label:'Read the research library',href:'/research',note:'Check the operating assumptions.'}],
  banners: [{label:'Scope checkpoint',title:'Name the decision owner',body:'Document where client authority begins.',href:'/contact-us',linkText:'Scope the role'},{label:'Pilot checkpoint',title:'Review a mixed sample',body:'Test routine work and exceptions.',href:'/contact-us',linkText:'Plan the pilot'},{label:'Next step',title:'Build a reviewable queue',body:'Convert the procedure into a staffing brief.',href:'/contact-us',linkText:'Contact us'}],
  faqs: [{question:'Where should the role stop?',answer:`The role should stop and escalate when the case requires ${boundary}.`},{question:'What proves the procedure works?',answer:`A reviewer can trace the source, permitted action, owner decision, and ${closure}.`}], sources
}])) as Record<string,any>;

const research = [
  ['offshore-work-queue-interruption-cost-study','Offshore work queue interruption cost: a measurement study','Measure switching, missing inputs, system failure, and owner waiting separately.','timestamped work intervals and interruption reasons','poor intake, unstable tools, or unclear ownership'],
  ['philippines-offshore-record-matching-accuracy-research','Philippines offshore record matching accuracy: a control study','Test whether staff link the right customer, invoice, order, or case.','redacted clear matches, near matches, duplicates, and missing identifiers','false matches and missed matches'],
  ['offshore-escalation-packet-completeness-analysis','Offshore escalation packet completeness: an operating analysis','Check whether decision owners receive enough evidence to answer.','required fields, attached sources, owner response, and return request','missing facts, owner delay, and genuine ambiguity'],
  ['philippines-offshore-role-permission-drift-review','Philippines offshore role permission drift: a review method','Find access that remains after tasks, clients, or responsibilities change.','identities, groups, actions, last use, grant owner, and task need','unused access, excess group rights, and unjustified administration'],
  ['offshore-service-recovery-handoff-evidence-study','Offshore service recovery handoff evidence: a case study method','Evaluate whether customer problems reach the right owner with context intact.','complaints, repeated contacts, failed remedies, promises, and outcomes','missing history, unsupported conclusions, and returned handoffs']
] as const;

export const september2ResearchPosts = research.map(([slug,title,excerpt,evidence,signals]) => ({ slug, title, excerpt: `Published September 2, 2026. ${excerpt}`, published: september2CampaignDate, thumbnail:image, cluster:'Workflow Design', stats:['Campaign publication: September 2, 2026','Evidence reviewed at the workflow level'], sections:[
  {heading:'Research question',body:`Can a defined offshore workflow produce a reliable result when the review focuses on ${evidence}? State the queue, period, decision boundary, and expected evidence before sampling.`},
  {heading:'Method',body:`Select representative routine work and exceptions. Record ${evidence}. Use redacted or synthetic material where possible, keep personal information out of the analysis log, and have a named reviewer apply the same rule to each case.`},
  {heading:'Interpretation',body:`Separate ${signals}. A count or elapsed-time result does not explain its cause on its own. Review the underlying cases and distinguish operator action from source, system, and client-owner dependencies.`},
  {heading:'Decision use and limits',body:`Use the findings to revise one documented control, then repeat the sample. The result applies only to the tested queue, period, sources, and rules. It does not prove future performance or justify broader access.`}
], sources }));
