export const september7CampaignDate = '2026-09-07' as const;
const image = '/philippines-team.jpg';
const blogs = [
['offshore-customer-refund-evidence-pack','Offshore customer refund evidence packs: give approvers the full picture','Prepare refund requests without moving financial authority into the support queue.','order record, payment state, delivery evidence, policy version, and earlier contacts','eligibility exceptions, refund release, goodwill amounts, and suspected fraud','approved amount, processor result, ledger entry, customer notice, and remaining owner'],
['philippines-vendor-onboarding-document-desk','Philippines vendor onboarding desks: organize the file before approval','Gather supplier evidence while procurement and compliance owners retain decisions.','supplier identity, entity details, tax forms, payment instructions, service scope, and source dates','vendor approval, risk acceptance, contract terms, and bank-detail exceptions','reviewed file, decision, system record, access state, and supplier message'],
['offshore-insurance-claim-intake-support','Offshore insurance claim intake: keep facts separate from coverage decisions','Build a careful intake lane that records the loss without promising an outcome.','claimant identity, policy reference, event time, reported facts, documents, and consent','coverage, liability, reserves, settlement, urgency, and legal interpretation','claim record, document inventory, assigned adjuster, acknowledgment, and open questions'],
['philippines-ecommerce-catalog-change-control','Philippines ecommerce catalog updates: a controlled publishing workflow','Prepare product changes from approved sources and catch mismatches before publication.','SKU, approved copy, price source, inventory rule, images, market, and effective time','pricing exceptions, regulated claims, launch timing, and unapproved substitutions','live page, price, variant mapping, image, mobile view, timestamp, and rollback record'],
['offshore-purchase-order-change-queue','Offshore purchase-order changes: preserve approval history from request to ERP','Prepare PO amendments without hiding commercial decisions.','purchase order, supplier, requested change, budget code, receipt status, and contract reference','spend approval, scope acceptance, supplier commitment, and retrospective authorization','approved revision, ERP value, supplier acknowledgment, receiving record, and exception owner'],
['philippines-membership-renewal-support','Philippines membership renewal support: make consent and billing status clear','Handle routine renewals while exceptions and payment decisions stay with named owners.','member identity, plan, renewal date, consent record, payment status, and benefits','waivers, refunds, disputed consent, negotiated terms, and eligibility exceptions','renewed term, receipt, benefit state, failed-payment path, and member confirmation'],
['offshore-logistics-delivery-proof-review','Offshore proof-of-delivery review: resolve document gaps before invoicing','A repeatable evidence check for delivery records, signatures, quantities, and exceptions.','shipment ID, carrier event, delivery time, recipient evidence, quantities, and damage notes','claim liability, invoice release, write-offs, concessions, and authenticity disputes','matched delivery, discrepancy record, reviewer decision, invoice state, and notices'],
['philippines-employee-onboarding-coordination','Philippines employee onboarding coordination: one accountable readiness record','Coordinate people, equipment, access, and training without turning checklists into HR judgment.','approved hire, start date, location, role, manager, systems, equipment, and training','employment terms, accommodations, background disposition, privileged access, and exceptions','account state, equipment receipt, orientation, missing-item owner, and manager acknowledgment'],
['offshore-saas-trial-conversion-administration','Offshore SaaS trial conversions: protect the handoff from product use to billing','Prepare conversion records with visible entitlement, consent, pricing, and approvals.','account, trial dates, usage, requested plan, approved price, billing contact, and consent','discounts, contract language, credit decisions, backdating, and commitments','subscription, entitlements, invoice schedule, CRM record, confirmation, and exceptions'],
['philippines-real-estate-listing-qa','Philippines real estate listing QA: verify the record before publication','A source-first review for addresses, features, media, availability, and disclosures.','property ID, authorized source, address, price, availability, features, media rights, and disclosures','valuation, legal sufficiency, language decisions, offers, and publication exceptions','published listing, mobile rendering, source match, timestamp, correction path, and signoff'],
['offshore-donation-processing-reconciliation','Offshore donation reconciliation: connect the gift, receipt, and ledger','Match donation records without making tax or refund judgments.','donor record, transaction ID, amount, currency, campaign, restriction, processor status, and time','tax treatment, restriction acceptance, refunds, chargebacks, and donor-intent exceptions','CRM gift, ledger batch, receipt, variance queue, correction approval, and donor message'],
['philippines-technical-support-bug-escalation','Philippines technical support bug escalation: turn reports into reproducible evidence','Help engineers act by capturing the environment, steps, impact, and safe diagnostics.','account, product version, environment, timestamps, steps, expected result, logs, and consent','security severity, root cause, roadmap promises, data repair, and production changes','reproducible case, redacted evidence, engineering owner, workaround, update, and closure test'],
] as const;
const blogSources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and access-control context.'},{name:'Philippine National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Philippine privacy-accountability context.'}];
export const september7BlogPosts=blogs.map(([slug,title,excerpt])=>({slug,title,excerpt,minutes:9,published:september7CampaignDate,image,citations:blogSources.map(s=>s.url)}));
export const september7BlogDetails=Object.fromEntries(blogs.map(([slug,title,,inputs,decisions,closure])=>[slug,{
 keyTakeaways:['Build the record from '+inputs+'.','Route '+decisions+' to the named client owner.','Close only after checking the '+closure+'.'],
 sections:[
 {title:'Open one traceable case',body:'Start with '+inputs+'. Keep the request in the approved case system and preserve its source and time. Compare identifiers before merging records. When sources disagree, describe the mismatch and pause the affected step. A Philippines-based specialist can assemble evidence, but should never replace a missing fact with a likely answer. This gives the reviewer a usable record instead of a polished story that cannot be retraced.'},
 {title:'Write the decision boundary into the queue',body:decisions.charAt(0).toUpperCase()+decisions.slice(1)+' stay with an authorized client owner. Name that owner and a backup, then state what the coordinator may do while waiting. A useful escalation contains the decision requested, relevant evidence, deadline, and safest checkpoint. Urgency does not create permission, and silence is not approval.'},
 {title:'Use controlled access and current sources',body:'Give each worker an individual account and only the fields needed. Keep personal, financial, and identity information inside approved systems. Record the source version, action, actor, and approval. NIST CSF 2.0 helps organize governance and access questions, while the Philippine Data Privacy Act supplies local privacy context. The client procedure must still define the pass rule.'},
 {title:'Check the downstream result',body:'Before closure, compare the authorized action with the '+closure+'. Look for partial saves, delayed integrations, duplicates, stale messages, and records that changed after approval. If the result is incomplete, leave a named owner and review time. The audit trail should show what arrived, what was allowed, what changed, who decided an exception, and what the requester was told.'},
 {title:'Pilot ordinary and awkward cases',body:'Test '+title.toLowerCase()+' with a routine request, a missing field, conflicting evidence, and one material exception. Ask two reviewers to identify the same permitted action and escalation point. Repair instructions where they disagree. Review a mixed sample after launch and retain reopened cases. Results describe only that queue, period, systems, and sample; they are not a forecast.'}],
 internalLinks:[{label:'Plan an operations support role',href:'/services/operations-support',note:'Turn the queue into a bounded role brief.'},{label:'Review the research library',href:'/research',note:'Test the operating assumptions.'}],
 banners:[{label:'Scope checkpoint',title:'Name the decision owner',body:'Put permissions and stop conditions in writing.',href:'/contact-us',linkText:'Scope the role'},{label:'Pilot checkpoint',title:'Test a mixed sample',body:'Include routine work and exceptions.',href:'/contact-us',linkText:'Plan the pilot'},{label:'Next step',title:'Build an inspectable queue',body:'Define the record, boundary, and finish line.',href:'/contact-us',linkText:'Contact us'}],
 faqs:[{question:'What should the offshore specialist decide?',answer:'Only routine actions explicitly permitted by the role brief. Material exceptions stay with the named client owner.'},{question:'What counts as complete?',answer:'Completion requires a check of the '+closure+', plus a visible owner for anything unresolved.'}],sources:blogSources
}])) as Record<string,any>;

const researchSources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'Philippine National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'International Labour Organization, Working anytime, anywhere',url:'https://www.ilo.org/publications/working-anytime-anywhere-effects-world-work'}];
const studies=[
['offshore-queue-aging-distribution-study','Offshore queue aging distributions: look beyond the average','A cohort method for finding stalled work without treating unlike cases as equivalent.','case-open time, ready time, status changes, dependency owner, completion time, and reopens','active work, approval waits, source gaps, system holds, and deferred cases'],
['philippines-offshore-instruction-drift-review','Philippines offshore instruction drift: testing whether the live queue matches the SOP','A reproducible review of written procedures, local habits, and system prompts.','effective SOP versions, prompts, training examples, sampled cases, actions, and outcomes','outdated instructions, undocumented workarounds, ambiguity, access constraints, and approved changes'],
['offshore-first-pass-yield-analysis','Offshore first-pass yield: measuring usable completions without hiding rework','Define a fair denominator and separate operator corrections from changed requirements.','submitted cases, completeness rule, review result, return reason, resubmission, and final disposition','operator error, missing evidence, reviewer disagreement, system failure, and changed requirements'],
['philippines-offshore-escalation-routing-study','Philippines offshore escalation routing: a case study of ownership clarity','Test whether exceptions reach someone with authority before commitments are missed.','exception type, detection time, routing rule, recipients, acknowledgments, authority, and decision','wrong routing, unavailable owners, incomplete packets, ambiguous authority, and execution delay'],
['offshore-quality-sample-selection-review','Offshore quality sampling: checking whether the review set represents the queue','A transparent method for balancing routine work, exceptions, shifts, and consequential cases.','queue population, case types, shifts, workers, risk flags, sampling rule, exclusions, and results','random variation, oversampling, excluded failures, reviewer knowledge, small groups, and missing logs'],
] as const;
export const september7ResearchPosts=studies.map(([slug,title,excerpt,evidence,factors])=>({slug,title,excerpt,published:september7CampaignDate,thumbnail:image,cluster:'Workflow Design' as const,stats:['Scope: one defined queue and review window','Interpretation separates workflow, source, system, and owner factors'],sections:[
{heading:'Question and scope',body:'Can reviewers reach a consistent finding from '+evidence+'? Define the queue, roles, policy version, period, and unit before sampling. This study concerns one operating process, not the general ability or trustworthiness of Filipino professionals.'},
{heading:'Method',body:'Select a documented cohort containing routine cases and exceptions. Capture '+evidence+'. Prefer system records, minimize personal information, and redact working copies. Have a second reviewer classify a subset with the same definitions. Preserve disagreements so apparent precision does not hide an unclear rule.'},
{heading:'Analysis',body:'Separate '+factors+'. Report every rate with its numerator, denominator, window, and exclusions. Inspect cases before assigning cause; association alone does not establish causation. NIST frameworks organize control questions, but the client procedure supplies the operational pass condition.'},
{heading:'Decision use',body:'Change one owned control: an intake field, source label, permission, routing rule, example, or review checkpoint. Keep consequential decisions with the authorized client owner. Repeat the sample under the same definitions and keep unresolved cases visible.'},
{heading:'Scope and limitations',body:'Findings apply only to the sampled queue, period, systems, people, and rules. Small cohorts can miss rare exceptions, missing logs can distort measures, and reviewer knowledge can affect classification. The ILO source offers broad context; it does not establish company performance. This is an operating review, not legal advice, an audit opinion, or a forecast.'}],sources:researchSources}));
