import type { ResearchPost } from './fleet-data';
import { buildResearchSections, type ResearchStudyTopic } from './campaign-2026-09-18-research';

export const september25ResearchDate = '2026-09-25';

const sources = [
  {name:'NIST: Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST: CSF 2.0 Quick-Start Guides',url:'https://www.nist.gov/cyberframework/quick-start-guides'},
  {name:'NIST: SP 800-53 Rev. 5 Security and Privacy Controls',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'NIST: SP 800-171 Rev. 3',url:'https://csrc.nist.gov/pubs/sp/800/171/r3/final'},
  {name:'CISA: Cybersecurity Performance Goals',url:'https://www.cisa.gov/cyber-guidance/cybersecurity-performance-goals'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippine National Privacy Commission: Implementing Rules and Regulations',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
  {name:'Philippine National Privacy Commission: Advisories and Circulars',url:'https://privacy.gov.ph/pips-and-pics/advisories-circulars/'},
  {name:'U.S. GAO: Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/products/gao-14-704g'},
  {name:'U.S. Department of Labor: Protecting Temporary Workers',url:'https://www.osha.gov/temporaryworkers'}
] as const;

const topics: readonly ResearchStudyTopic[] = [
  {slug:'philippines-saas-access-request-evidence-completeness-study',title:'SaaS Access-Request Evidence Completeness in Philippines Operations Support',excerpt:'A bounded study for testing whether user-access requests reach system owners with complete evidence while entitlement decisions remain client-owned.',subject:'SaaS access-request evidence completeness',population:'new-user, role-change, temporary-access, privileged-access, reinstatement, extension, and removal requests across approved business applications during one review period',fields:'requester, worker identity, employment state, business purpose, requested role, system, data class, start and end dates, approver, segregation conflict, fulfillment actor, and verification result',errors:'missing business purpose, wrong approver, excess role scope, absent expiry, identity mismatch, unresolved segregation conflict, shared-account requests, fulfillment before approval, and closure without verification',owner:'application owner, security owner, or designated access approver',reserved:'approve an entitlement, waive segregation rules, create a shared account, grant privileged access, extend an exception, or accept residual security risk',service:'/services/shared-services-administration',label:'Explore Shared Services Administration'},
  {slug:'offshore-customer-cancellation-instruction-fidelity-research',title:'Customer Cancellation-Instruction Fidelity in Offshore Support',excerpt:'A source-backed method for checking whether cancellation requests preserve the customer’s words, identity checks, and policy route without inventing retention authority.',subject:'customer cancellation-instruction fidelity',population:'immediate cancellations, end-of-term requests, partial cancellations, account closures, cooling-off inquiries, failed-verification contacts, retention offers, and disputed completion records from defined channels',fields:'customer statement, channel, receipt time, verified identity, account, product or service, requested effective date, policy version, permitted response, offer status, owner decision, and confirmation evidence',errors:'changed intent, missed dates, unsupported retention claims, cancellation barriers, incomplete identity checks, premature closure, unapproved promises, missing confirmations, and records that conceal repeat contact',owner:'customer-experience, subscription-policy, legal, or designated account owner',reserved:'interpret a statutory right, deny cancellation, create a retention offer, waive a charge, set an effective date outside policy, admit liability, or close a disputed request',service:'/services/customer-experience-support',label:'Explore Customer Experience Support'},
  {slug:'philippines-bank-reconciliation-exception-provenance-study',title:'Bank-Reconciliation Exception Provenance in Philippines Finance Support',excerpt:'A practical research design for deciding whether reconciliation exceptions can be reconstructed without moving accounting judgment into a support role.',subject:'bank-reconciliation exception provenance',population:'unmatched deposits, outstanding payments, bank fees, timing differences, reversals, duplicated lines, stale items, and returned reviewer questions for one account set and period',fields:'account, statement date, transaction identifier, amount, currency, ledger reference, proposed match, source document, exception reason, age, preparer, reviewer, owner response, and final state',errors:'unsupported matches, duplicated clearing, wrong-period treatment, hidden stale items, missing source documents, altered descriptions, unexplained write-offs, unapproved entries, and closure before reviewer acceptance',owner:'controller, treasury manager, or designated reconciliation reviewer',reserved:'approve a journal entry, determine accounting treatment, write off a balance, classify fraud, alter a bank record, certify cash, or close an unresolved exception',service:'/services/finance-operations-support',label:'Explore Finance Operations Support'},
  {slug:'offshore-marketing-suppression-list-change-evidence-research',title:'Marketing Suppression-List Change Evidence in Offshore Operations',excerpt:'A privacy-aware model for studying whether suppression changes are attributable and complete while consent and legal interpretation remain with the client.',subject:'marketing suppression-list change evidence',population:'unsubscribe events, manual suppressions, complaint-driven suppressions, corrected addresses, re-permission records, channel-specific choices, imports, merges, and synchronization exceptions during a stated window',fields:'contact identifier, channel, source event, event time, requested preference, prior state, new state, governing rule, actor, downstream systems, synchronization result, exception, and reviewer',errors:'lost unsubscribe events, wrong-channel changes, resubscription without evidence, stale downstream lists, identity collisions, overwritten timestamps, incomplete imports, undocumented manual overrides, and exposure of unnecessary personal data',owner:'privacy, legal, marketing-operations, or designated consent-policy owner',reserved:'interpret consent law, declare a lawful basis, reverse a suppression, approve a campaign audience, resolve a disputed identity, or decide whether a message may be sent',service:'/services/marketing-operations-support',label:'Explore Marketing Operations Support'},
  {slug:'philippines-project-change-request-dependency-study',title:'Project Change-Request Dependency Mapping in Philippines Coordination Support',excerpt:'A decision-grade study for checking whether proposed changes reach owners with visible dependencies, evidence, and boundaries before approval.',subject:'project change-request dependency mapping',population:'scope, schedule, resource, vendor, technical, security, budget, and cancellation changes submitted, returned, withdrawn, or decided during one project review period',fields:'request identifier, requester, baseline reference, proposed change, stated reason, affected deliverables, dependencies, assumptions, cost or schedule estimate source, risks, required owners, questions, decision, and implementation state',errors:'missing baseline, hidden dependencies, double-counted impacts, unsupported estimates, wrong decision owner, implementation before approval, lost rejected requests, scope changes disguised as status updates, and closure without downstream confirmation',owner:'project sponsor, product owner, budget owner, or designated change authority',reserved:'approve scope, commit budget, accept risk, change a contract, promise a delivery date, prioritize work, or authorize implementation',service:'/services/project-coordination-support',label:'Explore Project Coordination Support'}
];

export const september25ResearchPosts: readonly ResearchPost[] = topics.map((topic, index) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  published: september25ResearchDate,
  thumbnail: '/research/research-default.svg',
  cluster: index === 0 || index === 3 ? 'Hiring Controls' : index === 2 ? 'Scope Benchmarks' : 'Workflow Design',
  stats: ['Primary measure: evidence-complete, boundary-correct disposition', 'Sources and operating assumptions checked September 25, 2026'],
  sections: buildResearchSections(topic),
  sources,
  serviceHandoff: {href:topic.service,label:topic.label,body:`Turn the findings on ${topic.subject} into a bounded Philippines-based role brief with documented access, examples, review, and escalation.`}
}));
