import type { ResearchPost } from './fleet-data';

// Provisional only. OFFAA-85 must reconcile this to the actual first-publication
// date in UTC immediately before the sole combined production push.
export const october5ResearchDate = '2026-10-06';

export const october5ResearchPosts: readonly ResearchPost[] = [
  {
    slug: 'supplier-scorecard-evidence-reliability-research',
    title: 'Supplier Scorecard Evidence Reliability in Offshore Procurement Administration',
    excerpt: 'A field-level method for deciding whether supplier scorecards support procurement review without turning administrative support into vendor judgment.',
    published: october5ResearchDate,
    thumbnail: '/research/research-default.svg',
    cluster: 'Workflow Design',
    stats: ['Primary measure: decision-ready supplier observations', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/procurement-administration', label: 'Explore Procurement Administration', body: 'Build a bounded procurement administration workflow with named evidence, approval limits, and client-side review.' },
    sources: [
      { name: 'GAO Standards for Internal Control in the Federal Government (2025)', url: 'https://www.gao.gov/greenbook' },
      { name: 'NIST SP 800-161 Rev. 1: Cybersecurity Supply Chain Risk Management Practices', url: 'https://csrc.nist.gov/pubs/sp/800/161/r1/final' }
    ],
    sections: [
      { heading: 'Finding and decision boundary', body: `A supplier scorecard is useful only when a reviewer can reconstruct what was observed, which obligation or operating expectation it relates to, who evaluated it, and what decision followed. A polished red-amber-green summary does not supply that chain by itself. For an offshore procurement administration role, the defensible contribution is evidence preparation: maintaining the supplier population, linking observations to approved records, checking required fields, routing discrepancies, and preserving owner decisions. Supplier selection, risk acceptance, contract interpretation, remediation demands, and commercial consequences remain with authorized client owners. The GAO Green Book describes principles for quality information, responsibility, monitoring, and corrective action in a federal internal-control context. NIST SP 800-161 discusses supply-chain risk practices across the lifecycle. This study uses both as control-design references; neither mandates a private company's scorecard, proves a supplier is safe, or substitutes for legal, security, procurement, or operational judgment. The practical research question is narrower: can a bounded record make a supplier observation decision-ready without hiding uncertainty or transferring authority to the person assembling it?` },
      { heading: 'Build the scorecard population before choosing metrics', body: `Start with the supplier universe, not the vendors easiest to measure. Reconcile approved supplier, contract, purchase-order, accounts-payable, security-review, service-owner, and incident sources for a declared business unit and observation period. Retain stable supplier and agreement identifiers alongside display names so acquisitions, resellers, affiliates, and duplicate records do not collapse silently. Include active suppliers, paused relationships with continuing obligations, subcontractors visible through approved records, and terminated suppliers with open credits, data-return work, or unresolved corrective actions. Record the source and extraction time for every population member. Then define the unit of assessment: legal entity, contracted service, location, product, or engagement. Mixing those units makes a score uninterpretable because one supplier can perform differently across services. Missing ownership, inaccessible agreements, and conflicting names are findings to route, not permission to invent a match. The administrator should reference permissioned systems rather than copying contracts, personal data, security evidence, or confidential pricing into a parallel spreadsheet. A population completeness measure needs a denominator and explicit exclusions; a high completion percentage over an incomplete vendor list is false reassurance.` },
      { heading: 'Translate observations into traceable evidence', body: `Each scorecard field needs a definition, evidence source, observation window, permissible status, and accountable reviewer. Delivery timeliness might derive from accepted receipt against an agreed milestone, not the date an invoice arrived. Quality might concern documented returns or acceptance exceptions, not an operator's impression. Responsiveness should distinguish supplier response time from time waiting for the client's clarification. Security, privacy, continuity, or financial-risk fields should point to the qualified owner's current assessment rather than asking an administrative analyst to recreate it. Preserve numerator, denominator, timezone, cut-off, exclusions, and late-arriving corrections behind any rate. Free-text comments should identify a dated event and source, avoiding character judgments and unsupported causal claims. When records conflict, retain the conflict and send a precise question to the owner. Facts are source values and observable events. Analysis is the declared transformation of those facts under the rubric. An explanation offered by a supplier or stakeholder remains an attributed statement until confirmed. A forecast, causal account, or recommended consequence is an inference or decision, not a fact. This separation lets a reviewer correct the evidence without rewriting history.` },
      { heading: 'Method for a bounded reliability test', body: `Freeze the population, period, definitions, and source hierarchy before reading final ratings. Select a stratified sample that includes high-spend and low-spend engagements, new and long-running relationships, ordinary performance, exceptions, missing records, and supplier-name changes. A preparer assembles evidence while a second reviewer independently reconstructs an overlap sample from authorized sources. Compare whether both reviewers identify the same event, denominator, obligation, status, and unresolved question. Preserve their first classifications before calibration so disagreement remains measurable. Trace a subset in both directions: from scorecard statement back to source, and from source exception forward to the scorecard and owner response. Test cut-off behavior with a correction received after the period, an invoice disputed for reasons unrelated to performance, and a milestone changed through an approved amendment. The protocol should also include a supplier with no events; zero exceptions must not automatically become perfect performance when required evidence is absent. Report field-level agreement, untraceable claims, missing denominators, stale owner assessments, unmatched suppliers, and corrections after review. Do not blend these defects into one average that conceals why a record failed.` },
      { heading: 'Interpretation without automatic vendor ranking', body: `A score is a compressed description of selected observations, not a complete supplier judgment. A low on-time rate can reflect supplier delay, an unrealistic baseline, a client approval hold, disputed event timestamps, or a changed scope. A high rate can coexist with severe but infrequent failures. Weighting several fields creates an additional management choice: it does not arise objectively from the data. Accordingly, show material components and exceptions beside any aggregate. Compare like periods only when definitions and source coverage remained stable; otherwise mark the break and avoid a trend claim. Never infer that missing incidents prove absence of incidents, or that a completed questionnaire proves operating effectiveness. Reviewers should examine contrary cases, severity, concentration, and exposure as well as counts. The output can support decisions to request clarification, repair data, narrow an engagement, perform qualified review, or monitor a corrective action. It cannot on its own establish breach, compliance, financial viability, cybersecurity posture, or suitability for future work. If a threshold triggers an action, record who approved that rule, when it took effect, what exceptions are allowed, and which owner may override it.` },
      { heading: 'Operational workflow and authority controls', body: `The working instruction should name approved systems, required fields, source precedence, access limits, cut-off rules, reviewer assignments, escalation paths, and retention treatment. The offshore administrator may reconcile supplier identifiers, prepare evidence links, calculate preapproved measures, flag missing inputs, distribute review packets, record authorized dispositions, and follow up on due dates. The role must not negotiate, amend terms, accuse a supplier, accept risk, approve payment, assign contractual fault, decide termination, or alter a rating to reach a desired outcome. Conflicting instructions place the item on a visible hold with a named client owner. Use named accounts and least access; do not export unrestricted supplier, bank, personnel, or security data merely for convenience. Version definitions and scorecard logic, retaining effective dates so earlier results remain understandable. Corrections should preserve the original observation, reason, approver, time, and recalculated result. A completed administrative task is not a completed corrective action: closure needs the agreed evidence and authorized acceptance. These controls make the workflow scalable while keeping consequential supplier decisions where the client intended them to remain.` },
      { heading: 'Failure modes and challenge cases', body: `Test the design against cases likely to defeat a neat spreadsheet. One supplier uses two legal entities; another invoices through a reseller; a third changes product name without changing the agreement. A delivery is accepted after the client delayed access. A credit note arrives after period close. A severe security concern is restricted to a qualified reviewer, so the preparer can see only a current status and owner. A contract renewal overlaps an unresolved corrective action. An owner asks for a green rating despite missing evidence. For each case, require the record to preserve identity, scope, source, dates, uncertainty, authority, and next action without disclosing restricted material. Include one fully ordinary record to ensure reviewers do not manufacture exceptions. Exercise absence coverage, reassignment, correction, and rollback of an erroneous match. Confirm that a late source update changes the appropriate period under an approved rule rather than through silent editing. If two reviewers repeatedly disagree on a field, revise the definition or source hierarchy before scaling. If the necessary source cannot be accessed lawfully or reliably, mark the field unavailable and route it; do not replace it with intuition.` },
      { heading: 'Measures, limitations, and reader outcome', body: `Useful measures include population reconciliation rate, fields supported by current evidence, reviewer agreement by field, observations returned for clarification, unmatched supplier identities, late corrections, overdue owner decisions, reopened actions, and closure verified against the agreed record. Report counts with denominators and exclusions. Segment defects by population, source, definition, preparation, review, and implementation so managers can repair the right part of the process. This documentary study cannot establish that every supplier, incident, obligation, subcontractor, or operational event was discovered. Source systems may be delayed or incomplete; restricted evidence may be summarized; samples can miss rare failures; and relationships can change after the cut-off. Public control frameworks do not validate this particular workflow or provide a universal acceptable score. Findings from one service, period, or client cannot be generalized to other suppliers, countries, or future performance. The reader should receive a declared population, field dictionary, source map, sample method, disagreement record, exceptions, owner dispositions, limitations, and corrective-action register. That package supports a reasoned choice to pilot, repair sources, narrow the scorecard, obtain specialist review, or stop. Its value is not a colorful ranking. Its value is a reproducible path from a supplier observation to an accountable client decision.` }
    ]
  },
  {
    slug: 'customer-commitment-register-accuracy-research',
    title: 'Customer Commitment Register Accuracy in Offshore Experience Support',
    excerpt: 'A documentary method for testing whether promised customer actions remain accurate, owned, and reviewable across support channels.',
    published: october5ResearchDate,
    thumbnail: '/research/research-default.svg',
    cluster: 'Customer Experience',
    stats: ['Primary measure: reconstructable open commitments', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/customer-experience-support', label: 'Explore Customer Experience Support', body: 'Build a customer support workflow with bounded authority, traceable commitments, and client-side exception ownership.' },
    sources: [
      { name: 'FTC: Solving Problems With a Business—Returns, Refunds, and Other Resolutions', url: 'https://consumer.ftc.gov/articles/solving-problems-business-returns-refunds-and-other-resolutions' },
      { name: 'FTC: Warranties', url: 'https://consumer.ftc.gov/articles/warranties' }
    ],
    sections: [
      { heading: 'Research finding: a promise is a governed record', body: `A customer commitment register should answer five questions without relying on an agent's memory: what the business represented it would do, who was authorized to make that representation, what conditions applied, when the next event was due, and what evidence shows fulfillment or a properly approved change. The register is not a second customer relationship management system and should not become a place where offshore support staff invent remedies. Its purpose is continuity across email, chat, telephone notes, tickets, returns systems, finance queues, and internal handoffs. FTC consumer guidance recommends keeping records and explains that written warranties and stated return or resolution terms matter; it does not define one workflow for every business or resolve a particular dispute. This study therefore tests documentary accuracy rather than legal compliance or customer satisfaction. The central finding is that a commitment becomes operationally reliable only when its exact scope, authority, dependencies, state transitions, and closure evidence remain linked. A generic note such as follow up soon can look reassuring while leaving the next operator unable to act. A precise entry can still be wrong if it contradicts approved policy, omits a condition, or silently changes after the customer relied on it.` },
      { heading: 'Define the population from customer-facing evidence', body: `Begin with a declared period, channel set, product or service boundary, and definition of commitment. Include explicit promises to refund, replace, call back, investigate, provide a document, correct an account, apply a credit, escalate, or respond by a stated time. Include conditional representations when the condition can create a reasonable expectation, such as a refund after receipt and inspection. Exclude greetings, aspirations, automated estimates clearly identified as estimates, and internal tasks never communicated to a customer, but retain the rules behind each exclusion. Build the population from customer-facing messages and recorded call dispositions, then reconcile it against tickets, return authorizations, payment events, shipment records, and escalation queues. Starting only from an existing commitment field will miss promises recorded in free text or made in another channel. Preserve the original wording or a permissioned reference, channel, timestamp, timezone, customer and case identifiers, speaker, authority basis, promised action, due event, conditions, dependency, responsible owner, and current status. Minimize personal and payment data; the register needs a stable reference, not an uncontrolled copy of the entire conversation. If identity matching is uncertain, route the ambiguity instead of joining records by a similar name.` },
      { heading: 'Accuracy protocol and state reconstruction', body: `Freeze the source hierarchy and state definitions before examining outcomes. Suggested states are proposed, authorized, communicated, waiting on customer, waiting on business owner, in execution, fulfilled, superseded with approval, withdrawn with approval, disputed, and unresolved. These states describe evidence, not whether the customer is right. Select a stratified sample containing ordinary cases, high-value remedies, multiple channels, language transfers, reopened tickets, staff changes, deadline commitments, conditional offers, and records marked closed. One reviewer reconstructs the commitment only from authoritative records; a second independently repeats an overlap sample. Compare the exact action, amount or item where applicable, due trigger, deadline, condition, owner, and status. Preserve initial disagreements. Trace forward from the customer-facing statement to execution evidence and backward from refunds, replacements, or callbacks to the statement and authorization that initiated them. Test events arriving out of order and systems that store only date rather than time. A closed ticket is not fulfillment evidence, and a payment request is not a completed refund. Record unavailable evidence as unavailable. Do not infer consent from silence, authority from job title, or completion from elapsed time.` },
      { heading: 'Separate fact, analysis, inference, and decision', body: `Facts include the words communicated, approved policy version, authorization record, system timestamp, delivery scan, refund settlement, and dated owner response. Analysis maps those facts to a predeclared state and identifies gaps. Inference includes explanations for delay, likely customer expectations, or whether two differently worded messages refer to the same promise. Decisions include granting an exception, changing a deadline, offering compensation, interpreting warranty scope, accepting financial or legal exposure, and closing a dispute. The offshore support analyst may prepare facts and analysis but must label uncertainty and send decisions to authorized owners. This separation is especially important when a friendly phrase can be read as an unconditional promise, when policy changed between purchase and contact, or when a supervisor approved a remedy in private chat. Preserve the applicable policy and approval evidence available at the time; do not overwrite the earlier record with today's rule. If later information corrects a factual error, append a correction with its source and time. If the business changes its intended action, record who authorized the change and what customer communication followed. A register that silently edits the original commitment prevents both operational learning and fair review.` },
      { heading: 'Authority and escalation design', body: `A bounded customer experience support role can identify candidate commitments, enter approved fields, check due items, request missing evidence, prepare status updates from source records, and route exceptions. It should not promise a refund, warranty remedy, credit, delivery date, legal outcome, investigation result, policy exception, or compensation beyond explicitly delegated limits. It should not reinterpret ambiguous terms, suppress an overdue item, or change a commitment merely to make a service target appear met. The client instruction must name permissible representations, monetary and nonmonetary approval limits, policy sources, protected data rules, approved channels, timezones, escalation owners, absence coverage, and emergency paths. Conflicting instructions create a visible hold. A customer message can be acknowledged without inventing an answer; the record should distinguish acknowledgement from resolution. Sensitive allegations, threats, safety issues, chargebacks, accessibility needs, privacy requests, and legal notices follow qualified routes rather than the ordinary queue. Access should be limited to the fields and systems needed. Review exports should redact unnecessary content and follow the client's retention rules. These boundaries protect customers while preventing evidence administration from drifting into unapproved commercial judgment.` },
      { heading: 'Challenge cases that expose weak registers', body: `Use a pilot set designed to break simple due-date tracking. A representative says the team will call tomorrow but the customer's timezone differs. A replacement is promised after return receipt, yet the carrier scan and warehouse receipt disagree. A supervisor authorizes a partial refund while a public return policy appears broader. Two agents make incompatible commitments in different channels. An automated message gives an estimate after a human promised a fixed date. A refund is approved but fails at the payment processor. A warranty question depends on product and purchase records the support team cannot interpret. A customer withdraws a request after work has begun. For each case, require the record to preserve original words, applicable authority, condition, clock, ownership, later communication, and final evidence. Include ordinary fulfilled commitments so reviewers do not assume every sampled item is defective. Exercise reassignment during absence and confirm the due item stays visible. Reopen a supposedly closed case when settlement fails. Test whether a customer reply after closure reconnects to the prior commitment rather than starting without context. If the workflow cannot represent one of these cases without misleading simplification, repair its state model before scaling.` },
      { heading: 'Measures and diagnostic interpretation', body: `Measure population capture against independently sampled customer-facing records, not only completion among items already registered. Report commitments with reconstructable wording, valid authority, complete condition, normalized due time, named owner, current evidence, and verified closure. Track unregistered promises, ambiguous deadlines, unauthorized remedies, ownerless items, items hidden by ticket closure, customer-wait versus business-wait time, failed execution after approval, repeated contact before fulfillment, reopened commitments, and corrections after review. Counts need denominators and channel coverage. A low overdue rate may reflect reliable execution, generous deadlines, missing registration, or premature closure. A high reopening rate may reveal poor work, stronger detection, payment failures, unclear customer communication, or a new review rule. Do not rank individual agents from small or noncomparable samples. Segment problems by instruction, authorization, system design, channel integration, staffing coverage, owner response, and execution. Qualitative review should examine severity and contrary cases beside averages. The useful management question is not whether the dashboard is green; it is whether an accountable owner can distinguish a broken promise from a data defect, authorized change, customer dependency, or still-open decision and then correct the responsible part of the process.` },
      { heading: 'Limitations and decision-ready output', body: `This documentary method cannot prove that every spoken or informal representation was captured, that a customer understood a message as intended, or that a completed operational event resolves a legal or contractual obligation. Call recording availability, transcription quality, channel retention, system clocks, identity matching, payment settlement, and shipment updates can all create gaps. Sampling may miss rare severe cases, and later customer evidence can change the interpretation. FTC materials offer general consumer information and do not certify this design, determine governing law, or establish the appropriate remedy in a specific matter. Findings from one queue, period, language, product, or company do not generalize automatically. Report exclusions, inaccessible sources, clock assumptions, policy changes, reviewer disagreements, and unresolved cases with every accuracy rate. A decision-ready output contains the population definition, source map, field dictionary, authority matrix, sampled records, agreement results, exception register, owner decisions, verified closures, and correction history. That package lets a client choose whether to expand the workflow, repair channel capture, clarify delegation, change absence coverage, obtain qualified advice, or pause. The outcome is reliable continuity and accountable review, not a claim that all customer obligations have been satisfied.` }
    ]
  },
  {
    slug: 'financial-close-checklist-dependency-integrity-research',
    title: 'Financial Close Checklist Dependency Integrity in Offshore Finance Support',
    excerpt: 'A dependency-based method for testing whether close tasks are ready, blocked, reviewed, and evidenced without delegating accounting judgment.',
    published: october5ResearchDate,
    thumbnail: '/research/research-default.svg',
    cluster: 'Operational Controls',
    stats: ['Primary measure: evidence-ready close dependencies', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/finance-operations-support', label: 'Explore Finance Operations Support', body: 'Build a bounded finance operations workflow with explicit dependencies, approval limits, and client-controlled accounting decisions.' },
    sources: [
      { name: 'GAO Standards for Internal Control in the Federal Government (2025)', url: 'https://www.gao.gov/greenbook' },
      { name: 'NIST SP 800-53 Rev. 5 Update 1', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' }
    ],
    sections: [
      { heading: 'Why dependency integrity matters', body: `A financial close checklist can show every row as complete while the close remains unsupported. The defect usually sits between tasks: an upstream file was preliminary, a reconciliation used the wrong period, an approval covered a different version, an exception was parked outside the checklist, or a journal posted after the reviewer signed. Dependency integrity asks whether each task consumed the required input, under the intended cutoff and version, and produced evidence suitable for the next authorized step. It is not an opinion on whether accounts comply with a reporting framework. An offshore finance support role can maintain the dependency record, prepare reconciliations under written instructions, assemble review packets, and route exceptions. Accounting policy, estimates, materiality, journal approval, control ownership, and financial-statement assertions remain with qualified client personnel. The GAO Green Book provides public control concepts including quality information, responsibility, control activities, monitoring, and remediation. NIST SP 800-53 provides control concepts for access, audit records, configuration, and system integrity. Both are used here as design references, not as claims that a private close is federally compliant or that a technology control proves an accounting conclusion.` },
      { heading: 'Model the close as a directed evidence graph', body: `Represent the close as nodes and edges rather than a flat list. A node is a bounded activity or decision: freeze a subledger extract, reconcile a bank account, calculate a schedule, review an exception, approve a journal, post it, rerun a report, or certify a balance. An edge names what the downstream node requires from the upstream node. Record entity, ledger, account scope, period, cutoff, source system, report parameters, extraction time and timezone, preparer, reviewer, expected output, accepted version, exception route, and retention location. Distinguish data availability from data acceptance. A received file may still be incomplete, preliminary, inaccessible, corrupted, or outside scope. Give each output a stable identifier or content hash where permitted so a reviewer can tell whether an approval and a later upload concern the same artifact. Never place passwords, bank credentials, personal data, or unrestricted financial exports in the graph. Use permissioned references. Dependencies owned by another team remain visible with a named responder and required event; hiding them inside a note converts external waiting into apparent finance delay.` },
      { heading: 'Research protocol for a close cycle', body: `Choose one declared entity and period, then freeze the checklist version, calendar, source hierarchy, status dictionary, and dependency rules before studying performance. Sample tasks across cash, receivables, payables, payroll interfaces, fixed assets, intercompany, accrual support, journal processing, consolidation inputs, and management review, subject to the client's scope. Include ordinary, late, reopened, manual, automated, and exception-bearing work. Reconstruct each selected path from source cutoff through preparation, review, approved adjustment, posting, rerun, and final evidence. A second reviewer independently traces an overlap sample without relying on the green status. Compare input identity, period, parameters, version, owner, sequence, approval, and final state. Preserve initial disagreements. Trace both directions: from checklist completion back to evidence and from late source changes forward to every affected task. Exercise a corrected report arriving after review and an approved journal that fails to post. A timestamp proves when a system recorded an event, not that the event was authorized, complete, or understood. Unavailable evidence stays unavailable rather than becoming an assumed pass.` },
      { heading: 'States that reveal rather than conceal waiting', body: `Use states that describe observable workflow: not started, input not due, waiting for source, input received unvalidated, ready to prepare, prepared, returned for correction, ready for owner review, owner decision pending, approved for posting, posting failed, posted unverified, verified, superseded, and unresolved. Define entry and exit evidence for every state. The difference between waiting for source and owner decision pending matters because the recovery owner differs. Complete should require the agreed final evidence, not a preparer's upload or a ticket closure. When an upstream artifact changes, mark affected downstream nodes stale automatically or through a documented review; do not leave them green because their operators finished earlier. Record planned versus actual availability separately from active handling time. A dependency deadline should specify its timezone and trigger, such as business day or receipt event. If the organization allows provisional work, label it and identify what must be rerun. The register should preserve state transitions, actor, time, reason, and source. Silent edits destroy the very sequence needed to explain a late or reopened close item.` },
      { heading: 'Authority boundaries around finance work', body: `Administrative support may collect approved inputs, confirm file identity, execute documented calculations, prepare reconciliations, populate standard journal templates, assemble support, track dependencies, and record authorized responses. It must not select accounting policy, decide recognition or classification, create an unsupported estimate, determine materiality, approve its own work, release payment, post beyond delegated access, suppress a difference, or certify financial statements. Written instructions should identify systems, entities, accounts, allowed procedures, approval thresholds, segregation requirements, evidence standards, escalation owners, absence coverage, and emergency paths. Named accounts and least privilege are essential because a clean checklist cannot compensate for uncontrolled posting access. Conflicting instructions place the item in a visible hold. A request to backdate approval, reuse prior-period evidence without validation, alter a report to match a target, or clear an unexplained difference must stop and escalate. Reviewer access should be sufficient to inspect the referenced source while sensitive exports remain in governed repositories. Control owners, finance leaders, and qualified accountants decide whether an exception is acceptable and what correction is required.` },
      { heading: 'Close scenarios that challenge the model', body: `Test a bank feed that refreshes after reconciliation, an invoice batch posted to the prior period, an intercompany counterparty working in another timezone, a payroll file replaced without a new name, an accrual schedule whose formula changed, a journal approved but rejected by the ledger, and a late adjustment that alters a reviewed report. Add a task completed by an alternate during absence and one genuinely uneventful path. For each, ask which downstream nodes became stale, who had authority to proceed, what the record showed at each decision, and what final evidence restored readiness. Exercise duplicate files, daylight-saving boundaries, closed accounting periods, access loss, and a reviewer who rejects only part of a package. Confirm that reopening one task does not erase its former state or imply every downstream balance is wrong; it should trigger a scoped impact review. Test whether an operator can identify the authoritative version without using filenames alone. If the system cannot represent partial acceptance, provisional processing, or failed posting without marking a false completion, revise the workflow before adding more entities or accounts.` },
      { heading: 'Metrics for diagnosis, not deadline theater', body: `Report dependency readiness at planned start, input lateness by owner category, unvalidated receipts, stale downstream tasks, review returns, reopened nodes, approval waiting, posting failures, verification gaps, and adjustments after certification. Show counts with denominators by entity and task type. Measure active preparation separately from external waiting and owner decision time. A fast close can coexist with weak evidence; a slower close can reflect deliberate detection of defects. A low exception rate may mean stable processing or poor capture. Do not score individuals from tasks with different dependencies and risk. Inspect the longest path through the graph because shortening a noncritical task may not affect completion. Also inspect concentrated risk: one unresolved high-impact dependency can matter more than many routine completions. Changes to checklist design, system migration, acquisition, calendar, or policy create breaks in comparability. The purpose of measurement is to direct repair toward source availability, instructions, access, preparation, review capacity, system behavior, or decision ownership. It is not to make every delay look like operator underperformance.` },
      { heading: 'Limits and the decision-ready close packet', body: `A documentary dependency review cannot determine whether financial statements are fairly presented, whether an accounting treatment is correct, or whether fraud, error, or every off-system adjustment was detected. Source extracts may be incomplete, system audit data may be unavailable, approvals may occur through restricted channels, and the selected sample may miss rare material events. A content hash shows identity, not accuracy. Workflow agreement shows reproducibility, not accounting correctness. Public control frameworks do not certify this close design or prescribe a universal close duration. Results for one entity and period should not be generalized to another without testing. State exclusions, unavailable evidence, late discoveries, reviewer disagreements, system limitations, and changes after cutoff beside any readiness figure. A useful packet contains the declared graph, field definitions, source lineage, access and authority map, sampled traces, stale-node history, unresolved exceptions, owner decisions, posting and verification evidence, corrective actions, and known limitations. It lets the client decide whether to repair a source, clarify instructions, change review timing, narrow delegated work, obtain specialist review, expand a tested process, or stop. The outcome is a reconstructable close workflow, not an outsourced accounting opinion.` }
    ]
  },
  {
    slug: 'campaign-utm-attribution-change-evidence-research', title: 'Campaign UTM Governance and Attribution-Change Evidence in Offshore Marketing Operations',
    excerpt: 'A reproducible method for governing campaign parameters and separating observed traffic from changing attribution rules.', published: october5ResearchDate,
    thumbnail: '/research/research-default.svg', cluster: 'Marketing Operations',
    stats: ['Primary measure: reconstructable campaign classification', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/marketing-operations-support', label: 'Explore Marketing Operations Support', body: 'Build a bounded campaign operations workflow with governed parameters, preserved source evidence, and client-owned attribution decisions.' },
    sources: [{ name: 'Google Analytics: Manual campaign dimensions and parameters', url: 'https://support.google.com/analytics/answer/10917952' }, { name: 'Google Analytics: Attribution models', url: 'https://support.google.com/analytics/answer/10596866' }],
    sections: [
      { heading: 'Comparison governance note', body: `Treat each comparison as a versioned analytical product with a named owner, declared question, and review date. Preserve contrary observations rather than removing them as noise. A reviewer should repeat the classification without relying on private memory.` },
      { heading: 'Finding: classification and attribution are different controls', body: `UTM parameters classify a link at collection time; an attribution model later assigns credit under its own rules. Conflating the two causes teams to rewrite campaign tags to make reports look consistent, even when the real change occurred in channel definitions, identity resolution, lookback windows, consent coverage, model selection, or platform processing. Google documents the manual campaign parameters used to populate traffic-source dimensions and separately documents attribution settings and models. Those materials describe Google Analytics behavior, not a universal marketing measurement standard or proof of commercial impact. For offshore marketing operations, the safe delegated role is to implement an approved naming plan, test links, preserve releases, detect deviations, and prepare comparison evidence. Marketing leadership owns campaign meaning, channel policy, attribution choices, budget decisions, and performance claims. The decision-grade question is whether another reviewer can reconstruct which parameter set was published, what analytics configuration applied, and why a reported result changed. A tidy dashboard without that lineage cannot distinguish changed customer behavior from changed measurement.` },
      { heading: 'Create a governed campaign namespace', body: `Define each permitted field, character rule, case rule, reserved value, owner, and effective date before generating links. Source identifies the referring platform or publisher under the organization's dictionary; medium describes the governed delivery class; campaign connects activity to an approved initiative; content distinguishes creative or placement when needed; term should be used only for its approved purpose. Do not place names, email addresses, account identifiers, confidential segmentation, or other sensitive data in query strings. Maintain a stable campaign identifier separately from a mutable display label. Record destination, canonical destination, locale, parameters in deterministic order, shortener or redirect, creative identifier, channel, owner, approval, creation time, intended launch window, and retirement state. Preserve the literal released URL and its normalized representation. Case folding or decoding must never silently merge historically distinct values. When an external partner supplies tags, map them explicitly rather than overwriting their evidence. A taxonomy exception is a visible decision with an expiry, not a new convention created by repetition.` },
      { heading: 'Release and collection protocol', body: `Select a bounded set of campaigns across email, paid, social, partner, QR, and owned placements where applicable. Generate URLs from the approved register, then test destination resolution, HTTPS, redirect retention, parameter encoding, duplicate keys, fragments, mobile behavior, and analytics collection in a nonproduction or controlled context. Save the tested literal link, redirect chain, final landing location, consent state, event time and timezone, observed source dimensions, property or stream identifier, and tester. After launch, sample actual placement links rather than assuming the register matches distribution. Reconcile collected values to the released population while keeping unattributed and unrecognized traffic visible. A missing parameter can arise from a bad link, redirect, privacy control, application behavior, manual copy, or analytics processing; classification should stop at the evidence. Do not patch historical source data to force a match. Corrections apply prospectively unless the analytics owner authorizes a documented restatement and the platform supports it honestly.` },
      { heading: 'Attribution-change evidence', body: `Create a change record whenever a model, lookback window, channel group, key event, identity method, property configuration, consent implementation, cross-domain setup, import, or reporting query changes. Capture requester, approver, rationale, effective timestamp, affected properties and reports, previous and new configuration, reproducible screenshots or exports, and expected comparability break. Before change, freeze a bounded comparison dataset and query definition. After change, rerun the same declared question where technically possible and label differences as observed; causal explanations remain inference until tested. Never describe reassigned credit as newly created revenue. Separate event occurrence, campaign classification, eligible conversion, and attributed credit. If a platform recalculates history, preserve the prior export and note that the interface no longer reproduces it. If it does not recalculate, do not splice periods as though rules were constant. Marketing owners decide whether a trend remains decision-useful and what disclosures accompany it.` },
      { heading: 'Challenge tests and operating boundaries', body: `Exercise mixed-case parameters, spaces and encoded characters, duplicated keys, an email link copied into social, a partner redirect that strips tags, a shortened URL changed after approval, organic sharing of a tagged link, cross-domain navigation, consent denial, an offline conversion import, and a channel-definition change midcampaign. Include an ordinary clean case. Ask whether reviewers reach the same classification from the stored evidence and whether the register preserves what a customer actually received. The support role may build approved URLs, check placements, reconcile values, flag anomalies, and prepare before-and-after reports. It may not choose the attribution model, redefine channels, infer customer identity, claim causation, alter spend, or conceal unattributed traffic. Conflicting instructions create a hold routed to the analytics or marketing owner. Access should be least privilege; exports should avoid user-level data when aggregate evidence is sufficient. A link that resolves correctly can still be governed incorrectly, while a correctly governed link can still produce incomplete analytics.` },
      { heading: 'Worked comparison without a causal claim', body: `Consider a campaign released under one channel dictionary on Monday and reviewed after a new custom channel group takes effect Thursday. Build two views from a frozen event cohort: the original source and medium values as collected, and the classifications produced by each documented rule set. Hold property, eligible event, reporting timezone, date range, and query dimensions constant. Count records that move between groups and retain an unclassified bucket. If reported attributed conversions also change, compare the attribution configuration, eligibility rules, lookback window, and processing time before offering an explanation. The appropriate result may be three statements: collection values did not change; classification changed for a declared subset; credited outcomes changed under a separately identified setting. That is more accurate than saying the campaign suddenly improved or declined. Have a second reviewer reproduce the tables from saved definitions and exports. Record query text or interface settings, extraction time, thresholds, late-arriving data, and any platform limitation. When exact reproduction is impossible, say which part cannot be recreated and why. The client owner then decides whether to annotate the trend, restate a report, preserve separate eras, or discontinue the comparison. The support analyst prepares this evidence but does not select the story the numbers should tell.` },
      { heading: 'Measures, limitations, and reader decision', body: `Report released links matching the register, tested redirect retention, observed values mapped to approved taxonomy, unknown values, sensitive-value violations, unapproved changes, comparison breaks, and time to owner resolution. Use denominators by channel and release, not a blended percentage that hides one failing placement. Retain failed tests and unexpected values so the review is not limited to links known to work. Compare releases only when channel mix, taxonomy coverage, and observation windows are stated. A percentage of mapped sessions should identify whether its denominator includes direct, unassigned, consent-limited, or otherwise unavailable observations. Five-word consistency does not prove conceptual consistency: inspect whether campaign meanings, worked examples, and conclusions remain specific. Analytics evidence is limited by consent, blockers, deletion, platform processing, identity uncertainty, sampling or thresholds, offline imports, redirect behavior, and configuration access. This study cannot prove incremental effect, causal return, or complete observation of customer journeys. Google documentation explains its product and does not validate a company's implementation. A decision-ready packet contains taxonomy version, URL inventory, test evidence, collection reconciliation, configuration history, comparability statement, exceptions, owner decisions, and limitations. It supports a choice to repair links, clarify taxonomy, restate a report, narrow a comparison, obtain specialist review, or continue a controlled workflow without turning administrative tagging into marketing judgment.` }
    ]
  },
  {
    slug: 'policy-exception-expiry-renewal-controls-research', title: 'Policy Exception Expiry and Renewal Controls in Offshore Shared Services',
    excerpt: 'A lifecycle method for ensuring temporary exceptions expire, renew through accountable review, and leave verifiable closure evidence.', published: october5ResearchDate,
    thumbnail: '/research/research-default.svg', cluster: 'Governance',
    stats: ['Primary measure: owner-decision-ready exception records', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/shared-services-administration', label: 'Explore Shared Services Administration', body: 'Build a shared-services workflow that tracks temporary exceptions while preserving risk and policy authority with client owners.' },
    sources: [{ name: 'GAO Standards for Internal Control in the Federal Government (2025)', url: 'https://www.gao.gov/greenbook' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' }],
    sections: [
      { heading: 'Finding: expiry must change the operating state', body: `An expiry date is not a control when nothing happens at expiry. Reliable exception governance requires a defined transition: the exception closes after verified restoration, enters an approved renewal, or moves to an escalated noncompliant or unresolved state owned by someone authorized to act. This topic differs from prior exception-aging analysis, which measured owner waiting. Here the research object is the full authorization lifecycle and the evidence needed to prevent a temporary departure from becoming an undocumented permanent rule. GAO control principles support defined responsibility, quality information, monitoring, and remediation; NIST CSF 2.0 provides governance and risk-management outcomes. Neither framework approves a specific exception, sets a universal duration, or transfers risk authority. Offshore shared-services staff can maintain the register, test required fields, issue reminders, assemble renewal packets, and verify recorded actions. Policy interpretation, risk acceptance, compensating-control sufficiency, renewal, and enforcement remain with designated client owners.` },
      { heading: 'Define the exception object and its clock', body: `Every record should identify the policy or control requirement and version, bounded scope, affected system or process, requestor, accountable owner, risk owner, reason, approval authority, decision, start, expiry timestamp and timezone, review checkpoints, conditions, compensating measures, evidence locations, restoration plan, and closure standard. Separate the business need from the approved departure. A broad narrative such as operational necessity cannot define scope. The clock may start at approval, implementation, or a named event, but the choice must be explicit. Calendar date, business day, and duration are not interchangeable. Renewal lead time is a workflow trigger, not an automatic extension. Link dependent exceptions without merging their authorities. Keep sensitive security, personnel, legal, or customer material in permissioned repositories and store references in the register. A copied prior exception is a new request only after its current facts, scope, owner, and evidence are independently reviewed.` },
      { heading: 'Lifecycle reconstruction method', body: `Freeze the population and observation period, then reconcile registers with approval systems, risk records, access or configuration evidence, service queues, and closure artifacts. Include active, expired, renewed, rejected, withdrawn, superseded, and supposedly closed exceptions. Stratify by duration, impact category, owner, repeated renewal, compensating measure, and evidence availability. Reconstruct a sample from request through validation, decision, implementation, checkpoints, pre-expiry notice, renewal or restoration, and verified closure. A second reviewer independently traces an overlap sample using the same definitions. Preserve disagreement about scope, dates, owner, and state. Trace backward from currently nonstandard conditions to an authorization and forward from expired approvals to the actual environment. A signed decision does not prove conditions were implemented; a closed ticket does not prove standard state was restored. Mark evidence unavailable rather than inferring compliance from silence.` },
      { heading: 'Renewal is a new decision, not an edit', body: `A renewal packet should show original rationale, present scope, current exposure, incidents or near misses, performance of compensating measures, changed dependencies, alternative progress, requested duration, and an updated restoration plan. Preserve the former decision and create a linked new one with its own approver and effective period. Do not edit the old expiry or copy its signature. Repeated renewals deserve explicit trend visibility because they may indicate an unrealistic policy, missing investment, unresolved ownership, or normalized risk; they do not automatically prove misconduct. Reviewers should see whether the approving authority remains valid and whether organizational, technical, contractual, or legal context changed. If review is incomplete at expiry, the predefined state applies. The administrator cannot manufacture a grace period. Emergency extensions require their own authorized path, narrow duration, and retrospective evidence. Any instruction to backdate approval or conceal a lapse must stop and escalate.` },
      { heading: 'Expiry challenge cases and role boundary', body: `Test an owner who leaves before expiry, a compensating control whose evidence stops, a system migration that changes scope, two linked exceptions with different dates, an expiry during a holiday, a renewal submitted late, partial restoration, a rejected renewal, and an exception discovered outside the register. Include one clean closure. Confirm reminders reach a role or rota rather than only one mailbox and that absence coverage cannot approve beyond delegated authority. Exercise the transition at the exact timestamp and verify downstream access, configuration, process, or reporting reflects the authorized state. Shared-services staff may reconcile records, notify owners, prepare evidence, record decisions, and verify specified closure artifacts. They may not assess residual risk, interpret policy, approve or extend an exception, disable a system, punish a person, or declare a compensating control effective. Conflicting sources remain visible and route to the policy, security, legal, operational, or risk owner named by the client.` },
      { heading: 'Closure proof and post-expiry review', body: `Define closure evidence when the exception is approved, not when the administrator wants to clear the queue. Restoration may require a configuration snapshot, access reconciliation, completed migration, updated procedure, test result, owner attestation tied to objective evidence, or another artifact selected by the control owner. Record the intended standard state, actual restoration event, verifier, verification time, residual items, and repositories. If only part of the scope is restored, close that portion only when the model permits it and keep the remainder under an authorized state. After closure, sample whether the former exception condition reappears and whether temporary access, monitoring, or workarounds were removed. A renewal decision should not erase a lapse between old expiry and new effectiveness. Quantify that interval and route it to the responsible owner without labeling its consequence beyond available evidence. Review a small cohort of recently expired records against operational sources to detect registers that close administratively while conditions persist. Also trace newly discovered nonstandard conditions backward; absence of an approval is a finding, not proof of intent or impact. Corrective actions need owner, due event, and later verification. This post-expiry step distinguishes a living governance process from a reminder calendar.` },
      { heading: 'Notification design and safe failure', body: `Schedule notices far enough ahead for evidence gathering and owner review, with intervals proportionate to the client's chosen risk tier. Record delivery and acknowledgement separately: an email sent to an inactive owner does not demonstrate receipt or decision. Escalation should move through named roles and alternates while preserving the original owner and deadline. Dashboards may highlight proximity, but color cannot replace state or authority. If the register service fails, a documented recovery procedure should identify the last reliable extract, urgent expiries, approved communication channel, and reconciliation after restoration. Test duplicate notifications, timezone boundaries, bulk owner reassignment, and a malformed date. Prevent automation from granting renewal, changing risk acceptance, or closing exceptions based solely on a response keyword. Automated reminders assist attention; they cannot make the governed decision. Retain enough notification history to diagnose failure without keeping unnecessary sensitive content. Review whether repeated reminders produce owner action or merely administrative noise, then adjust routes through authorized governance rather than extending dates to improve a metric.` },
      { heading: 'Measures, limitations, and outcome', body: `Report population reconciliation, complete scope and authority fields, notices delivered, decision-ready renewal packets, expiries without disposition, unauthorized post-expiry operation, repeated renewals, failed compensating evidence, partial closures, reopened items, and verified restoration. Show denominators and state definitions. A low active count may reflect sound closure or missing discovery; many renewals may reflect weak remediation or deliberate temporary management. Segment by failure point rather than ranking coordinators. This study cannot determine whether a policy is legally sufficient, a risk is acceptable, every departure was discovered, or a control operates effectively. Restricted sources, system latency, informal approvals, and sampling constrain results. Public frameworks do not certify the workflow. A decision-ready output contains the reconciled population, lifecycle history, authority map, current evidence, renewal comparisons, lapse register, owner decisions, closure verification, corrective actions, and limitations. It lets the client restore standard state, renew deliberately, redesign policy, fund remediation, narrow delegated administration, seek qualified review, or stop—without allowing a calendar field to masquerade as governance.` }
    ]
  }
];
