export const september8CampaignDate = '2026-09-08' as const;
const image = '/philippines-team.jpg';
const blogs = [
['offshore-subscription-cancellation-desk','An offshore subscription cancellation desk that does not lose the customer record','Gather cancellation facts while refund and retention decisions stay with the client.','account, plan, renewal date, cancellation request, payment state, and earlier contacts','eligibility exceptions, refund release, goodwill amounts, and suspected fraud','approved amount, processor result, ledger entry, customer notice, and remaining owner'],
['philippines-medical-appointment-recall-queue','How a Philippines appointment recall queue can keep clinical judgment out of scheduling','Follow up on missed appointments without turning schedulers into clinicians.','patient identifier, recall reason, due window, consent, contact preference, and attempt history','clinical urgency, treatment advice, eligibility, privacy exceptions, and discharge decisions','appointment status, approved message, escalation, next attempt, and review date'],
['offshore-construction-rfi-administration','Offshore RFI administration: keep the question tied to the drawing','Organize construction questions so the answer stays linked to the right revision.','project, RFI number, drawing revision, location, question, requester, and due date','design interpretation, cost acceptance, schedule relief, safety decisions, and contractual notice','issued response, approver, affected documents, distribution list, and open consequence'],
['philippines-freight-invoice-audit-prep','Philippines freight invoice review: prepare the discrepancy before finance decides','Match carrier charges to shipment records while payment authority stays with the client.','shipment, invoice, bill of lading, agreed rate, accessorial evidence, currency, and receipt date','payment release, dispute position, write-offs, contract interpretation, and fraud findings','matched amount, coded variance, evidence link, decision owner, and payment state'],
['offshore-legal-intake-conflict-check-prep','Offshore legal intake support: prepare a conflict check without making the call','Organize names and relationships for attorney review without offering legal conclusions.','prospective client names, related parties, entities, matter type, jurisdictions, and spelling variants','conflict conclusions, legal advice, representation, waivers, and matter acceptance','search record, possible matches, attorney disposition, intake status, and approved response'],
['philippines-marketplace-seller-case-triage','Philippines marketplace case triage before the appeal clock runs out','Turn platform notices and seller records into a usable evidence file.','seller account, marketplace notice, policy citation, listing IDs, earlier submissions, and deadline','policy interpretation, appeal claims, compensation, legal escalation, and risk acceptance','case category, evidence inventory, missing item, submitted response, and platform result'],
['offshore-property-maintenance-work-order-control','Offshore property maintenance dispatch without a blank cheque','Coordinate tenants and vendors with clear access, price, and completion limits.','property, unit, requester, issue, access permission, approved vendor, and spending limit','emergency classification, vendor exceptions, spend increases, and tenant remedies','appointment, vendor acknowledgment, completion evidence, invoice match, and tenant confirmation'],
['philippines-loan-document-indexing-support','Philippines loan document indexing: make the missing-file list reliable','Classify borrower documents while credit decisions remain with the lender.','application ID, document type, borrower, statement period, page count, source, and received time','creditworthiness, authenticity findings, conditions, exceptions, and adverse action','indexed file, duplicate state, missing-page flag, reviewer queue, and audit event'],
['offshore-warranty-claim-evidence-review','Offshore warranty claim preparation: find the gap before adjudication','Assemble purchase and failure evidence without deciding whether the warranty pays.','claim ID, serial number, purchase record, warranty version, reported failure, photos, and service history','coverage, causation, fraud, replacement value, goodwill, and legal interpretation','complete claim packet, evidence gaps, adjudication result, fulfillment record, and customer message'],
['philippines-grant-reporting-calendar-desk','A Philippines grant reporting calendar that survives staff changes','Keep obligations, evidence owners, and submission records together.','award, funder, reporting period, obligation, template version, evidence owner, and due date','allowable cost judgments, narrative claims, certification, budget changes, and disclosures','reviewed draft, approver, submission receipt, retained evidence, and next obligation'],
['offshore-food-delivery-menu-operations','Offshore menu operations for food delivery apps across every storefront','Prepare item and availability changes from approved menu sources.','location, channel, menu version, item ID, approved description, price, availability, and allergen source','allergen interpretation, pricing exceptions, claims, substitutions, and launch timing','live item, price, option mapping, availability, mobile rendering, and rollback note'],
['philippines-recruiting-interview-coordination','Philippines interview coordination that protects candidate context','Coordinate panels and availability while selection decisions stay with hiring owners.','candidate ID, approved stage, role, panel, time zones, availability, and communication history','selection, assessment scoring, compensation, accommodations, references, and rejection rationale','confirmed schedule, interviewer brief, attendance, feedback receipt, candidate notice, and next owner'],
] as const;
const blogSources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and access-control context.'},{name:'Philippine National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Philippine privacy-accountability context.'}];
export const september8BlogPosts=blogs.map(([slug,title,excerpt])=>({slug,title,excerpt,minutes:9,published:september8CampaignDate,image,citations:blogSources.map(s=>s.url)}));
export const september8BlogDetails=Object.fromEntries(blogs.map(([slug,title,,inputs,decisions,closure])=>[slug,{
 keyTakeaways:['Build the record from '+inputs+'.','Route '+decisions+' to the named client owner.','Close only after checking the '+closure+'.'],
 sections:[
 {title:'Open one traceable case',body:'Start with '+inputs+'. Keep the request in the approved case system and preserve its source and time. Compare identifiers before merging records. When sources disagree, describe the mismatch and pause the affected step. A Philippines-based specialist can assemble evidence, but should never replace a missing fact with a likely answer. This gives the reviewer a usable record instead of a polished story that cannot be retraced.'},
 {title:'Write the decision boundary into the queue',body:decisions.charAt(0).toUpperCase()+decisions.slice(1)+' stay with an authorized client owner. Name that owner and a backup, then state what the coordinator may do while waiting. A useful escalation contains the decision requested, relevant evidence, deadline, and safest checkpoint. Urgency does not create permission, and silence is not approval.'},
 {title:'Use controlled access and current sources',body:'Give each worker an individual account and only the fields needed. Keep personal, financial, and identity information inside approved systems. Record the source version, action, actor, and approval. NIST CSF 2.0 helps organize governance and access questions, while the Philippine Data Privacy Act supplies local privacy context. The client procedure must still define the pass rule.'},
 {title:'Check the downstream result',body:'Before closure, compare the authorized action with the '+closure+'. Look for partial saves, delayed integrations, duplicates, stale messages, and records that changed after approval. If the result is incomplete, leave a named owner and review time. The audit trail should show what arrived, what was allowed, what changed, who decided an exception, and what the requester was told.'},
 {title:'Pilot ordinary and awkward cases',body:'Test '+title.toLowerCase()+' with a routine request, a missing field, conflicting evidence, and one material exception. Ask two reviewers to identify the same permitted action and escalation point. Repair instructions where they disagree. Review a mixed sample after launch and retain reopened cases. Results describe only that queue, period, systems, and sample; they are not a forecast.'}],
 internalLinks:[{label:'Plan an operations support role',href:'/services/operations-support',note:'Turn the queue into a bounded role brief.'},{label:'Review the research library',href:'/research',note:'Test the operating assumptions.'}],
 banners:[{label:'Scope checkpoint',title:'Name the decision owner',body:'Put permissions and stop conditions in writing.',href:'/contact-us',linkText:'Scope the role'},{label:'Pilot checkpoint',title:'Test a mixed sample',body:'Include routine work and exceptions.',href:'/contact-us',linkText:'Plan the pilot'},{label:'Next step',title:'Build an inspectable queue',body:'Define the record, boundary, and finish line.',href:'/contact-us',linkText:'Contact us'}],
 faqs:[{question:'What should the offshore specialist decide?',answer:'Only routine actions explicitly permitted by the role brief. Material exceptions stay with the named client owner.'},{question:'What counts as complete?',answer:'Completion requires a check of the '+closure+', plus a visible owner for anything unresolved.'}],sources:blogSources
}])) as Record<string,any>;

const researchSources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'Philippine National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'International Labour Organization, Working anytime, anywhere',url:'https://www.ilo.org/publications/working-anytime-anywhere-effects-world-work'}];
const studies=[
['offshore-queue-interruption-cost-study','What queue interruptions really cost an offshore operations team','A time study that separates necessary questions from avoidable switching.','case-open time, ready time, status changes, dependency owner, completion time, and reopens','active work, approval waits, source gaps, system holds, and deferred cases'],
['philippines-shift-overlap-handoff-study','How much shift overlap does a Philippines handoff need?','A cohort comparison built around accepted handoffs and reconstructed work.','effective SOP versions, prompts, training examples, sampled cases, actions, and outcomes','outdated instructions, undocumented workarounds, ambiguity, access constraints, and approved changes'],
['offshore-exception-taxonomy-reliability','Can two reviewers classify the same offshore workflow exception?','An agreement study that tests whether an exception taxonomy works in practice.','submitted cases, completeness rule, review result, return reason, resubmission, and final disposition','operator error, missing evidence, reviewer disagreement, system failure, and changed requirements'],
['philippines-training-example-coverage-review','Do training examples cover the work a Philippines team actually receives?','A coverage review comparing the training set with the live queue mix.','exception type, detection time, routing rule, recipients, acknowledgments, authority, and decision','wrong routing, unavailable owners, incomplete packets, ambiguous authority, and execution delay'],
['offshore-rework-cause-coding-study','Offshore rework cause coding without blaming the nearest person','A reproducible review separating corrections from changed requests and broken inputs.','queue population, case types, shifts, workers, risk flags, sampling rule, exclusions, and results','random variation, oversampling, excluded failures, reviewer knowledge, small groups, and missing logs'],
] as const;
export const september8ResearchPosts=studies.map(([slug,title,excerpt,evidence,factors])=>({slug,title,excerpt,published:september8CampaignDate,thumbnail:image,cluster:'Workflow Design' as const,stats:['Scope: one defined queue and review window','Interpretation separates workflow, source, system, and owner factors'],sections:[
{heading:'Question and scope',body:'Can reviewers reach a consistent finding from '+evidence+'? Define the queue, roles, policy version, period, and unit before sampling. This study concerns one operating process, not the general ability or trustworthiness of Filipino professionals.'},
{heading:'Method',body:'Select a documented cohort containing routine cases and exceptions. Capture '+evidence+'. Prefer system records, minimize personal information, and redact working copies. Have a second reviewer classify a subset with the same definitions. Preserve disagreements so apparent precision does not hide an unclear rule.'},
{heading:'Analysis',body:'Separate '+factors+'. Report every rate with its numerator, denominator, window, and exclusions. Inspect cases before assigning cause; association alone does not establish causation. NIST frameworks organize control questions, but the client procedure supplies the operational pass condition.'},
{heading:'Decision use',body:'Change one owned control: an intake field, source label, permission, routing rule, example, or review checkpoint. Keep consequential decisions with the authorized client owner. Repeat the sample under the same definitions and keep unresolved cases visible.'},
{heading:'Scope and limitations',body:'Findings apply only to the sampled queue, period, systems, people, and rules. Small cohorts can miss rare exceptions, missing logs can distort measures, and reviewer knowledge can affect classification. The ILO source offers broad context; it does not establish company performance. This is an operating review, not legal advice, an audit opinion, or a forecast.'}],sources:researchSources}));
