import type { ResearchPost } from './fleet-data';

// Provisional only. OFFAA-85 must reconcile this to the actual first-publication
// date in UTC immediately before the sole combined production push.
export const october5ResearchDate = '2026-10-05';

export const october5ResearchPosts: readonly ResearchPost[] = [
  {
    slug: 'supplier-scorecard-evidence-reliability-research',
    title: 'Supplier Scorecard Evidence Reliability in Offshore Procurement Administration',
    excerpt: 'A field-level method for deciding whether supplier scorecards support procurement review without turning administrative support into vendor judgment.',
    published: october5ResearchDate,
    thumbnail: '/aug20-research-heroes/offshore-operations-source-freshness-review.svg',
    cluster: 'Workflow Design',
    stats: ['Primary measure: decision-ready supplier observations', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/procurement-administration', label: 'Explore Procurement Administration', body: 'Build a bounded procurement administration workflow with named evidence, approval limits, and client-side review.' },
    sources: [
      { name: 'GAO Standards for Internal Control in the Federal Government (2025)', url: 'https://www.gao.gov/greenbook' },
      { name: 'NIST SP 800-161 Rev. 1: Cybersecurity Supply Chain Risk Management Practices', url: 'https://csrc.nist.gov/pubs/sp/800/161/r1/final' }
    ],
    sections: [
      { heading: 'Finding and decision boundary', body: `A supplier scorecard is useful only when a reviewer can reconstruct what was observed, which obligation or operating expectation it relates to, who evaluated it, and what decision followed. A polished red-amber-green summary does not supply that chain by itself. For an offshore procurement administration role, the defensible contribution is evidence preparation: maintaining the supplier population, linking observations to approved records, checking required fields, routing discrepancies, and preserving owner decisions. Supplier selection, risk acceptance, contract interpretation, remediation demands, and commercial consequences remain with authorized client owners. The GAO Green Book describes principles for quality information, responsibility, monitoring, and corrective action in a federal internal-control context. NIST SP 800-161 discusses supply-chain risk practices across the lifecycle. This study uses both as control-design references; neither mandates a private company's scorecard, proves a supplier is safe, or substitutes for legal, security, procurement, or operational judgment. The practical research question is narrower: can a bounded record make a supplier observation decision-ready without hiding uncertainty or transferring authority to the person assembling it?` },
      { heading: 'Build the scorecard population before choosing metrics', body: `Start with the supplier universe, not the vendors easiest to measure. Reconcile approved supplier, contract, purchase-order, accounts-payable, security-review, service-owner, and incident sources for a declared business unit and observation period. Retain stable supplier and agreement identifiers alongside display names so acquisitions, resellers, affiliates, and duplicate records do not collapse silently. Include active suppliers, paused relationships with continuing obligations, subcontractors visible through approved records, and terminated suppliers with open credits, data-return work, or unresolved corrective actions. Record the source and extraction time for every population member. Then define the unit of assessment: legal entity, contracted service, location, product, or engagement. Mixing those units makes a score uninterpretable because one supplier can perform differently across services. Missing ownership, inaccessible agreements, and conflicting names are findings to route, not permission to invent a match. The administrator should reference permissioned systems rather than copying contracts, personal data, security evidence, or confidential pricing into a parallel spreadsheet. A population completeness measure needs a denominator and explicit exclusions; a high completion percentage over an incomplete vendor list is false reassurance.` },
      { heading: 'Translate observations into traceable evidence', body: `Each scorecard field needs a definition, evidence source, observation window, permissible status, and accountable reviewer. Delivery timeliness might derive from accepted receipt against an agreed milestone, not the date an invoice arrived. Quality might concern documented returns or acceptance exceptions, not an operator's impression. Responsiveness should distinguish supplier response time from time waiting for the client's clarification. Security, privacy, continuity, or financial-risk fields should point to the qualified owner's current assessment rather than asking an administrative analyst to recreate it. Preserve numerator, denominator, timezone, cut-off, exclusions, and late-arriving corrections behind any rate. Free-text comments should identify a dated event and source, avoiding character judgments and unsupported causal claims. When records conflict, retain the conflict and send a precise question to the owner. Facts are source values and observable events. Analysis is the declared transformation of those facts under the rubric. An explanation offered by a supplier or stakeholder remains an attributed statement until confirmed. A forecast, causal account, or recommended consequence is an inference or decision, not a fact. This separation lets a reviewer correct the evidence without rewriting history.` },
      { heading: 'Method for a bounded reliability test', body: `Freeze the population, period, definitions, and source hierarchy before reading final ratings. Select a stratified sample that includes high-spend and low-spend engagements, new and long-running relationships, ordinary performance, exceptions, missing records, and supplier-name changes. A preparer assembles evidence while a second reviewer independently reconstructs an overlap sample from authorized sources. Compare whether both reviewers identify the same event, denominator, obligation, status, and unresolved question. Preserve their first classifications before calibration so disagreement remains measurable. Trace a subset in both directions: from scorecard statement back to source, and from source exception forward to the scorecard and owner response. Test cut-off behavior with a correction received after the period, an invoice disputed for reasons unrelated to performance, and a milestone changed through an approved amendment. The protocol should also include a supplier with no events; zero exceptions must not automatically become perfect performance when required evidence is absent. Report field-level agreement, untraceable claims, missing denominators, stale owner assessments, unmatched suppliers, and corrections after review. Do not blend these defects into one average that conceals why a record failed.` },
      { heading: 'Interpretation without automatic vendor ranking', body: `A score is a compressed description of selected observations, not a complete supplier judgment. A low on-time rate can reflect supplier delay, an unrealistic baseline, a client approval hold, disputed event timestamps, or a changed scope. A high rate can coexist with severe but infrequent failures. Weighting several fields creates an additional management choice: it does not arise objectively from the data. Accordingly, show material components and exceptions beside any aggregate. Compare like periods only when definitions and source coverage remained stable; otherwise mark the break and avoid a trend claim. Never infer that missing incidents prove absence of incidents, or that a completed questionnaire proves operating effectiveness. Reviewers should examine contrary cases, severity, concentration, and exposure as well as counts. The output can support decisions to request clarification, repair data, narrow an engagement, perform qualified review, or monitor a corrective action. It cannot on its own establish breach, compliance, financial viability, cybersecurity posture, or suitability for future work. If a threshold triggers an action, record who approved that rule, when it took effect, what exceptions are allowed, and which owner may override it.` },
      { heading: 'Operational workflow and authority controls', body: `The working instruction should name approved systems, required fields, source precedence, access limits, cut-off rules, reviewer assignments, escalation paths, and retention treatment. The offshore administrator may reconcile supplier identifiers, prepare evidence links, calculate preapproved measures, flag missing inputs, distribute review packets, record authorized dispositions, and follow up on due dates. The role must not negotiate, amend terms, accuse a supplier, accept risk, approve payment, assign contractual fault, decide termination, or alter a rating to reach a desired outcome. Conflicting instructions place the item on a visible hold with a named client owner. Use named accounts and least access; do not export unrestricted supplier, bank, personnel, or security data merely for convenience. Version definitions and scorecard logic, retaining effective dates so earlier results remain understandable. Corrections should preserve the original observation, reason, approver, time, and recalculated result. A completed administrative task is not a completed corrective action: closure needs the agreed evidence and authorized acceptance. These controls make the workflow scalable while keeping consequential supplier decisions where the client intended them to remain.` },
      { heading: 'Failure modes and challenge cases', body: `Test the design against cases likely to defeat a neat spreadsheet. One supplier uses two legal entities; another invoices through a reseller; a third changes product name without changing the agreement. A delivery is accepted after the client delayed access. A credit note arrives after period close. A severe security concern is restricted to a qualified reviewer, so the preparer can see only a current status and owner. A contract renewal overlaps an unresolved corrective action. An owner asks for a green rating despite missing evidence. For each case, require the record to preserve identity, scope, source, dates, uncertainty, authority, and next action without disclosing restricted material. Include one fully ordinary record to ensure reviewers do not manufacture exceptions. Exercise absence coverage, reassignment, correction, and rollback of an erroneous match. Confirm that a late source update changes the appropriate period under an approved rule rather than through silent editing. If two reviewers repeatedly disagree on a field, revise the definition or source hierarchy before scaling. If the necessary source cannot be accessed lawfully or reliably, mark the field unavailable and route it; do not replace it with intuition.` },
      { heading: 'Measures, limitations, and reader outcome', body: `Useful measures include population reconciliation rate, fields supported by current evidence, reviewer agreement by field, observations returned for clarification, unmatched supplier identities, late corrections, overdue owner decisions, reopened actions, and closure verified against the agreed record. Report counts with denominators and exclusions. Segment defects by population, source, definition, preparation, review, and implementation so managers can repair the right part of the process. This documentary study cannot establish that every supplier, incident, obligation, subcontractor, or operational event was discovered. Source systems may be delayed or incomplete; restricted evidence may be summarized; samples can miss rare failures; and relationships can change after the cut-off. Public control frameworks do not validate this particular workflow or provide a universal acceptable score. Findings from one service, period, or client cannot be generalized to other suppliers, countries, or future performance. The reader should receive a declared population, field dictionary, source map, sample method, disagreement record, exceptions, owner dispositions, limitations, and corrective-action register. That package supports a reasoned choice to pilot, repair sources, narrow the scorecard, obtain specialist review, or stop. Its value is not a colorful ranking. Its value is a reproducible path from a supplier observation to an accountable client decision.` }
    ]
  },
  {
    slug: 'customer-commitment-register-accuracy-research',
    title: 'Customer Commitment Register Accuracy in Offshore Experience Support',
    excerpt: 'A documentary method for testing whether promised customer actions remain accurate, owned, and reviewable across support channels.',
    published: october5ResearchDate,
    thumbnail: '/aug20-research-heroes/offshore-operations-queue-state-reconstruction.svg',
    cluster: 'Customer Experience',
    stats: ['Primary measure: reconstructable open commitments', 'Sources checked October 5, 2026'],
    serviceHandoff: { href: '/services/customer-experience-support', label: 'Explore Customer Experience Support', body: 'Build a customer support workflow with bounded authority, traceable commitments, and client-side exception ownership.' },
    sources: [
      { name: 'FTC: Solving Problems With a Business—Returns, Refunds, and Other Resolutions', url: 'https://consumer.ftc.gov/articles/solving-problems-business-returns-refunds-and-other-resolutions' },
      { name: 'FTC: Warranties', url: 'https://consumer.ftc.gov/articles/warranties' }
    ],
    sections: [
      { heading: 'Research finding: a promise is a governed record', body: `A customer commitment register should answer five questions without relying on an agent's memory: what the business represented it would do, who was authorized to make that representation, what conditions applied, when the next event was due, and what evidence shows fulfillment or a properly approved change. The register is not a second customer relationship management system and should not become a place where offshore support staff invent remedies. Its purpose is continuity across email, chat, telephone notes, tickets, returns systems, finance queues, and internal handoffs. FTC consumer guidance recommends keeping records and explains that written warranties and stated return or resolution terms matter; it does not define one workflow for every business or resolve a particular dispute. This study therefore tests documentary accuracy rather than legal compliance or customer satisfaction. The central finding is that a commitment becomes operationally reliable only when its exact scope, authority, dependencies, state transitions, and closure evidence remain linked. A generic note such as follow up soon can look reassuring while leaving the next operator unable to act. A precise entry can still be wrong if it contradicts approved policy, omits a condition, or silently changes after the customer relied on it.` },
      { heading: 'Define the population from customer-facing evidence', body: `Begin with a declared period, channel set, product or service boundary, and definition of commitment. Include explicit promises to refund, replace, call back, investigate, provide a document, correct an account, apply a credit, escalate, or respond by a stated time. Include conditional representations when the condition can create a reasonable expectation, such as a refund after receipt and inspection. Exclude greetings, aspirations, automated estimates clearly identified as estimates, and internal tasks never communicated to a customer, but retain the rules behind each exclusion. Build the population from customer-facing messages and recorded call dispositions, then reconcile it against tickets, return authorizations, payment events, shipment records, and escalation queues. Starting only from an existing commitment field will miss promises recorded in free text or made in another channel. Preserve the original wording or a permissioned reference, channel, timestamp, timezone, customer and case identifiers, speaker, authority basis, promised action, due event, conditions, dependency, responsible owner, and current status. Minimize personal and payment data; the register needs a stable reference, not an uncontrolled copy of the entire conversation. If identity matching is uncertain, route the ambiguity instead of joining records by a similar name.` },
      { heading: 'Accuracy protocol and state reconstruction', body: `Freeze the source hierarchy and state definitions before examining outcomes. Suggested states are proposed, authorized, communicated, waiting on customer, waiting on business owner, in execution, fulfilled, superseded with approval, withdrawn with approval, disputed, and unresolved. These states describe evidence, not whether the customer is right. Select a stratified sample containing ordinary cases, high-value remedies, multiple channels, language transfers, reopened tickets, staff changes, deadline commitments, conditional offers, and records marked closed. One reviewer reconstructs the commitment only from authoritative records; a second independently repeats an overlap sample. Compare the exact action, amount or item where applicable, due trigger, deadline, condition, owner, and status. Preserve initial disagreements. Trace forward from the customer-facing statement to execution evidence and backward from refunds, replacements, or callbacks to the statement and authorization that initiated them. Test events arriving out of order and systems that store only date rather than time. A closed ticket is not fulfillment evidence, and a payment request is not a completed refund. Record unavailable evidence as unavailable. Do not infer consent from silence, authority from job title, or completion from elapsed time.` },
      { heading: 'Separate fact, analysis, inference, and decision', body: `Facts include the words communicated, approved policy version, authorization record, system timestamp, delivery scan, refund settlement, and dated owner response. Analysis maps those facts to a predeclared state and identifies gaps. Inference includes explanations for delay, likely customer expectations, or whether two differently worded messages refer to the same promise. Decisions include granting an exception, changing a deadline, offering compensation, interpreting warranty scope, accepting financial or legal exposure, and closing a dispute. The offshore support analyst may prepare facts and analysis but must label uncertainty and send decisions to authorized owners. This separation is especially important when a friendly phrase can be read as an unconditional promise, when policy changed between purchase and contact, or when a supervisor approved a remedy in private chat. Preserve the applicable policy and approval evidence available at the time; do not overwrite the earlier record with today's rule. If later information corrects a factual error, append a correction with its source and time. If the business changes its intended action, record who authorized the change and what customer communication followed. A register that silently edits the original commitment prevents both operational learning and fair review.` },
      { heading: 'Authority and escalation design', body: `A bounded customer experience support role can identify candidate commitments, enter approved fields, check due items, request missing evidence, prepare status updates from source records, and route exceptions. It should not promise a refund, warranty remedy, credit, delivery date, legal outcome, investigation result, policy exception, or compensation beyond explicitly delegated limits. It should not reinterpret ambiguous terms, suppress an overdue item, or change a commitment merely to make a service target appear met. The client instruction must name permissible representations, monetary and nonmonetary approval limits, policy sources, protected data rules, approved channels, timezones, escalation owners, absence coverage, and emergency paths. Conflicting instructions create a visible hold. A customer message can be acknowledged without inventing an answer; the record should distinguish acknowledgement from resolution. Sensitive allegations, threats, safety issues, chargebacks, accessibility needs, privacy requests, and legal notices follow qualified routes rather than the ordinary queue. Access should be limited to the fields and systems needed. Review exports should redact unnecessary content and follow the client's retention rules. These boundaries protect customers while preventing evidence administration from drifting into unapproved commercial judgment.` },
      { heading: 'Challenge cases that expose weak registers', body: `Use a pilot set designed to break simple due-date tracking. A representative says the team will call tomorrow but the customer's timezone differs. A replacement is promised after return receipt, yet the carrier scan and warehouse receipt disagree. A supervisor authorizes a partial refund while a public return policy appears broader. Two agents make incompatible commitments in different channels. An automated message gives an estimate after a human promised a fixed date. A refund is approved but fails at the payment processor. A warranty question depends on product and purchase records the support team cannot interpret. A customer withdraws a request after work has begun. For each case, require the record to preserve original words, applicable authority, condition, clock, ownership, later communication, and final evidence. Include ordinary fulfilled commitments so reviewers do not assume every sampled item is defective. Exercise reassignment during absence and confirm the due item stays visible. Reopen a supposedly closed case when settlement fails. Test whether a customer reply after closure reconnects to the prior commitment rather than starting without context. If the workflow cannot represent one of these cases without misleading simplification, repair its state model before scaling.` },
      { heading: 'Measures and diagnostic interpretation', body: `Measure population capture against independently sampled customer-facing records, not only completion among items already registered. Report commitments with reconstructable wording, valid authority, complete condition, normalized due time, named owner, current evidence, and verified closure. Track unregistered promises, ambiguous deadlines, unauthorized remedies, ownerless items, items hidden by ticket closure, customer-wait versus business-wait time, failed execution after approval, repeated contact before fulfillment, reopened commitments, and corrections after review. Counts need denominators and channel coverage. A low overdue rate may reflect reliable execution, generous deadlines, missing registration, or premature closure. A high reopening rate may reveal poor work, stronger detection, payment failures, unclear customer communication, or a new review rule. Do not rank individual agents from small or noncomparable samples. Segment problems by instruction, authorization, system design, channel integration, staffing coverage, owner response, and execution. Qualitative review should examine severity and contrary cases beside averages. The useful management question is not whether the dashboard is green; it is whether an accountable owner can distinguish a broken promise from a data defect, authorized change, customer dependency, or still-open decision and then correct the responsible part of the process.` },
      { heading: 'Limitations and decision-ready output', body: `This documentary method cannot prove that every spoken or informal representation was captured, that a customer understood a message as intended, or that a completed operational event resolves a legal or contractual obligation. Call recording availability, transcription quality, channel retention, system clocks, identity matching, payment settlement, and shipment updates can all create gaps. Sampling may miss rare severe cases, and later customer evidence can change the interpretation. FTC materials offer general consumer information and do not certify this design, determine governing law, or establish the appropriate remedy in a specific matter. Findings from one queue, period, language, product, or company do not generalize automatically. Report exclusions, inaccessible sources, clock assumptions, policy changes, reviewer disagreements, and unresolved cases with every accuracy rate. A decision-ready output contains the population definition, source map, field dictionary, authority matrix, sampled records, agreement results, exception register, owner decisions, verified closures, and correction history. That package lets a client choose whether to expand the workflow, repair channel capture, clarify delegation, change absence coverage, obtain qualified advice, or pause. The outcome is reliable continuity and accountable review, not a claim that all customer obligations have been satisfied.` }
    ]
  }
];
