import type { ResearchPost } from './fleet-data';

export const september28ResearchDate = '2026-09-28';
type Section = {heading:string; body:string};
type Study = {slug:string; title:string; excerpt:string; cluster:string; service:string; label:string; stats:string[]; sources:{name:string;url:string}[]; sections:Section[]};

const commonSources = [
  {name:'NIST: Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST: SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippine National Privacy Commission: Implementing Rules and Regulations',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
  {name:'U.S. GAO: 2025 Green Book',url:'https://www.gao.gov/greenbook'}
];

const sharedSections: Section[] = [
  {heading:'How to run the pilot',body:`Treat this as a bounded workflow study, not a promise about a provider, a location, or future performance. Freeze the written procedure, authority table, source register, sample window, exclusions, and scoring rubric before looking at outcomes. Include ordinary cases, returned work, aged exceptions, and abandoned records; a sample of successful closures alone cannot reveal where judgment or evidence escaped the workflow. Have two reviewers independently score an overlap sample and retain their initial disagreements. A reconciled score without the pre-reconciliation result can hide an ambiguous rubric. Record missing data as missing rather than treating silence as a pass. Use named accounts, least-necessary access, approved systems, and redacted or synthetic training examples. The client owner keeps consequential approval authority. The support role may collect, compare, prepare, document, and route only the actions stated in the role brief. A complete escalation is a correct outcome when evidence or authority is absent.`},
  {heading:'Interpreting results and uncertainty',body:`Report counts and denominators beside every percentage, split routine and exception cohorts, and show the distribution rather than only an average. Separate active handling time from time waiting on a requester, system, or client owner. Facts are the captured records, timestamps, versions, and reviewer observations. Analysis is the consistent application of the declared rubric. Explanations for failure remain hypotheses unless the design tests them. One period can miss seasonality, policy changes, rare high-impact events, and work completed outside the system. Source documents can also be incomplete or updated after the event. The cited authorities provide control, privacy, consumer, and security principles; they do not certify a client workflow or establish legal compliance. Management should repeat a focused sample after any material change in process, permissions, systems, policy, case mix, or staffing and should state the checked date when reusing these findings.`},
  {heading:'Decision gate for delegation',body:`Proceed only if a new reviewer can reconstruct the request, governing source, permitted action, operator work, owner decision, and correction history without relying on memory or private chat. The operating packet should name the queue, source of truth, required fields, stop conditions, prohibited actions, safe holding state, escalation destination, response expectation, and review owner. Expansion is reasonable when both routine work and difficult cases remain attributable and reviewable, access matches the approved duties, and repeated exceptions lead to a process correction rather than improvisation. Pause when instructions conflict, the source version is uncertain, privileged access is broader than the role, evidence is routinely copied into uncontrolled tools, or workers are rewarded for closing records they should escalate. These gates turn the study into a staffing decision while keeping business judgment with the accountable client owner.`}
  ,{heading:'Source discipline and review cadence',body:`Record each source title, publisher, URL, version when available, and the date checked. A source register should explain which proposition or control each reference informs; a long bibliography does not substitute for claim-level reasoning. Recheck links and governing internal documents before a later pilot because public guidance and client procedures can change. During launch, review a small mixed sample each day so instruction defects are corrected before they spread. Move to a weekly cadence only after exception handling is stable. The weekly review should show open questions, owner response delays, rubric disagreements, access issues, and corrective actions with named owners and dates. Close a corrective action only when a follow-up sample demonstrates the intended change. Preserve contrary examples, since they often reveal a boundary that an aggregate score hides.`}
];

const studies: Study[] = [
  {
    slug:'philippines-crm-duplicate-account-merge-readiness-study', title:'CRM Duplicate-Account Merge Readiness in Philippines Revenue Operations', cluster:'Workflow Design', service:'/services/revenue-operations-support', label:'Explore Revenue Operations Support',
    excerpt:'A decision-grade study for testing whether a support team can prepare possible CRM duplicates without erasing account history or assuming merge authority.',
    stats:['Primary measure: reviewer-confirmed candidate packets','Sources checked September 28, 2026'],
    sources:[...commonSources,{name:'NIST: Privacy Framework',url:'https://www.nist.gov/privacy-framework'}],
    sections:[
      {heading:'Executive finding',body:`Duplicate-account preparation is suitable for a bounded revenue-operations role; deciding that two records represent the same customer is not. The useful unit is a candidate packet containing the two record identifiers, match signals, contradictory fields, relationship history, open opportunities, consent evidence, ownership, and downstream dependencies. A name or email match is only a lead. Shared domains, subsidiaries, franchise locations, name changes, recycled phone numbers, and test records create plausible false positives. The safest design lets the support role surface candidates and preserve both histories while a designated CRM or account owner accepts, rejects, or requests more evidence. Success is not the number of records merged. It is the proportion of candidates whose evidence, conflicts, and likely downstream effects are complete enough for an authorized reviewer to decide without redoing discovery.`},
      {heading:'Research question and population',body:`The study asks whether candidate discovery can reduce CRM disorder without moving identity judgment into the preparation role. Build a population from exact and fuzzy duplicate alerts, manually reported duplicates, parent-child conflicts, reopened records, lead conversions, imports, and previously rejected candidates during one fixed window. Exclude training records only through a rule declared in advance. Capture stable record IDs, creation source and time, normalized and original names, domains, permitted contact fields, legal entity or location clues, account owner, consent and suppression state, opportunities, cases, contracts, integration keys, and the rule that created the alert. Never copy unrestricted customer data to a spreadsheet merely for convenience. The CRM owner defines which fields may be compared and which destinations are approved for review.`},
      {heading:'Candidate-specific method',body:`Stratify by alert type because an exact external identifier is different from a fuzzy company-name match. Sample accepted, rejected, unresolved, and auto-created candidates. Reviewers first classify whether the packet is complete, then independently decide same entity, related entity, different entity, or insufficient evidence. Preserve that distinction: related entities are not duplicates. For confirmed pairs, map what a merge would do to ownership, activity chronology, opt-outs, open pipeline, support cases, invoices, integrations, and reporting. Run the method in read-only mode during the pilot; no record should be merged to prove that a packet is reviewable. Compare reviewer agreement by rule and investigate clusters of disagreement. A rule that creates many ambiguous candidates may need revised blocking criteria rather than more operator coaching.`},
      {heading:'Measures and failure analysis',body:`The primary measure is reviewer-confirmed candidate-packet completeness: required evidence present, contradictions visible, downstream effects listed, and authority correctly routed. Report precision by alert rule, insufficient-evidence rate, reviewer agreement before discussion, candidate age, owner waiting, and false-positive categories. Track whether the same pair reappears after rejection, which exposes weak suppression or unstable identifiers. Failure modes include treating a shared domain as identity, discarding the losing record’s chronology, moving an opt-out, assigning an opportunity to the wrong owner, combining subsidiaries, losing an integration key, or allowing the preparer to approve the merge. If completeness is low, locate whether the cause is missing source access, ambiguous field definitions, poor import provenance, or a flawed matching rule. Do not infer worker quality from alert precision when the system generated the candidate population.`},
      {heading:'Worked boundary cases',body:`A company rebrand with the same registration evidence, contract chain, and account owner may be a strong candidate, but the reviewer still owns the decision and migration plan. Two clinics with a shared procurement email but different addresses, contracts, and service cases are related records, not an obvious merge. A lead converted twice after separate webinar imports may be duplicated, yet consent timestamps and campaign attribution must survive any correction. An acquired business may need a parent-child relationship rather than identity collapse. A person who moved employers can share a phone number across organizations without making the employer accounts equal. These cases belong in training because they force the operator to expose uncertainty instead of maximizing candidate volume.`},
      {heading:'Implementation packet',body:`Before launch, the revenue-operations owner should supply a record map, permitted comparison fields, definitions for same and related entities, examples of rejected matches, integration dependencies, and a reversible merge procedure owned by an administrator. The queue needs explicit states for new, researching, insufficient evidence, awaiting owner, accepted, rejected, and completed. Rejected pairs need a durable reason so the matcher does not recreate useless work. Quality review should trace a candidate from the generating rule through owner decision and any administrator action. Weekly reporting should show which rules create volume, ambiguity, and downstream risk. If an accepted merge later proves wrong, preserve the incident, recovery steps, affected objects, and rule change. That feedback is more useful than quietly repairing the account because it distinguishes a preparation error from a reviewer decision or a system defect.`}
    ]
  },
  {
    slug:'offshore-accounts-payable-approval-chain-integrity-research', title:'Accounts-Payable Approval-Chain Integrity in Offshore Finance Support', cluster:'Hiring Controls', service:'/services/finance-operations-support', label:'Explore Finance Operations Support',
    excerpt:'A controlled method for testing whether invoice packets preserve purchase, receipt, and approval evidence before payment decisions.',
    stats:['Primary measure: approval-ready packet integrity','Sources checked September 28, 2026'],
    sources:[...commonSources,{name:'GAO/CIGIE: Financial Audit Manual, Volume 1',url:'https://www.gao.gov/products/gao-22-105894'}],
    sections:[
      {heading:'Executive finding',body:`An offshore finance-support role can assemble and reconcile an invoice packet when authorization and payment release remain segregated. The deciding evidence is not a status called approved. It is a traceable chain linking the supplier record, purchase authorization, goods or service receipt, invoice, exception handling, designated approver, and payment state. GAO control guidance is written for government environments, so it is not a private-company compliance rule; its distinctions among authorization, processing, recording, review, and asset custody are nevertheless useful design inputs. The support role should identify missing or conflicting evidence and route it. It should not create a purchase order after the fact, change supplier banking details, decide materiality, approve an exception, post an unsupported entry, or release funds.`},
      {heading:'Population and evidence map',body:`Build the population from invoices received in a fixed period, including purchase-order and non-purchase-order items, partial receipts, recurring services, credits, duplicates, urgent requests, rejected packets, and invoices placed on hold. Capture invoice identifier, supplier master ID, legal entity, currency, amount, tax fields as defined by the client, purchase reference, receipt or service acceptance, contract reference, requester, cost owner, approval path and version, timestamps, exception reason, and final disposition. Preserve the original file and inbound channel. A forwarded email is not automatically authority, and a typed approver name is not proof of an attributable decision. Bank-detail changes should follow a separately controlled verification path and must never be normalized as routine invoice preparation.`},
      {heading:'Method for chain reconstruction',body:`Create strata for clean matches, quantity or price variances, missing receipts, missing purchase references, new suppliers, changed payment instructions, duplicates, credits, and manual overrides. For each item, reconstruct the sequence from receipt to final state using system events rather than recollection. Compare invoice terms with the approved source, identify who could request, approve, record, and release the transaction, and flag incompatible combinations. Reviewers independently decide whether the packet is approval-ready, incomplete, contradictory, or outside scope. For a prospective pilot, the preparer places incomplete work into a visible hold state and sends a structured question to the named owner. Test whether the case resumes with the owner response attached instead of being rebuilt in private messages.`},
      {heading:'Measures that expose control quality',body:`The primary measure is approval-ready packet integrity: correct supplier and entity, source invoice preserved, required match evidence present, variance visible, valid approver attributable, and no prohibited action by the preparer. Report first-pass completeness, duplicate-detection yield, holds by reason, packets returned after approval review, owner waiting, active preparation time, and percentage involving a manual override. Separately count potential segregation conflicts and bank-change cases. A low cycle time can be harmful if it comes from bypassed receipts or retrospective approvals. Conversely, a longer queue can reflect appropriate holds. Compare failure rates by intake channel and invoice type before blaming the operator; mailbox routing, contract access, and receipt discipline may dominate the result.`},
      {heading:'Worked tests and stop rules',body:`A recurring software invoice with a current contract still needs the client’s declared acceptance and approval route; recurrence does not grant standing authority to the preparer. A price variance within a system tolerance may route automatically only if the rule and version are documented. An urgent executive email does not erase required controls. A credit note should link to the original obligation and should not be treated as cash or an independent purchase. Two invoices with different numbers but the same supplier, amount, date, and underlying service deserve review rather than automatic deletion. Any changed bank instruction, suspected identity mismatch, unsupported manual journal request, or request to split an amount around an approval threshold triggers the client’s designated escalation path.`},
      {heading:'Operating design after the study',body:`The finance owner should convert the observed failure reasons into a field dictionary and route matrix rather than a larger collection of informal reminders. Each hold code should identify the missing evidence, responsible owner, expected next action, and whether the invoice clock continues under client policy. Dashboards should distinguish prepared, approval-ready, approved, scheduled, and paid; collapsing those states makes it impossible to locate delay. Reviewer sampling should include cleared exceptions and payments stopped before release. Access review should confirm that preparers cannot edit supplier payment instructions or release the items they assembled. When a rule changes, record its effective time and test invoices on both sides of the boundary. The study supports expansion only if a replacement reviewer can reproduce the packet and if an absent approver does not cause staff to route around the authority model.`}
    ]
  },
  {
    slug:'philippines-customer-refund-escalation-packet-study', title:'Customer Refund Escalation Packets in Philippines Support', cluster:'Workflow Design', service:'/services/customer-experience-support', label:'Explore Customer Experience Support',
    excerpt:'A source-backed study of whether refund requests reach authorized owners with the customer’s request, transaction evidence, and policy context intact.',
    stats:['Primary measure: decision-ready escalation packets','Sources checked September 28, 2026'],
    sources:[...commonSources,{name:'FTC Consumer Advice: Returns, Refunds, and Other Resolutions',url:'https://consumer.ftc.gov/articles/solving-problems-business-returns-refunds-and-other-resolutions'},{name:"FTC: Mail, Internet, or Telephone Order Merchandise Rule Business Guide",url:'https://www.ftc.gov/business-guidance/resources/business-guide-ftcs-mail-internet-or-telephone-order-merchandise-rule'}],
    sections:[
      {heading:'Executive finding',body:`Refund-support preparation is delegable when the role faithfully records what the customer requested, locates the applicable client policy and transaction evidence, and routes any decision outside a narrow written rule. It fails when speed targets encourage an agent to reinterpret the request, promise an outcome, invent eligibility, or hide repeat contact. FTC consumer material emphasizes keeping transaction documents and records of contacts; specific legal duties vary by transaction and jurisdiction, so client legal or policy owners must set the governing rule. A decision-ready escalation should let the authorized owner see the customer’s words, verified account and order, amount and payment path, delivery or service evidence, prior contacts, applicable policy version, requested remedy, and precise unresolved question.`},
      {heading:'Cohort and field design',body:`Study refund, return, exchange, credit, cancellation-linked, failed-delivery, duplicate-charge, partial-service, warranty, and disputed-resolution contacts received through defined channels during one period. Include repeat contacts and requests closed without payment, not only completed refunds. Capture the original message or faithful transcript, received time, channel, identity-verification result, account and transaction references, product or service, amount and currency, tender type, fulfillment evidence, relevant dates, policy version, prior promises, agent action, escalation owner, decision, and confirmation. Minimize personal and payment data: store references in controlled systems rather than copying full credentials into research sheets. Failed identity verification is a state requiring a safe route, not permission to disclose account details.`},
      {heading:'Method centered on instruction fidelity',body:`First classify what the customer actually asked for without deciding entitlement. Then compare the packet with the client’s versioned policy and authority table. Reviewers score whether the request, chronology, evidence, policy route, prior commitments, and open question are preserved. Independently classify each case as executable under a narrow rule, owner decision required, identity incomplete, evidence incomplete, or outside scope. Sample ordinary requests, high-value cases, partial remedies, repeated contacts, charge disputes, and requests near deadlines. For prospective testing, use a holding response approved by the client and observe whether the packet receives a decision without a second discovery interview. A second interview may signal a poor packet; it may also reflect new facts, so reviewers must code the reason.`},
      {heading:'Measures and interpretation',body:`The primary measure is decision-ready escalation completeness. Secondary measures are instruction-fidelity errors, missing-transaction evidence, wrong policy versions, unsupported promises, repeat-contact rate, rework reason, owner waiting, active handling, and time from authorized decision to confirmation. Report outcomes by request type and channel. Do not call every denied request an agent error, and do not call every issued refund correct; the study evaluates evidence and authority, not customer satisfaction or legal compliance. Inspect whether certain policy clauses generate disagreement, whether identity steps cause abandonment, and whether owners answer the question asked. If agents frequently paraphrase away important qualifiers such as partial, end-of-term, or original payment method, redesign the intake fields and examples.`},
      {heading:'Boundary examples',body:`“Cancel the renewal but keep this month” is not equivalent to immediate account closure. “I did not receive one item” is not a request to reverse the entire order. A customer who asks when a refund will arrive may already have an approved transaction; the task is status confirmation, not a new eligibility decision. A request after a stated deadline may still require an owner review for exceptions, applicable rights, or prior promises, but the support role should not invent the result. A chargeback notice, suspected account takeover, threat of harm, legal demand, or request exposing sensitive payment data follows the client’s specialist escalation route. Training should reward accurate restatement and a precise owner question rather than persuasive improvisation.`},
      {heading:'Service design implications',body:`Turn recurring packet defects into changes at intake. If customers omit order identifiers, provide a secure lookup path rather than asking them to resend sensitive data. If agents choose the wrong policy, show the version and effective date in the workspace. If owners repeatedly ask for the same chronology, generate it from events while preserving the customer’s original message. Response templates should distinguish acknowledgement, request for information, authorized decision, and transaction confirmation; one generic “resolved” message cannot do all four jobs. Calibration should use cases where the requested remedy differs subtly from the final outcome. Reviewers should check that confirmation matches the owner decision and payment state. The client should also define what happens when the owner misses the response target, because silently expanding agent authority is not a safe queue-management strategy.`}
    ]
  },
  {
    slug:'offshore-vendor-sla-breach-evidence-readiness-research', title:'Vendor SLA Breach Evidence Readiness in Offshore Procurement Support', cluster:'Scope Benchmarks', service:'/services/procurement-administration', label:'Explore Procurement Administration',
    excerpt:'A practical study for determining whether vendor-performance exceptions can be reconstructed without letting a support role interpret contracts or assert breach.',
    stats:['Primary measure: contract-owner-ready exception records','Sources checked September 28, 2026'],
    sources:[...commonSources,{name:'CISA: ICT Supply Chain Risk Management Resources',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/information-communications-technology-supply-chain-risk-management'}],
    sections:[
      {heading:'Executive finding',body:`A procurement-support role can collect service evidence and prepare an exception record, but it should not declare breach, waive performance, calculate a contractual remedy, or send a legal notice. The difficult work is aligning observations with the correct agreement, service, measurement window, exclusions, and notice path. A dashboard that shows red is not self-interpreting. Maintenance windows, customer-caused delay, dependencies, time-zone definitions, amendments, and data-source gaps can change what the record means. The decision-grade output is therefore a contract-owner-ready packet: governing document and version, cited service term, raw measurement, calculation steps, exception context, correspondence, business impact supplied by the owner, unresolved uncertainty, and the decision requested.`},
      {heading:'Define the review universe',body:`Inventory active vendor-service combinations and the governing contract, statement of work, service schedule, amendments, and named owner. Select one fixed measurement period and include met targets, suspected misses, disputed measurements, missing reports, excused events, and unresolved prior exceptions. Capture service identifier, metric definition, target, clock and timezone, source system, numerator and denominator, excluded intervals, incident references, vendor report, internal observations, notice deadline, communication record, and owner disposition. Do not place full contracts or sensitive security logs in an uncontrolled analysis file. Use document references and permissions that match the role. If two documents conflict or an amendment cannot be located, the record stops for contract-owner review.`},
      {heading:'Reperformance method',body:`Stratify exceptions by metric: availability, response, resolution, delivery, quality, capacity, or another client-defined term. For each sampled record, a reviewer should reproduce the calculation from raw evidence under the documented definition. Compare internal and vendor timestamps, clock boundaries, maintenance classifications, and dependencies. Preserve both versions when they disagree. A second reviewer independently decides whether the packet is reproducible and whether it routes to the correct owner; neither reviewer declares legal breach. In a prospective pilot, prepare the packet before the notice deadline and measure how often the owner can decide without requesting missing documents. Test a few non-breach periods too, because a method that only examines red alerts cannot reveal false positives.`},
      {heading:'Measures and diagnostic cuts',body:`The primary measure is contract-owner-ready exception rate: correct governing term, complete measurement inputs, reproducible calculation, exclusions identified, source links intact, and a precise decision request. Report source-agreement rate, calculation disagreement, missing-report frequency, exceptions found after a notice deadline, owner rework, unresolved age, and active preparation versus waiting time. Slice results by vendor, service, metric type, and data source without publishing unsupported league tables. A high count of suspected misses may reflect one unstable telemetry feed. A low count may reflect missing monitoring. Examine denominator choices and timezone handling before drawing a performance conclusion. Record every manual adjustment and who authorized its use.`},
      {heading:'Scenarios that protect the boundary',body:`An outage spanning midnight can fall into different reporting months depending on the agreement’s timezone; the support role presents both timestamps and cites the term. A vendor’s maintenance label is evidence, not automatic exclusion. Slow response caused by a missing customer contact still requires the dependency and communication chronology. If an amendment changes a target mid-period, divide the analysis or ask the owner how to apply it. A service credit table does not authorize the preparer to invoice or net a payment. Cybersecurity concerns, suspected falsified reports, disputed contract language, material business impact, or a looming notice deadline should follow the client’s urgent escalation route rather than wait for a routine monthly summary.`},
      {heading:'From monthly report to managed queue',body:`A reliable exception queue should link every observation to a vendor-service record and governing-document reference. States should distinguish suspected miss, evidence incomplete, calculation reproduced, owner review, vendor response, disputed, accepted, and closed. Closure needs the owner’s disposition and any follow-up action; the arrival of a vendor reply is not closure. Assign ownership for telemetry gaps separately from vendor-performance questions. Trend reporting should retain individual event references and should show denominator changes, missing periods, and definition changes beside the chart. Review a sample of green periods to detect calculations that systematically suppress alerts. Before scaling the offshore role, verify that notice calendars, contract access, and sensitive operational logs have appropriate permissions and backups. The goal is a dependable evidence path, not a support team that negotiates commercial terms by implication.`}
    ]
  },
  {
    slug:'philippines-employee-offboarding-evidence-continuity-study', title:'Employee Offboarding Evidence Continuity in Philippines Shared Services', cluster:'Hiring Controls', service:'/services/shared-services-administration', label:'Explore Shared Services Administration',
    excerpt:'A privacy-aware study of whether offboarding tasks remain attributable across HR, application, asset, and manager handoffs.',
    stats:['Primary measure: evidence-complete offboarding chain','Sources checked September 28, 2026'],
    sources:[...commonSources,{name:'CISA: Cybersecurity Performance Goals',url:'https://www.cisa.gov/cyber-guidance/cybersecurity-performance-goals'}],
    sections:[
      {heading:'Executive finding',body:`Offboarding coordination is suitable for a shared-services role when employment decisions, access ownership, payroll judgment, investigations, and exception acceptance stay with designated client owners. The coordinator’s job is to translate an authorized event into an attributable chain of tasks and expose anything that remains open. A closed ticket is weak evidence if application access, shared secrets, devices, forwarding rules, physical credentials, vendor portals, and data custody are scattered across unlinked systems. The primary outcome should be an evidence-complete chain from authoritative instruction through owner-confirmed disposition, not a promise that every action happens instantly. Timing requirements differ by risk, contract, system, and client policy; management must define them rather than allowing the coordinator to improvise.`},
      {heading:'Events, systems, and minimum data',body:`Build a population of voluntary departures, involuntary departures, end-of-contract events, internal transfers, leaves, rescinded departures, and records reopened because an account or asset was found later. Capture the authoritative event reference, effective time and timezone, employment state, manager and HR owner, worker identifier, system and asset inventory source, application owner, entitlement or device, required action, due time, performer, completion evidence, exception, owner acceptance, and verification result. Apply data minimization: the coordination record needs the instruction and task state, not sensitive reasons for departure. Restrict visibility for high-risk events. The support role should never originate a termination, infer it from rumor, or change an effective time without authoritative instruction.`},
      {heading:'Chain-of-custody methodology',body:`Map the event flow from the authoritative people record to identity, application, facility, equipment, vendor, and knowledge-transfer owners. Stratify by event type, privilege level, worker type, and whether the system is connected to centralized identity management. Sample completed, late, cancelled, transferred, and exception-accepted tasks. Reviewers reconstruct who knew what and when, which source triggered each action, and what evidence proves the final state. For access, distinguish request submitted, session revoked, account disabled, entitlement removed, token recovered, and owner verification; those are not interchangeable. For assets, record custody and exception decisions without asking the coordinator to accuse a worker of loss. Test reinstatement and rescinded departures because reversal paths often reveal destructive or irreversible automation.`},
      {heading:'Measures that matter',body:`The primary measure is evidence-complete offboarding continuity: authoritative trigger, full in-scope inventory, named owners, attributable actions, visible exceptions, and final verification. Report task completion by risk tier, median and upper-percentile owner waiting, accounts discovered after closure, stale shared credentials, assets without custody evidence, incorrect actions on transfers, cancelled tasks not reversed, and reviewer agreement. Separate system automation time from manual-owner time. A fast average can conceal one privileged account left open, while one delayed low-risk archive can distort a small sample. Avoid turning the study into surveillance or an individual productivity ranking. Diagnose gaps in inventory, integration, ownership, timing rules, or evidence definitions before attributing them to the coordinator.`},
      {heading:'Boundary and recovery cases',body:`An internal transfer may require entitlement review rather than wholesale deletion. A leave may require temporary suspension and a documented restoration owner. A rescinded departure tests whether queued actions can be stopped and whether already completed steps can be safely reversed. A departing administrator may control service accounts or secrets that do not appear in the personal account inventory; the security owner must direct rotation and continuity. Forwarding email, exporting a mailbox, retaining personal data, withholding final pay, accepting an unreturned device, or preserving material for litigation are owner decisions under client policy and applicable advice. The coordinator records and routes these questions. It does not make them disappear by marking the parent ticket complete.`},
      {heading:'Launch controls and ongoing review',body:`The launch packet should contain event types, authoritative triggers, timing tiers, system and asset owners, permitted coordinator actions, restricted data, cancellation procedures, and examples for transfer, leave, rescission, and privileged departure. Run tabletop tests before using a live high-risk event. One test should inject a late-discovered application; another should reverse the departure after actions are queued. Daily launch review should focus on overdue high-risk tasks and conflicting instructions. Weekly review should reconcile the population of departure events to the coordination queue and inspect a mixed sample of completed and exception-accepted records. Periodic access review should confirm that coordinators can observe task evidence without acquiring the administrative powers they coordinate. When an owner accepts a delay or retention exception, record the scope and review date so an exception does not become a permanent hidden entitlement.`}
    ]
  }
];

export const september28ResearchPosts: readonly ResearchPost[] = studies.map((study) => ({
  slug:study.slug,title:study.title,excerpt:study.excerpt,published:september28ResearchDate,thumbnail:'/research/research-default.svg',cluster:study.cluster,stats:study.stats,
  sections:[...study.sections,...sharedSections],sources:study.sources,
  serviceHandoff:{href:study.service,label:study.label,body:'Turn this research into a bounded Philippines-based role brief with documented authority, source access, examples, review, and escalation.'}
}));
