export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'shared-services-administration', title: 'Shared Services Administration', desc: 'Build a Philippines-based shared services administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-experience-support', title: 'Customer Experience Support', desc: 'Build a Philippines-based customer experience support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'finance-operations-support', title: 'Finance Operations Support', desc: 'Build a Philippines-based finance operations support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'revenue-operations-support', title: 'Revenue Operations Support', desc: 'Build a Philippines-based revenue operations support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'procurement-administration', title: 'Procurement Administration', desc: 'Build a Philippines-based procurement administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'data-management-support', title: 'Data Management Support', desc: 'Build a Philippines-based data management support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'marketing-operations-support', title: 'Marketing Operations Support', desc: 'Build a Philippines-based marketing operations support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'technical-support-desk', title: 'Technical Support Desk', desc: 'Build a Philippines-based technical support desk workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'project-coordination-support', title: 'Project Coordination Support', desc: 'Build a Philippines-based project coordination support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'back-office-quality-review', title: 'Back-Office Quality Review', desc: 'Build a Philippines-based back-office quality review workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring offshore operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
