import type { ResearchPost } from './fleet-data';

const src = (name: string, url: string) => ({ name, url });

const august18ResearchBatchAll: readonly ResearchPost[] = [
  {
    slug: 'philippines-offshore-ticket-triage-consistency', title: 'Ticket Triage Consistency in Philippines-Based Support', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Scope Benchmarks',
    excerpt: 'A study of whether a distributed support role sorts incoming requests consistently when priority, ownership, and evidence rules are tested together.',
    stats: ['Triage quality is a classification question before it is a speed question', 'A priority label needs evidence and an owner, not only a color'],
    sections: [
      { heading: 'Research question', body: 'When a Philippines-based support operator receives the same type of request under different conditions, do the triage decisions remain consistent? The practical issue is not whether every ticket receives the same priority. A security incident, a blocked customer request, and a routine administrative question should not land in the same queue. The issue is whether the differences follow an approved rule that another reviewer can understand. This study treats triage as a bounded classification task. It does not treat the country of the operator as an explanation for any result.' },
      { heading: 'Evidence scope and method', body: 'Build a test set from synthetic or redacted tickets that covers ordinary requests, missing information, competing urgency signals, and a request that requires client authority. Give the operator the same current rubric and record the selected queue, priority, reason, evidence link, and escalation owner. Repeat a small subset later to check stability. NIST incident-handling guidance supports recording classification and escalation decisions. NIST access-control guidance supports limiting the operator to the systems needed to classify work. The test measures the stated process, not general judgment.' },
      { heading: 'What to measure', body: 'Separate agreement with the approved rubric from agreement between two people. A reviewer can disagree with the rubric itself, which is a rule-design problem. Record false urgency, missed urgency, unsupported priority changes, and tickets parked without a next owner. Also record the time spent waiting for a missing field. That prevents a data-quality problem from being counted as slow triage. A short queue may hide inconsistency, so include cases from each status and sample returned tickets as well as accepted ones.' },
      { heading: 'Operational interpretation', body: 'If decisions differ because the rubric uses vague terms such as urgent or important, revise the rule before coaching the operator. If the evidence is present but the classification changes, inspect examples and reviewer calibration. If the operator correctly stops on a request that needs a client decision, count that as controlled completion. The role can collect facts, apply the approved category, and route the exception. It should not promise a resolution or change a customer-impacting priority without authority.' },
      { heading: 'Limitations', body: 'A test set cannot represent every customer phrase or every incident. Repeated cases may also teach the answer rather than test transfer. Ticket timestamps can be incomplete, and the approved rule may change during the sample period. The result therefore applies to the task, rubric, tools, and evidence window that were examined. It does not prove that a person will classify every future request correctly or that a particular queue design will reduce response time.' },
      { heading: 'Evidence-led conclusion', body: 'A support triage role is ready when its decisions can be traced to a current rule, the evidence is visible, and the next owner is named when the role reaches its boundary. Managers should report disagreement by cause instead of publishing one blended accuracy score. That view tells them whether to repair the rubric, improve intake fields, or provide role-specific coaching. The useful outcome is a repeatable classification record, not a claim about nationality, personality, or innate ability.' },
      { heading: 'FAQs', body: 'Should the operator set the priority? Only within an approved rubric and with an escalation path for exceptions. Is speed enough to judge triage? No. A fast unsupported classification can create more work and risk. Should customer tone affect priority? Only where the client has defined an observable service or safety condition. Do public labor statistics validate triage skill? No. They provide context, not an individual capability finding.' }
    ], sources: [src('NIST Computer Security Incident Handling Guide', 'https://csrc.nist.gov/pubs/sp/800/61/r2/final'), src('NIST Access Control guidance', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('Philippine Statistics Authority Labor Force Survey', 'https://psa.gov.ph/statistics/labor-force-survey')]
  },
  {
    slug: 'philippines-offshore-knowledge-base-findability', title: 'Knowledge-Base Findability for Philippines Support Teams', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Workflow Design',
    excerpt: 'How to test whether a support operator can find the current answer, identify uncertainty, and avoid treating search as permission to guess.',
    stats: ['A searchable page is not necessarily an approved source', 'Findability should be tested with version, ownership, and stop rules'],
    sections: [
      { heading: 'Research question', body: 'Can a Philippines-based support operator find and use the current approved answer when a knowledge base contains similar, old, or conflicting pages? This is a research question about retrieval and authority, not a test of memory. In a distributed workflow, an answer that sounds plausible can still be wrong if its source is obsolete. The study asks whether the operator can show the source, its effective status, and the reason it applies to the request.' },
      { heading: 'Method and evidence', body: 'Prepare a controlled set of questions using redacted or synthetic cases. Include a clear answer, a page with an older version, two pages that appear to conflict, and one case with no approved answer. Record search terms, selected source, version or effective date, response, and escalation. NIST configuration-management guidance supports identifying the current approved configuration. NIST privacy guidance helps define what must not be pasted into a search field. The method examines the knowledge system and role instructions together.' },
      { heading: 'Findings that matter', body: 'A successful search has several parts. The operator locates the source, confirms that it is current, answers only within the source, and preserves the link or identifier for review. A failed search is not always an operator failure. It may show duplicate titles, missing effective dates, weak indexing, or an owner who has not retired an old page. Code each failure by retrieval, governance, interpretation, or authority. That classification gives the client a repair path.' },
      { heading: 'Role boundary', body: 'The operator may summarize an approved policy and ask the owner to resolve a conflict. The operator should not create a new customer promise merely because the search returns no result. Nor should a convenient internal message silently become the authoritative page. A safe response can say that the request is pending owner confirmation. This may leave the ticket open longer, but it keeps the decision with the person authorized to change the policy.' },
      { heading: 'Limitations', body: 'A controlled question set cannot capture every accent, spelling variation, product term, or unusual customer description. Search ranking changes as pages are edited. A result also depends on the permissions available to the role, so a failure may reflect access design rather than content. Publish the test date and source versions. Repeat after a major taxonomy change, migration, or policy update instead of treating one pass as permanent evidence.' },
      { heading: 'Evidence-led conclusion', body: 'Findability is reliable only when the current source is identifiable and uncertainty has a defined route. A manager should measure the proportion of cases with a traceable source, the number of stale pages encountered, and the time needed to resolve conflicts. The goal is not to make an operator answer every question. It is to make the right answer easier to verify and the wrong guess harder to publish.' },
      { heading: 'FAQs', body: 'Is a search result enough evidence? No. Check the page owner and effective version. Should operators edit the knowledge base? Only if that responsibility is explicit and reviewed. What should happen when two policies conflict? Pause the customer commitment and escalate to the policy owner. Can a high search success rate prove answer quality? No. Sample the answer against its source.' }
    ], sources: [src('NIST Configuration Management', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('NIST Privacy Framework', 'https://www.nist.gov/privacy-framework'), src('World Bank Philippines Digital Economy Report', 'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf')]
  },
  {
    slug: 'philippines-offshore-data-entry-exception-rate', title: 'Exception Rates in Philippines-Based Data Entry', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Scope Benchmarks',
    excerpt: 'A method for reading data-entry exceptions without confusing source defects, unclear rules, and operator mistakes.',
    stats: ['An exception rate needs a defined denominator and reason code', 'A blocked record is evidence about the input path, not automatically about the operator'],
    sections: [
      { heading: 'Research question', body: 'What does an exception rate in Philippines-based data entry actually measure? A row that cannot be completed may have a missing source, a duplicate, an unclear field rule, a permission limit, or an execution error. Treating all of these as the same defect produces a poor training decision and may encourage staff to fill gaps with guesses. This study asks whether the workflow records enough detail to distinguish those causes.' },
      { heading: 'Method', body: 'Select a defined period and a representative sample of new, edited, accepted, returned, and blocked records. For each item, capture the source, required fields, rule applied, action taken, exception code, reviewer decision, and final disposition. Use NIST measurement guidance to keep the denominator stable and NIST least-privilege guidance to test whether the role could access only the information needed. Do not place live personal data in a research worksheet. Use masked identifiers or links to the approved record.' },
      { heading: 'Reading the rate', body: 'Report separate rates for missing input, source conflict, duplicate handling, rule ambiguity, permission block, and confirmed execution error. A high missing-input rate points toward intake design. A high rule-ambiguity rate points toward the procedure. A high execution-error rate may justify coaching, but only after the instruction and sample are clear. Show counts alongside percentages because a small denominator can make one item look like a trend. Include returned items, since accepted-only sampling hides the work that creates rework.' },
      { heading: 'Niche application', body: 'For shared services, finance administration, CRM maintenance, and publishing support, the safe response to an exception differs. A data operator can flag a duplicate or attach a source. An authorized owner may need to decide whether a payment record, customer field, or public claim is correct. The role brief should name each stop condition. Completion means a clean record or a useful escalation packet, not a populated field at any cost.' },
      { heading: 'Limitations', body: 'Reason codes can be applied inconsistently, especially when a reviewer sees only the final row. Historical exports may omit the original source or timestamp. Some errors are discovered after acceptance, which changes the observed rate. The study also cannot use a general labor statistic to infer an individual operator’s data skill. Recheck the classification scheme after the first review cycle and document any change to the denominator.' },
      { heading: 'Evidence-led conclusion', body: 'An exception rate becomes useful when it explains what the workflow made difficult. Managers should ask whether the input was complete, the rule was current, the permission was sufficient, and the operator had a safe way to stop. Only then should they interpret execution errors or set coaching priorities. A lower rate is not automatically better if it was achieved by silent assumptions. The better measure is a traceable record with an honest disposition.' },
      { heading: 'FAQs', body: 'Should blocked records count as failures? They should count in reporting, but with their reason. Is 100 percent completion a good target? Not when it rewards unsupported guesses. How much should be sampled? Enough to cover each important state and exception type; the exact size depends on risk and volume. Who approves a corrected source? The owner of that data or process.' }
    ], sources: [src('NIST Engineering Statistics Handbook', 'https://www.itl.nist.gov/div898/handbook/'), src('NIST SP 800-171 Rev. 3', 'https://csrc.nist.gov/pubs/sp/800/171/r3/final'), src('Philippine Statistics Authority Labor Force Survey', 'https://psa.gov.ph/statistics/labor-force-survey')]
  },
  {
    slug: 'philippines-offshore-customer-record-redaction', title: 'Customer Record Redaction in Philippines Support Work', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Hiring Controls',
    excerpt: 'How to evaluate whether support notes preserve useful context while limiting unnecessary exposure of customer information.',
    stats: ['A useful note needs context, but not every available field', 'Redaction quality should be reviewed at the point of capture and handoff'],
    sections: [
      { heading: 'Research question', body: 'Can a Philippines-based support role preserve the facts needed for the next owner without copying unnecessary customer information into tickets, notes, or handoff messages? This question sits at the boundary between service continuity and data minimization. A blank note forces repetition. An unrestricted note creates another copy of sensitive information. The study tests whether the role has a clear purpose, field rule, and stop condition for recording data.' },
      { heading: 'Evidence scope and method', body: 'Use synthetic cases that contain identifiers, payment references, health or identity details where relevant, and ordinary service context. Ask the operator to create a note for a routine handoff, a disputed record, and a case needing escalation. Review what was copied, what was omitted, who can view it, and whether the source record was linked. The NIST Privacy Framework provides a way to discuss data processing risk. NIST access-control guidance supports restricting the note system to the people and tasks that need it.' },
      { heading: 'What good looks like', body: 'A good note explains the customer’s request, the action already taken, the open question, the next owner, and the source location. It uses a stable reference instead of repeating a full identifier. It distinguishes a customer statement from a verified fact. It does not include passwords, authentication codes, full payment details, or unrelated history. When the operator is unsure whether a field is permitted, the correct action is to pause and ask the data owner.' },
      { heading: 'Review design', body: 'Sample notes at capture, after handoff, and after closure. Record the data category, purpose, audience, retention rule, and reviewer disposition. A note can be technically redacted and still disclose too much through a combination of details. Check search permissions and export behavior where the workflow allows it. Keep any review dataset masked. A role that writes notes should not automatically receive authority to change the customer record or decide the retention period.' },
      { heading: 'Limitations', body: 'Synthetic cases do not show every local privacy requirement, customer preference, or system integration. Redaction standards also depend on the company’s legal and contractual context, which this research does not establish. A review of visible notes cannot prove that a hidden export or screenshot does not exist. The result should therefore be treated as a control test against the approved process, followed by legal or privacy-owner review where needed.' },
      { heading: 'Evidence-led conclusion', body: 'The safest support note is purposeful and reviewable. It carries enough context for the next permitted action while pointing back to the authoritative record instead of creating a second customer file. Managers should measure unnecessary fields, missing handoff context, and access to the resulting notes separately. That distinction helps the team improve the form, the training, or the permission boundary without asking an operator to make a legal judgment.' },
      { heading: 'FAQs', body: 'Should support notes contain the full customer name? Use the approved identifier rule, not a blanket habit. Can screenshots replace notes? No. They may expose more information and can be hard to search. Who decides whether a field is sensitive? The company’s privacy or data owner should define the rule. Is redaction only a writing issue? No. Access, exports, retention, and downstream systems also matter.' }
    ], sources: [src('NIST Privacy Framework', 'https://www.nist.gov/privacy-framework'), src('NIST SP 800-53 Rev. 5', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('U.S. Department of Justice Effective Communication', 'https://www.ada.gov/resources/effective-communication/')]
  },
  {
    slug: 'philippines-offshore-publishing-source-traceability', title: 'Source Traceability for Philippines-Based Publishing Support', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Workflow Design',
    excerpt: 'A research model for checking whether a distributed publishing role can connect a public claim to the source, date, and review decision behind it.',
    stats: ['A source list is weaker than claim-level traceability', 'Publishing support needs a stop rule for claims that cannot be verified'],
    sections: [
      { heading: 'Research question', body: 'Can a Philippines-based publishing operator show which source supports each material public claim, when that source was checked, and who approved the interpretation? The question concerns an operational role in a niche where readers may use articles to make staffing, access, or workflow decisions. A list of links at the bottom of a page does not prove that a number or recommendation came from any one of them. This study examines the connection between claim, evidence, wording, and approval.' },
      { heading: 'Method and evidence', body: 'Choose a sample of drafts across research, service, and educational pages. Mark factual claims, analysis, examples, and calls to action. For each factual claim, record the source URL, relevant passage or dataset, access date, source scope, and reviewer decision. NIST configuration-management guidance supports retaining version and change information. The World Bank and Philippine Statistics Authority provide examples of public sources whose scope must be described rather than stretched into a company result. The method does not infer business performance from national statistics.' },
      { heading: 'Interpretation', body: 'A claim can be supported, overextended, outdated, or unsupported. A source may establish a labor statistic but not the quality of a particular provider. A security standard may describe a control principle but not prove that a workflow implements it. An operator can identify these boundaries and flag the sentence. The authorized editor or subject owner should decide whether to narrow, remove, or approve the wording. Good publishing support includes a stop state when the source does not carry the claim.' },
      { heading: 'Workflow test', body: 'Give the operator a brief with a defined audience and a small set of approved sources. Include one source with a date change, one claim that needs a limitation, and one tempting but irrelevant link. Review the source map before publication and after a correction. Track claims with missing evidence, citations attached to the wrong sentence, and source dates omitted from time-sensitive material. Keep internal evidence records separate from public copy.' },
      { heading: 'Limitations', body: 'Source traceability cannot guarantee that a reputable source is free from error. A public page can change after review, and a link can remain live while its underlying data is revised. The sample may also favor well-documented topics. This study does not replace legal review, fact checking for regulated claims, or a company’s own editorial policy. It shows whether the stated publishing process leaves an inspectable path for the claims examined.' },
      { heading: 'Evidence-led conclusion', body: 'A research article is more trustworthy when its important claims have an explicit evidence path and a bounded interpretation. Managers should inspect the claim map, not count links. For offshore publishing support, the role can gather sources, record provenance, draft cautious language, and flag gaps. Final decisions about public claims, sensitive topics, and company representations belong to the authorized reviewer. That boundary protects both the reader and the operator.' },
      { heading: 'FAQs', body: 'Are three links enough? Quantity does not replace relevance. Should every sentence have a citation? No, but material factual claims should have an identifiable basis. Can a source support an analysis? It can inform the analysis, but the conclusion must be labeled as interpretation. What happens when a source disappears? Record the issue and replace or remove the claim after review.' }
    ], sources: [src('NIST Configuration Management', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('Philippine Statistics Authority Labor Force Survey', 'https://psa.gov.ph/statistics/labor-force-survey'), src('World Bank Philippines Digital Economy Report', 'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf')]
  },
  {
    slug: 'philippines-offshore-schedule-change-handoff', title: 'Schedule-Change Handoffs in Philippines-Based Support', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Scope Benchmarks',
    excerpt: 'What evidence shows that a schedule change preserves queue ownership, customer commitments, and safe escalation across a distributed team.',
    stats: ['A schedule handoff transfers state, not just a calendar slot', 'The next owner must be visible before a shift ends'],
    sections: [
      { heading: 'Research question', body: 'When a Philippines-based support schedule changes, does the handoff preserve the state of open work well enough for the next owner to act safely? A shift ending is not the same as a task ending. The next person needs to know what was received, what was done, what is blocked, and which decisions remain with the client. This research separates coverage from continuity. It does not assume that a longer overlap or a particular work schedule guarantees a better result.' },
      { heading: 'Method', body: 'Select handoffs from routine, returned, customer-impacting, and owner-dependent work. Compare the outgoing record with the incoming operator’s first action. Record queue state, last evidence, next action, due rule, customer promise if one exists, and escalation owner. NIST audit and accountability guidance supports attributable event records. ILO material on homeworking provides context for remote-work conditions, but it does not define a service level for this company. Use the client’s approved schedule and role boundary as the test standard.' },
      { heading: 'Continuity findings', body: 'Classify each handoff as complete, incomplete but recoverable, or unsafe to continue. A complete handoff does not need a long narrative. It needs the source record, a current status, a clear next action, and enough reason for any stop. An incoming operator who can find the work but not the approval owner has not received a complete handoff. Check whether the same missing field recurs. Repetition points to a form or queue design issue rather than an individual memory problem.' },
      { heading: 'Coverage and authority', body: 'A schedule plan can show who is available, but it cannot grant authority to make a client decision. If an item waits for approval, mark it owner-dependent rather than asking the next operator to improvise. If a customer promise is at risk, escalate using the approved route and preserve the timestamp. The handoff should also record which systems were used, without copying passwords or sensitive data into a personal message. Continuity depends on both state and permission.' },
      { heading: 'Limitations', body: 'Historical handoff records may reflect different staffing, tools, or instructions. A small sample may miss the rare case that causes the greatest harm. Time stamps can also be written after the fact. The findings apply to the queue, period, and role tested. They cannot establish that a schedule is universally adequate or that a person’s performance explains every delayed item. Repeat the study after a system or shift design changes.' },
      { heading: 'Evidence-led conclusion', body: 'A reliable schedule handoff leaves the next owner with an honest state of work and a safe action. Managers should measure incomplete handoffs by missing evidence, missing authority, and missing ownership instead of using one continuity percentage. The fix may be a field, a brief, an overlap, or a client response path. A handoff is successful when it protects the queue from silent assumptions and makes the next decision visible.' },
      { heading: 'FAQs', body: 'Does every handoff need a meeting? No. A well-designed record may be enough for routine work. Is overlap the main measure? No. Test whether the next owner can act from the evidence. Can the incoming operator close an old item? Only if the workflow permits it. What should happen when the record is incomplete? Hold or escalate it, then repair the handoff rule.' }
    ], sources: [src('NIST Audit and Accountability', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('ILO Homeworking in the Philippines', 'https://researchrepository.ilo.org/esploro/outputs/995219318102676'), src('Philippine Statistics Authority Labor Force Survey', 'https://psa.gov.ph/statistics/labor-force-survey')]
  },
  {
    slug: 'philippines-offshore-qa-sample-drift', title: 'Quality-Sample Drift in Philippines-Based Operations', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Scope Benchmarks',
    excerpt: 'How a quality sample changes meaning when task mix, reviewer rules, or the source queue changes without a matching note.',
    stats: ['A stable score requires a stable definition of the work sampled', 'Sample composition should be reported beside the result'],
    sections: [
      { heading: 'Research question', body: 'Does a quality score for Philippines-based operations still mean the same thing after the queue, task mix, reviewer, or instructions change? A score can rise because easy records dominate the sample, or fall because the team began receiving more exceptions. Without the sample context, a manager may coach the wrong person or change a working process. This study asks whether the quality record preserves enough information to interpret movement over time.' },
      { heading: 'Evidence scope and method', body: 'For each review period, record the population definition, task categories, sample rule, reviewer, rubric version, and reason for exclusion. Compare ordinary, returned, and high-risk records separately. NIST measurement guidance supports defining the object and method before comparing results. NIST assessment guidance supports retaining evidence for review. The research does not treat a quality score as a universal measure of an individual, and it avoids using labor-market data as a proxy for performance.' },
      { heading: 'Detecting drift', body: 'Look for changes in the denominator, acceptance rule, field requirements, and task distribution. A sample that once covered only routine data entry may later include customer escalations or source corrections. That is a real change in work, not necessarily a decline. Also check reviewer calibration. If one reviewer starts interpreting a rule differently, the apparent trend may be a measurement change. Keep returned work visible and code the first material defect.' },
      { heading: 'Use in management', body: 'The sample should guide a conversation about the workflow. If one defect category grows, inspect the input, procedure, access, and approval path before assigning coaching. If the task mix changed, publish a separate baseline. If a reviewer cannot explain the rubric, pause the score and calibrate. A support operator should know the evidence used to evaluate permitted work, while sensitive customer records remain protected and accessible only to authorized reviewers.' },
      { heading: 'Limitations', body: 'No sample can capture every future case, and small samples are sensitive to one difficult record. A stable rubric may still miss a new risk. Reviewers can also record the wrong category. The result describes the measurement design and selected period. It does not predict future quality or establish causation from a score alone. Keep the evidence date and revise the baseline when the queue changes materially.' },
      { heading: 'Evidence-led conclusion', body: 'Quality comparisons are fair only when the work and the measuring rule remain visible. Report score, sample composition, rubric version, reviewer, and defect categories together. That makes it possible to tell whether a change belongs to the operator, the queue, the source material, or the review method. For offshore support, this is a practical protection against both hidden process defects and unsupported claims about a person’s capability.' },
      { heading: 'FAQs', body: 'Should every period use the same sample size? Not necessarily, but the rule must be stated. Can easy items be excluded? Only with a documented reason and a separate report. Is one reviewer enough? It can be, if the rubric and calibration are controlled. When should the baseline change? After a material change to task mix, instructions, system, or risk.' }
    ], sources: [src('NIST Measurement and Analysis guidance', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('NIST Assessment Procedures', 'https://csrc.nist.gov/pubs/sp/800/53/a/final'), src('NIST Engineering Statistics Handbook', 'https://www.itl.nist.gov/div898/handbook/')]
  },
  {
    slug: 'philippines-offshore-approval-queue-congestion', title: 'Approval-Queue Congestion in Philippines Support Work', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Workflow Design',
    excerpt: 'A study of whether an approval queue is waiting on too many decisions, unclear thresholds, or incomplete packets from a support workflow.',
    stats: ['Approval aging is a system signal before it is an operator score', 'A complete packet should make the owner decision easier to locate'],
    sections: [
      { heading: 'Research question', body: 'Why does an approval queue serving a Philippines-based support workflow age? The cause may be a high volume of decisions, missing evidence, unclear authority, or an owner who cannot see the request at the right time. The operator may have prepared the packet correctly and still be unable to close the work. This study separates preparation time from decision waiting so a manager can change the right part of the system.' },
      { heading: 'Method', body: 'Trace a sample from intake through preparation, submission, owner review, return, approval, and closure. Capture timestamps, packet completeness, decision type, owner, return reason, and any duplicate request. NIST audit guidance supports preserving attributable events. NIST least-privilege guidance supports keeping approval authority with the authorized owner. Do not use a national employment statistic to set a client-specific queue target. Use the actual queue definition and agreed response rule.' },
      { heading: 'Analysis', body: 'Separate items waiting for missing input from items waiting for a valid decision. Review the distribution, not just the average age. If many packets return for the same missing field, repair intake. If packets are complete but unreviewed, the bottleneck is owner capacity or routing. If owners disagree about authority, clarify the decision matrix. An operator should be able to see the holding state and next owner rather than repeatedly resubmit the same request.' },
      { heading: 'Role boundary', body: 'Preparation can include collecting source records, checking required fields, and explaining the question. It should not include approving a payment, changing a customer commitment, or accepting a policy exception unless the client has explicitly delegated that authority. The support role can flag an approaching due point and escalate a blocked request. It should not bypass the queue by using an unapproved personal message or by representing silence as approval.' },
      { heading: 'Limitations', body: 'Queue timestamps may be incomplete or recorded late. A short study may coincide with a temporary volume spike. Approval rules also differ by company and risk. The evidence can show where the observed queue spent time, but it cannot prove that one intervention will remove the delay. Reassess after changing routing, packet fields, owner coverage, or approval thresholds.' },
      { heading: 'Evidence-led conclusion', body: 'Approval congestion becomes actionable when the record distinguishes preparation, waiting, return, and decision time. Managers can then decide whether to improve the request packet, assign a clearer owner, or change the authority boundary. The research supports transparency, not pressure to make an offshore operator decide without permission. A visible blocked state is safer than a queue that looks clear because decisions were made informally.' },
      { heading: 'FAQs', body: 'Should approval waiting count against the operator? Report it, but separate it from handling time. Is a complete packet always approved? No. Completeness supports review but does not replace judgment. Can the operator remind the owner? Yes, through the approved route. Can silence be treated as approval? Only if the written policy explicitly says so and the authorized owner accepts that design.' }
    ], sources: [src('NIST Audit and Accountability', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('NIST Least Privilege guidance', 'https://csrc.nist.gov/pubs/sp/800/171/r3/final'), src('Philippine Statistics Authority Labor Force Survey', 'https://psa.gov.ph/statistics/labor-force-survey')]
  },
  {
    slug: 'philippines-offshore-credential-sharing-risk', title: 'Credential-Sharing Risk in Philippines-Based Support', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Hiring Controls',
    excerpt: 'How to research whether a support workflow encourages shared credentials, weak recovery practices, or unsafe workarounds.',
    stats: ['Shared credentials remove individual accountability', 'A workaround is evidence of a workflow gap, not permission to widen access'],
    sections: [
      { heading: 'Research question', body: 'Does a Philippines-based support workflow let an operator complete permitted work with an attributable account, or does the process quietly encourage shared credentials and unsafe recovery? The question is about the design of access, not the trustworthiness of a worker. When a role cannot reach the needed record, people may exchange passwords, use a colleague’s session, or move a file to a personal channel. The study looks for those pressures before treating them as misconduct.' },
      { heading: 'Evidence scope and method', body: 'Map each task to its system, account type, permission, authentication method, recovery owner, and escalation path. Use a tabletop case in which the normal login fails and another in which the role needs a temporary permission. Review logs and the written procedure without collecting passwords or authentication codes. NIST identity guidance supports named accounts and multi-factor authentication. CIS account-management guidance supports reviewing account ownership and lifecycle. The test measures whether the workflow has a safe route.' },
      { heading: 'Findings', body: 'Record shared accounts, dormant access, unowned recovery methods, permissions broader than the task, and instructions that tell people to work around a block. A failed login should produce an approved help path, not a request for a coworker’s password. If the operator cannot complete the task because the role lacks access, that may be the intended boundary. The client owner should decide whether to change the permission, not the operator under time pressure.' },
      { heading: 'Operational response', body: 'Create an access map that names the business purpose, owner, permitted action, and review date for each system. Use a temporary access process with an expiry and a record of approval. Make safe stopping visible in the role brief. Where the work can be completed with a redacted export or a read-only view, say so explicitly. Do not treat a successful task completed through a shared account as a quality success because its evidence is weaker.' },
      { heading: 'Limitations', body: 'Administrative logs vary by provider and may not show copied credentials or conversations outside the system. A tabletop cannot prove that no unsafe workaround occurs later. Security requirements also depend on the company’s risk, contracts, and applicable law. This study identifies design and evidence gaps. It is not a forensic conclusion about any individual or a substitute for a security investigation.' },
      { heading: 'Evidence-led conclusion', body: 'A support role is easier to govern when it can succeed with a named account and can stop safely when access is wrong. Managers should measure attributable access, approved exceptions, orphaned accounts, and recurring access-related blockers. If a workflow repeatedly pushes operators toward sharing credentials, repair the workflow and ownership. Do not solve a scheduling problem by weakening the identity boundary.' },
      { heading: 'FAQs', body: 'Is a shared mailbox always unsafe? It depends on the approved design, but individual actions still need attribution. Can an operator borrow a manager’s session? No, use the authorized access path. Should every access request be permanent? No, use the least access needed and an expiry when practical. What if a customer is waiting? Escalate through the approved route rather than bypassing identity controls.' }
    ], sources: [src('NIST Digital Identity Guidelines', 'https://pages.nist.gov/800-63-4/sp800-63b.html'), src('CIS Controls v8 Account Management', 'https://www.cisecurity.org/controls/account-management'), src('NIST SP 800-171 Rev. 3', 'https://csrc.nist.gov/pubs/sp/800/171/r3/final')]
  },
  {
    slug: 'philippines-offshore-translation-review-boundary', title: 'Translation Review Boundaries for Philippines Support Content', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Hiring Controls',
    excerpt: 'A study of when language support can clarify a customer message and when the work requires a subject-matter or policy owner.',
    stats: ['Language clarity and policy interpretation are different tasks', 'A reviewer needs the source meaning and the approved response boundary'],
    sections: [
      { heading: 'Research question', body: 'Can a Philippines-based support role translate or clarify customer language without silently changing the policy meaning, commitment, or risk of the response? Language work often sits beside customer support, publishing, and operations. The role may explain a phrase, preserve the customer’s request, or prepare a draft. It should not turn an ambiguous sentence into an unapproved promise. This research tests the boundary between communication assistance and decision-making.' },
      { heading: 'Method and evidence', body: 'Use synthetic or redacted messages with ordinary wording, regional expressions, ambiguous intent, and a request involving a consequential decision. Compare the source message, the translation or summary, the proposed response, and the reviewer’s interpretation. The U.S. Department of Justice guidance on effective communication provides context for communicating with people with disabilities. ILO research on homeworking provides work-context background, not a language-performance benchmark. The approved policy owner remains the authority for the response.' },
      { heading: 'What to inspect', body: 'Check whether the operator preserved uncertainty, separated a customer statement from a verified fact, and flagged a phrase that could change the requested action. Reviewers should mark additions, omissions, tone changes, and policy interpretations separately. A good escalation includes the original wording, the plain-language question, and the specific point that needs confirmation. Do not score accent, nationality, or a customer’s preferred phrasing as a standalone quality judgment.' },
      { heading: 'Role boundary', body: 'The support role can ask a clarifying question from an approved script, summarize a request, and route a language concern. It may draft a response using an approved source. It should not decide eligibility, waive a rule, promise a refund, or interpret a legal or medical issue without the authorized owner. A customer’s frustration may require empathy, but empathy does not change the approval path. The role brief should make that distinction explicit.' },
      { heading: 'Limitations', body: 'A controlled language sample cannot represent every dialect, customer history, product term, or sensitive conversation. Translation quality can also depend on domain vocabulary that changes over time. Reviewers may disagree about tone even when meaning is preserved. The study therefore describes the cases and rubric used. It does not rank a person’s overall language ability or prove that a response will work for every customer.' },
      { heading: 'Evidence-led conclusion', body: 'Language support is safest when the workflow preserves the original meaning and sends policy decisions to the right owner. Managers should track changed meaning, missing context, unnecessary escalation, and unresolved language cases separately. That evidence can improve scripts and source material without turning a communication task into an unsupported judgment about a worker or customer. A clear stop rule protects service quality and authority at the same time.' },
      { heading: 'FAQs', body: 'Should every message receive a second-language review? No, use the risk and complexity of the case. Can a fluent operator interpret policy? Fluency does not grant policy authority. Should tone be measured? It may be reviewed against an approved standard, but not as a proxy for identity. What belongs in an escalation? The original wording, the relevant context, the uncertainty, and the decision owner.' }
    ], sources: [src('U.S. Department of Justice Effective Communication', 'https://www.ada.gov/resources/effective-communication/'), src('ILO Homeworking in the Philippines', 'https://researchrepository.ilo.org/esploro/outputs/995219318102676'), src('NIST Privacy Framework', 'https://www.nist.gov/privacy-framework')]
  },
  {
    slug: 'philippines-offshore-remote-onboarding-evidence', title: 'Evidence Quality in Remote Onboarding for Philippines Roles', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Scope Benchmarks',
    excerpt: 'What a first-week onboarding record can prove about a role, and what it cannot prove about future performance.',
    stats: ['Onboarding evidence should test the actual role boundary', 'A completed orientation is not evidence that the workflow is ready'],
    sections: [
      { heading: 'Research question', body: 'What can a first-week onboarding record prove for a Philippines-based support role? Teams often record that a person attended a call or read a procedure. Those events show exposure, not readiness to perform the real task with the correct evidence and stop rules. This study asks whether onboarding tests the work itself, including ordinary input, an exception, an access boundary, and a handoff to the owner.' },
      { heading: 'Method', body: 'Map the first-week sample to the role brief. Use synthetic or redacted work with representative inputs and one case that should be escalated. Record the instruction version, systems used, actions taken, evidence attached, reviewer notes, and unresolved questions. The U.S. Department of Labor and EEOC guidance on selection procedures support keeping a work evaluation tied to the job and applied consistently. NIST access guidance supports testing permissions without granting unnecessary production access. Public workforce data does not validate an individual result.' },
      { heading: 'Evidence categories', body: 'Separate orientation evidence, observed practice, independent completion, escalation behavior, and reviewer acceptance. A person may understand a procedure but still lack access. Another may complete the task but fail to preserve the source. A safe escalation can be the correct result on the boundary case. Record each distinction instead of compressing the week into ready or not ready. If the same question appears repeatedly, repair the instruction before assuming a training deficit.' },
      { heading: 'Decision use', body: 'The client owner should decide whether the role can move from supervised practice to permitted recurring work. The decision should name the task scope, access, review sample, open gaps, and next check. Avoid using live customer data as a test unless the approved process explicitly permits it. Keep hiring judgment, compensation, and role expansion outside the operator’s control. A first-week record is an operational evidence packet, not a promise about future outcomes.' },
      { heading: 'Limitations', body: 'The first week is a narrow window. Coaching, unfamiliar tools, and artificial examples can affect results. A successful sample cannot cover rare customer or commercial consequences. Reviewers may also change the standard while the onboarding is underway. Publish the evidence date and instruction version, then retest after material workflow or access changes. The record supports a bounded readiness decision, not a general claim about the person.' },
      { heading: 'Evidence-led conclusion', body: 'Good onboarding tests the role’s real boundaries in a controlled setting. It gives the owner evidence about task understanding, source handling, access, and escalation. Managers should retain the sample and reviewer reasoning while protecting personal information. If onboarding exposes an unclear rule, the workflow owns that lesson. A person should not be marked ready simply because the calendar says the first week is over.' },
      { heading: 'FAQs', body: 'Is orientation attendance enough? No. Observe representative work. Should speed be scored? Only where the role has a defined time requirement and quality remains visible. Can a work sample replace all hiring evidence? No, it covers only the tested conditions. Who approves readiness? The authorized role owner, using the stated rubric.' }
    ], sources: [src('U.S. Department of Labor Selection Procedures', 'https://www.dol.gov/agencies/ofccp/sex-discrimination/selection-procedures'), src('U.S. EEOC Employment Tests and Selection Procedures', 'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures'), src('NIST SP 800-171 Rev. 3', 'https://csrc.nist.gov/pubs/sp/800/171/r3/final')]
  },
  {
    slug: 'philippines-offshore-workflow-rollback-readiness', title: 'Rollback Readiness for Philippines-Based Workflow Changes', published: '2026-08-18', thumbnail: '/research/research-default.svg', cluster: 'Workflow Design',
    excerpt: 'How to test whether a distributed support workflow can reverse a bad rule or permission change without losing accountability.',
    stats: ['A rollback plan needs a prior approved state and an owner', 'Restoring a document does not necessarily restore permissions or queue state'],
    sections: [
      { heading: 'Research question', body: 'If a workflow change harms a Philippines-based support queue, can the team return to a known safe state without losing work history or widening access? Changes can affect instructions, source versions, permissions, forms, routing, and customer messages. A simple copy of the old procedure may not reverse a changed system setting or records already processed under the new rule. This study examines whether rollback is designed as an accountable operation.' },
      { heading: 'Method and evidence', body: 'Choose a low-risk test change and document the current version, owner, affected tasks, permissions, queue records, and communication path. Define the trigger for reversal, pause rule, prior approved state, reconciliation method, and verification evidence. NIST configuration-management guidance supports controlled changes and known versions. NIST incident-handling guidance supports recording response actions and lessons. Do not run the exercise against live customer work without explicit authorization. Use synthetic records where possible.' },
      { heading: 'Readiness findings', body: 'A rollback is ready when someone can name what changes, who may approve the reversal, which records are affected, and how the team proves recovery. Check for partial completion, duplicate work, stale instructions, permissions that remain open, and messages that need correction. A rollback may require a safe pause rather than immediate continuation. Keep the original change record. Erasing history makes it harder to understand which decision created the problem.' },
      { heading: 'Role boundary', body: 'A support operator can stop assigned work, preserve evidence, and report the observed impact. The operator should not independently change a queue rule, revoke another person’s access, or announce a customer-facing correction unless the role explicitly includes that authority. The client owner coordinates the decision and confirms the restored state. That boundary matters in offshore workflows because a time-zone gap can tempt a well-meaning operator to fix a problem outside the brief.' },
      { heading: 'Limitations', body: 'A tabletop or low-risk exercise cannot reproduce every vendor failure, integration delay, or customer consequence. The old state may also depend on data that has changed since the original deployment. Recovery evidence can show that the tested path worked, not that every hidden dependency was restored. Repeat after a material system, policy, or permission change. Seek security or legal review where the change affects regulated or sensitive records.' },
      { heading: 'Evidence-led conclusion', body: 'Rollback readiness is a property of the workflow, not a personal trait of the operator. It depends on versions, authority, evidence, pause rules, and reconciliation. Managers should test those pieces together and keep the result separate from ordinary quality scoring. A safe team can explain how to stop, who decides, and what proof closes the incident. That is stronger than relying on memory or a promise to fix the issue later.' },
      { heading: 'FAQs', body: 'Is a backup document a rollback plan? No. Include permissions, queue state, communication, and reconciliation. Can the operator reverse a mistake immediately? Only when the approved role permits it. Should rollback delete bad records? Preserve the history and follow the owner’s correction process. How often should the plan be tested? After material changes and at a cadence set by the risk owner.' }
    ], sources: [src('NIST Configuration Management', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'), src('NIST Computer Security Incident Handling Guide', 'https://csrc.nist.gov/pubs/sp/800/61/r2/final'), src('NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework')]
  }
];

const decisionNotes = [
  'For triage, the useful record is the reasoned category and the evidence that made the category defensible. A manager can compare an ordinary case with a boundary case without asking the operator to reveal private reasoning. The review should ask whether the stated rule was available, whether the selected route matched the rule, and whether the record named a person who could change the outcome. If the case was held, the hold should explain what was missing. That makes a pause a visible control rather than an unexplained delay.',
  'For knowledge work, the important distinction is between a page that can be found and a page that can be trusted. The review should capture the source identity, effective date, and any conflict that remained after searching. When the answer is absent, the operator should preserve the question and route it to the source owner. A later editor can then improve the library from real unanswered demand. This is more useful than asking people to memorize more pages or quietly copy an informal answer into the queue.',
  'For data entry, the exception record should explain why a value was not entered and what would make the item ready. A source defect belongs with the source owner. A rule gap belongs with the process owner. A permission block belongs with the access owner. An execution error may belong in coaching, but only after the sample and instruction are clear. Reporting those paths separately helps the client spend review time where the workflow actually creates risk instead of treating every incomplete row as the same kind of failure.',
  'For redaction, the reviewer should inspect both usefulness and exposure. Removing every detail can make a handoff impossible, while copying every detail creates an unnecessary second record. The test should therefore ask what the receiving role must know, where that information already lives, and which fields can be represented by a masked reference. The operator needs a clear route for uncertainty. The privacy owner needs evidence that the route is followed. Neither side should rely on an informal promise that people will remember which details are sensitive.',
  'For publishing, the source map should let another reviewer move from a sentence to the evidence and back again. The record should state whether the sentence reports a fact, draws an analysis, or gives a bounded recommendation. A public statistic can provide context without proving a provider result. A standard can describe a control without proving implementation. That distinction belongs in the wording. When the source is too narrow, the safest editorial action is to narrow the sentence, add a limitation, or remove it before a reader mistakes context for evidence.',
  'For schedule handoffs, the record should show the state of each open item at the moment responsibility changes. It should identify work that can continue, work that needs an owner decision, and work that must pause because a source or permission is missing. A calendar entry cannot carry all of that context by itself. The queue or case record must remain authoritative. Review the first action by the incoming owner. If that person has to ask the same basic questions repeatedly, the handoff design is not carrying enough state.',
  'For quality samples, keep the population definition beside the score. A result from routine records should not be compared silently with a result from a queue that now contains exceptions, source corrections, or customer-impacting cases. Reviewers should also record the rubric version and any calibration discussion. When the measuring rule changes, start a new baseline or explain the bridge. This keeps the score useful for management without pretending that a number has the same meaning after the work itself or the review standard has changed.',
  'For approval queues, the packet should make the decision visible without making the decision automatic. The operator can gather evidence, identify a discrepancy, and write the question that needs an owner answer. The packet should also show what is not known. That protects the approver from a false sense of completeness and protects the operator from pressure to fill the gap. Review queue age by state and reason. A complete packet waiting for a decision is different from an incomplete packet waiting for preparation.',
  'For credentials, a blocked task is a useful security signal. The record should show which permission was needed, who owns it, what the approved alternative is, and when the request expires. A shared password may make a queue look productive, but it removes attribution and makes later review weaker. Test recovery and temporary access as part of the workflow. If the safe path takes too long, fix its ownership and response rule. Do not solve the delay by turning a narrow support role into an administrator.',
  'For translation review, preserve the original wording alongside the plain-language interpretation and the unresolved question. That lets the owner check whether meaning changed without judging accent or identity. A language helper can make communication clearer, but clarity does not grant authority to change policy, waive verification, or promise an outcome. Sample cases with uncertainty as well as ordinary requests. The right result may be a careful escalation. Measure whether the next owner receives enough context, not whether every ambiguous message was forced into a confident answer.'
];

const evidenceAppendix = (post: ResearchPost) => `The evidence should be read as a description of ${post.title}, not as a general claim about every Philippines-based worker or every offshore arrangement. Start with the unit being studied: a ticket, note, record, handoff, approval packet, or controlled test case. Define the time window and the owner of the process before comparing results. Keep the source record attached to the observation, and record when the observation was made. If a system uses a local time zone, state that fact rather than silently converting timestamps. If a reviewer changes a category after the first decision, keep both the original and revised reason so the measurement can be audited.

Facts, analysis, and recommendations should remain separate. A fact is something the selected record or external source establishes. Analysis explains what that fact may mean for the workflow. A recommendation is a decision about what the client should test or change. One should not be used as proof of another. For example, a public description of a control can inform a role boundary, but it cannot prove that this workflow follows the control. A workforce statistic can describe context, but it cannot establish a candidate’s skill or a provider’s result. This separation is especially important when a reader may use the article to make a staffing, access, customer, or publishing decision.

The review should also record what was not observed. Missing logs, unavailable source versions, untested exceptions, and changes after the evidence window all narrow the conclusion. Do not fill those gaps with a confident assumption. Use a safe stop, a named owner, and a next evidence request. When a pattern repeats, compare the cost of repairing the instruction, form, queue, permission, or approval path with the cost of coaching. The correct intervention depends on the cause. Keep the public conclusion modest enough that it remains true if an unexamined edge case appears later. That is the standard used here: a practical finding that another reviewer can reproduce from the stated scope, not a promise about future performance. This boundary keeps the article useful when the queue, reviewer, or source changes.`;

export const august18ResearchBatch: readonly ResearchPost[] = august18ResearchBatchAll.slice(0, 10).map((post, index) => ({ ...post, sections: [...post.sections, { heading: ['Decision record', 'Source trust test', 'Exception reading', 'Minimum necessary record', 'Claim boundary', 'Handoff state', 'Baseline note', 'Owner decision', 'Access evidence', 'Meaning check'][index], body: decisionNotes[index] }, { heading: 'Evidence boundary', body: evidenceAppendix(post) }] }));
